import {test,expect} from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import fs from 'node:fs'

const company='bd0b8b1d78824672a8c80bce328ec215'
const shots='../.cache/screenshots/kit-regressao/appserver'
test('links históricos não reutilizam a porta de outra construção após reinício',async({page,request})=>{
 const old=await(await request.get('/api/ed/fluxos/ba5aad220d324a939022bb349e8bacdb')).json()
 const check=old.etapas.find((s:{nome:string})=>s.nome==='verificar').resultado
 expect(check.url).toBe('http://127.0.0.1:5163/')
 expect(check.url_ativa).toBeNull()
 const current=await(await request.get('/api/ed/fluxos/41f2ef42baad4f97991e6e795ec7be47')).json()
 expect(current.etapas.find((s:{nome:string})=>s.nome==='verificar').resultado.url_ativa).toBe('http://127.0.0.1:5163/')
 await page.goto('/assistente')
 await page.getByRole('button',{name:/Execuções \(/}).click()
 const card=page.locator('.ed-flow-card').filter({has:page.getByRole('heading',{name:/pesquisar ·/})})
 await expect(card.getByText(/Prévia não servida nesta sessão/)).toBeVisible()
 await expect(card.getByRole('link',{name:'Abrir prévia local ↗',exact:true})).toHaveCount(0)
})
test('5128: modelo validado, alternativas explícitas, versões e OAuth separado',async({page,request})=>{
 fs.mkdirSync(shots,{recursive:true})
 const before=await(await request.get(`/api/ed/empresas/${company}`)).json()
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto(`/empresas/${company}`)
 await page.getByRole('button',{name:'Construir prévia',exact:true}).click()
 await expect(page.getByText(/Modelo selecionado:/)).toContainText('Execução concluída')
 await expect(page.getByLabel('Modelo do runtime')).toHaveValue('gpt-6.1-sol')
 await expect(page.getByText('Resposta concluída: EDY_CRM_OK').first()).toBeVisible()
 await expect(page.locator('.ed-runtime-job').first()).toContainText('concluida')
 expect((await new AxeBuilder({page}).analyze()).violations).toEqual([])
 await page.screenshot({path:`${shots}/crm-desktop.png`,fullPage:true})
 await page.getByLabel('Alternativa do catálogo').selectOption('gpt-6-sol')
 await expect(page.getByLabel('Modelo do runtime')).toHaveValue('gpt-6-sol')
 await expect(page.getByText(/Modelo selecionado:/)).toContainText('Modelo listado')
 await page.getByLabel('Modelo do runtime').fill('gpt-6.1-sol')
 await page.getByLabel('Pedido para construir ou refinar').fill('Pedido manual mantido durante a mudança de modo.')
 await page.getByLabel('Autenticação da construção').selectOption('oauth_plano')
 await expect(page.getByText(/OAuth do CRM: sem_autorizacao/)).toBeVisible()
 await expect(page.getByLabel('Modelo do runtime')).toHaveValue('gpt-6.1-sol')
 await expect(page.getByLabel('Pedido para construir ou refinar')).toHaveValue('Pedido manual mantido durante a mudança de modo.')
 await page.getByLabel('Autenticação da construção').selectOption('plano')
 for(const width of [320,390,768]){
  await page.setViewportSize({width,height:844})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
 }
 await page.setViewportSize({width:390,height:844})
 expect((await new AxeBuilder({page}).analyze()).violations).toEqual([])
 await page.screenshot({path:`${shots}/crm-mobile.png`,fullPage:true})
 await expect(page.getByText(/model is not supported/).first()).toBeVisible()
 const completed=(await(await request.get(`/api/ed/empresas/${company}/construcoes`)).json()).filter((j:{tipo:string;estado:string})=>j.tipo==='codex_construcao'&&j.estado==='concluida')
 await expect(page.getByLabel('Prévia anterior para refinar').locator('option')).toHaveCount(completed.length+1)
 const jobs=await(await request.get(`/api/ed/empresas/${company}/construcoes`)).json()
 const failed=jobs.find((j:{tipo:string;estado:string})=>j.estado==='erro'&&j.tipo==='codex_construcao')
 await page.getByRole('button',{name:'Reutilizar pedido desta tentativa',exact:true}).first().click()
 await expect(page.getByLabel('Pedido para construir ou refinar')).toHaveValue(failed.parametros.instrucoes)
 await expect(page.getByLabel('Pacote para construir')).toHaveValue(failed.parametros.exportacao_id)
 await expect(page.getByLabel('Modelo do runtime')).toHaveValue('gpt-6.1-sol')
 expect(await(await request.get(`/api/ed/empresas/${company}`)).json()).toEqual(before)
 expect(errors).toEqual([])
})

test('seção real gerada e refinada: renderização, links, teclado e movimento reduzido',async({page,request})=>{
 const lead=await(await request.get(`/api/ed/empresas/${company}`)).json()
 const initial=lead.previas.find((p:{construcao_id:string})=>p.construcao_id==='1fd7b214c49740e18a07556ad56b6ae1')
 const refined=lead.previas.find((p:{construcao_id:string})=>p.construcao_id==='71e238ac68d243488853d39ab005d951')
 expect(initial.exportacao_id).toBe('7396294c77f3451a82b5f2361f577f72')
 expect(refined.exportacao_id).toBe('0a2cea32d5164cd5ac35fe15c6bc1df9')
 const failed:string[]=[];page.on('response',r=>{if(r.status()>=400)failed.push(r.url())})
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto(initial.url)
 await expect(page.getByRole('link',{name:/Visitar o site informado/})).toHaveAttribute('href','https://padariaartesanal.com.br/')
 await page.goto(refined.url)
 await expect(page.getByRole('link',{name:/Visitar o site informado/})).toHaveAttribute('href','https://padariaartesanal.com.br/')
 await expect(page.getByRole('link',{name:/Ligar para/})).toHaveAttribute('href','tel:+551182831144')
 await expect(page.getByText(/Fotografia da padaria aguarda autorização/)).toBeVisible()
 await expect(page.locator('.gallery .placeholder')).toHaveCount(3)
 await expect(page.getByRole('img')).toHaveAttribute('alt',/não representa produtos reais/)
 await expect(page.getByText('Publicação pendente de aprovação do titular')).toBeVisible()
 await page.keyboard.press('Tab');await expect(page.getByRole('link',{name:'Pular para o conteúdo'})).toBeFocused()
 await page.keyboard.press('Enter');await expect(page.locator('#conteudo')).toBeFocused()
 await page.getByRole('link',{name:/Planejar minha visita/}).click()
 await expect(page.locator('#informacoes')).toBeInViewport()
 await page.goto(refined.url)
 expect((await new AxeBuilder({page}).analyze()).violations).toEqual([])
 await page.screenshot({path:`${shots}/pao-desktop.png`})
 for(const width of [320,390,768]){
  await page.setViewportSize({width,height:844})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
  expect((await new AxeBuilder({page}).analyze()).violations).toEqual([])
 }
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:`${shots}/pao-mobile.png`,fullPage:true})
 await page.emulateMedia({reducedMotion:'reduce'})
 await expect(page.locator('.button').first()).toHaveCSS('transition-duration','0s')
 expect(errors).toEqual([]);expect(failed).toEqual([])
 fs.writeFileSync('../.cache/kit-regressao-navegador.json',JSON.stringify({desktop:true,mobile:[320,390,768],teclado:true,movimento_reduzido:true,axe_violations:0,erros:errors,recursos_falhos:failed},null,2))
})
