import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

test('bloqueio real mostra regra e permite cadastro/upload manual', async ({ page }) => {
  await page.goto('/empresas/nova')
  await page.getByLabel('Nome público da empresa').fill('Empresa fictícia — bloqueio de teste')
  await page.getByLabel('Site', { exact: true }).fill('https://blocked.example.org')
  await page.getByLabel('Estes são dados de demonstração').check()
  await page.getByRole('button', { name: 'Salvar empresa', exact: true }).click()
  await page.getByRole('button', { name: 'Pesquisa do site', exact: true }).click()
  await page.getByLabel('Confirmo que este site pertence').check()
  await page.getByRole('button', { name: 'Pesquisar informações da empresa', exact: true }).click()
  await expect(page.getByText('Regra de robots.txt', { exact: true })).toBeVisible()
  await expect(page.getByText('Nenhuma página lida.', { exact: false })).toBeVisible()
  await page.getByText('Ver regras e diagnóstico da leitura', { exact: true }).click()
  await expect(page.getByText('Disallow: /', { exact: false }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Revisar site / adicionar informações' }).click()
  await page.getByLabel('Descrição comercial').fill('Informação preenchida manualmente após bloqueio — demonstração')
  await page.getByRole('button', { name: 'Salvar empresa', exact: true }).click()
  await page.getByRole('button', { name: 'Pesquisa do site', exact: true }).click()
  await page.getByRole('button', { name: 'Enviar materiais manualmente' }).click()
  await expect(page.getByRole('button', { name: 'Enviar imagem', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Ficha da empresa', exact: true }).click()
  await expect(page.locator('.ed-facts').getByText('Informação preenchida manualmente após bloqueio — demonstração')).toBeVisible()
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
})

test('pesquisa → revisão sem sobrescrever → direitos → seleção → pacote', async ({ page }) => {
  await page.goto('/empresas/nova')
  await page.getByLabel('Nome público da empresa').fill('Oficina fictícia — teste de pesquisa')
  await page.getByLabel('Contato comercial', { exact: true }).fill('Contato escrito pelo usuário')
  await page.getByLabel('Site', { exact: true }).fill('https://example.org')
  await page.getByLabel('Estes são dados de demonstração').check()
  await page.getByRole('button', { name: 'Salvar empresa', exact: true }).click()
  await page.getByRole('button', { name: 'Pesquisar informações da empresa', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Pesquisar informações da empresa', exact: true })).toBeDisabled()
  await page.getByLabel('Confirmo que este site pertence').check()
  await page.getByRole('button', { name: 'Pesquisar informações da empresa', exact: true }).click()
  await expect(page.getByText('concluida', { exact: true })).toBeVisible()
  await expect(page.getByText('Contato escrito pelo usuário', { exact: true })).toBeVisible()
  await expect(page.getByText('https://www.instagram.com/fixture.ed/', { exact: true })).toBeVisible()
  await page.getByRole('checkbox', { name: 'Preencher este campo após conferir: Descrição', exact: true }).check()
  await expect(page.getByRole('button', { name: 'Confirmar sugestões selecionadas' })).toBeDisabled()
  await page.getByLabel('Conferi a identidade, a filial e os valores escolhidos').check()
  await page.getByRole('button', { name: 'Confirmar sugestões selecionadas' }).click()
  await expect(page.getByText('Sugestões aplicadas.', { exact: false })).toBeVisible()
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
  await page.getByLabel('Titular / atribuição da candidata').fill('Fixture própria — teste')
  await expect(page.getByRole('button', { name: 'Importar para a galeria' })).toBeDisabled()
  await page.getByLabel('Tenho permissão para exportar e usar esta imagem.').check()
  await page.getByRole('button', { name: 'Importar para a galeria' }).click()
  await expect(page.getByText('Importada. Selecione na aba Materiais para exportar.')).toBeVisible()
  await page.getByRole('button', { name: 'Ficha da empresa', exact: true }).click()
  await expect(page.locator('.ed-facts').getByText('Contato escrito pelo usuário', { exact: true })).toBeVisible()
  await expect(page.locator('.ed-facts').getByText('Empresa ficticia para validar enriquecimento.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Materiais', exact: true }).click()
  await page.getByRole('checkbox', { name: 'Incluir no pacote' }).check()
  await page.getByRole('button', { name: 'Documento e exportação', exact: true }).click()
  await page.getByRole('button', { name: 'Exportar para o Codex', exact: true }).click()
  await expect(page.getByText('Versão 1 pronta', { exact: true })).toBeVisible()
  await page.getByText('Ver documento completo e prompt', { exact: true }).click()
  await expect(page.getByLabel('Documento Markdown completo')).toContainText('Coleta automática e revisão')
  const companyUrl=page.url()
  await page.goto('/configuracoes/aparencia')
  await page.getByRole('button', { name: /^Nebulosa/ }).click()
  await page.goto(companyUrl)
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: 'Pesquisa do site', exact: true }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
})
