import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import fs from 'node:fs'
import path from 'node:path'

test('empresa → upload → documento → ZIP → prévia, com fontes e pendências', async ({ page }) => {
  const consoleErrors: string[] = []
  page.on('pageerror', err => consoleErrors.push(err.message))
  await page.goto('/leads')
  await expect(page.getByRole('heading', { name: 'Empresas', exact:true,level:1 })).toBeVisible()
  await page.getByRole('button', { name: 'Carregar demonstração' }).click()
  await expect(page.getByRole('heading', { name: 'Ateliê Aurora — demonstração' })).toBeVisible()
  await page.getByRole('button', { name: 'Editar ficha' }).click()
  await page.getByLabel('Contato comercial', { exact: true }).fill('+55 81 0000-0000')
  await page.getByLabel('Serviços confirmados', { exact: true }).fill('Serviço fictício de demonstração')
  await page.getByLabel('Conferi a identidade').check()
  await page.getByRole('button', { name: 'Salvar empresa', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Editar ficha' })).toBeVisible()
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
  fs.mkdirSync(path.resolve('../.cache/screenshots'), { recursive: true })
  await page.locator('#ed-main').focus()
  await page.evaluate(() => window.scrollTo(0, 0))
  await expect.poll(() => page.evaluate(() => window.scrollY)).toBe(0)
  await page.screenshot({ path: '../.cache/screenshots/ficha-desktop.png' })
  await page.getByRole('button', { name: 'Materiais', exact: true }).click()
  await page.getByLabel('Arquivo', { exact: true }).setInputFiles({ name: 'placeholder-demo.png', mimeType: 'image/png',
    buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=', 'base64') })
  await page.getByLabel('Origem', { exact: true }).fill('Fixture de teste, imagem fictícia')
  await page.getByLabel('Atribuição / titular', { exact: true }).fill('Ed CRM — demonstração')
  await page.getByLabel('Confirmo que posso exportar e usar esta imagem').check()
  await page.getByRole('button', { name: 'Enviar imagem', exact: true }).click()
  await expect(page.getByRole('checkbox', { name: 'Incluir no pacote' })).toBeVisible()
  await page.getByRole('checkbox', { name: 'Incluir no pacote' }).check()
  await expect(page.getByRole('checkbox', { name: 'Incluir no pacote' })).toBeChecked()
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
  await page.getByRole('button', { name: 'Documento e exportação', exact: true }).click()
  await page.getByLabel('Objetivo da landing page', { exact: true }).fill('Apresentar uma empresa fictícia para validar o fluxo.')
  await page.getByRole('button', { name: 'Exportar para o Codex', exact: true }).click()
  await expect(page.getByText('Versão 1 pronta', { exact: true })).toBeVisible()
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  await page.locator('#ed-main').focus()
  await page.keyboard.press('Control+Home')
  await page.screenshot({ path: '../.cache/screenshots/documento-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1440, height: 900 })
  const downloadEvent = page.waitForEvent('download')
  await page.getByRole('link', { name: 'Baixar ZIP', exact: true }).click()
  const download = await downloadEvent
  expect(await download.failure()).toBeNull()
  await download.saveAs(path.resolve('../.cache/browser-results/pacote-browser.zip'))
  await page.getByRole('button', { name: 'Prévia e versões', exact: true }).click()
  await page.getByLabel('Link da prévia', { exact: true }).fill('https://example.com/previa-demonstracao')
  await page.getByRole('button', { name: 'Registrar prévia', exact: true }).click()
  await expect(page.getByText('Prévia registrada.', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Etapa do fluxo')).toHaveValue('previa_pronta')
  await page.getByRole('link', { name: 'Todas as empresas', exact: true }).click()
  await page.getByRole('textbox', { name: 'Buscar empresas', exact: true }).fill('Aurora')
  await page.keyboard.press('Tab')
  await expect(page.getByRole('combobox', { name: 'Filtrar etapa', exact: true })).toBeFocused()
  await expect(page.getByRole('table')).toContainText('Ateliê Aurora — demonstração')
  await expect(page.getByRole('table')).toContainText('Demonstração')
  const a11y = await new AxeBuilder({ page }).analyze()
  expect(a11y.violations).toEqual([])
  expect(consoleErrors).toEqual([])
  fs.mkdirSync(path.resolve('../.cache/screenshots'), { recursive: true })
  await page.screenshot({ path: '../.cache/screenshots/desktop.png', fullPage: true })
  for (const width of [320, 390, 768, 1024]) {
    await page.setViewportSize({ width, height: 844 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
    await expect(page.getByRole('link', { name: 'Cadastro manual', exact: true })).toBeVisible()
  }
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: '../.cache/screenshots/mobile.png', fullPage: true })
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
  await page.getByRole('textbox', { name: 'Buscar empresas', exact: true }).fill('Nada aqui')
  await expect(page.getByRole('heading', { name: 'Nenhum registro com esses filtros' })).toBeVisible()
})

test('fonte pendente, configuração e estados sem simular resultados', async ({ page }) => {
  await page.goto('/nova-busca')
  await expect(page.getByRole('button', { name: 'Pesquisar empresas' })).toBeDisabled()
  await page.getByRole('link', { name: 'Configurar OpenStreetMap' }).click()
  await page.getByRole('button', { name: 'Ativar OpenStreetMap' }).click()
  await expect(page.getByRole('button', { name: 'Desativar fonte' })).toBeVisible()
  await page.goto('/nova-busca')
  await page.getByLabel('Cidade', { exact: true }).fill('Recife')
  await page.getByLabel('Quantidade máxima').fill('1')
  await page.getByRole('button', { name: 'Pesquisar empresas' }).click()
  await expect(page.getByText('Na fila', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Cancelar busca' }).click()
  await expect(page.getByText('Cancelada', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Retomar', exact: true })).toBeVisible()
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
})
