import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

test('preparação manual e dois escopos preservados, sem IA, com ZIP e mobile', async ({ page, request }) => {
  const created = await request.post('/api/ed/empresas', { data: { nome: 'Padaria fictícia · teste de preparação', demonstracao: true, confirmado: true, descricao: 'Padaria de teste.', telefone: 'Contato de teste', nicho: 'Padarias' } })
  const lead = await created.json()
  await page.goto(`/empresas/${lead.id}`)
  await page.getByRole('button', { name: 'Preparar prévia', exact: true }).click()
  await page.getByLabel('Objetivo', { exact: true }).fill('Apresentar informações revisadas')
  await page.getByLabel('Público', { exact: true }).fill('Clientes da região')
  await page.getByLabel('Oferta confirmada / a validar').fill('Serviços confirmados; sem preços')
  await page.getByLabel('Chamada principal (CTA)').fill('Entrar em contato')
  await page.getByLabel('URL de referência').fill('https://cr-fitness-academia.pages.dev/')
  await page.getByLabel('O que aproveitar da referência').fill('Composição fotográfica; identidade própria da padaria')
  await page.getByRole('button', { name: 'Adicionar referência', exact: true }).click()
  await page.getByLabel('Texto · abertura', { exact: true }).fill('Texto manual preservado')
  await page.getByRole('button', { name: 'Salvar preparação', exact: true }).first().click()
  await expect(page.getByText('Preparação salva. O próximo ZIP usará esta revisão.')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Gerar proposta de texto com OpenAI' })).toBeDisabled()
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
  await page.reload()
  await page.getByRole('button', { name: 'Preparar prévia', exact: true }).click()
  await expect(page.getByLabel('Texto · abertura', { exact: true })).toHaveValue('Texto manual preservado')
  await page.getByLabel('Tipo de entrega').selectOption('completo')
  await page.getByLabel('Banco de dados e entidades').fill('Catálogo administrável; definir entidades e permissões')
  await page.getByRole('button', { name: 'Salvar preparação', exact: true }).first().click()
  await expect(page.getByText('Preparação salva. O próximo ZIP usará esta revisão.')).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
  await page.screenshot({ path: '../.cache/screenshots/preparacao-mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'Documento e exportação', exact: true }).click()
  await page.getByRole('button', { name: 'Exportar para o Codex', exact: true }).click()
  await expect(page.getByText('Versão 1 pronta', { exact: true })).toBeVisible()
  await page.goto('/integracoes')
  await expect(page.locator('details.ed-connection-disclosure > summary').filter({hasText:'Firecrawl'})).toBeVisible()
  for (const name of ['Firecrawl','Apify · Instagram público','21st.dev MCP','OpenAI · Imagens']) {
    const summary=page.locator('details.ed-connection-disclosure > summary').filter({hasText:name});await expect(summary).toContainText('Sem credencial')
  }
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
})
