import {test,expect} from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import fs from 'node:fs'

test('quatro layouts, refinamento isolado, bloqueio, importação inválida e versão persistida',async({page,request})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 const lead=await(await request.post('/api/ed/empresas',{data:{nome:'Padaria fictícia · estúdio',nicho:'Padarias',demonstracao:true,confirmado:true,descricao:'Texto revisado para teste',telefone:'1182831144'}})).json()
 const root=`/api/ed/empresas/${lead.id}/composicao`
 await page.goto(`/empresas/${lead.id}`)
 await page.getByRole('button',{name:'Montar composição',exact:true}).click()
 await expect(page.locator('.ed-alternative')).toHaveCount(4)
 expect(await page.locator('.ed-alternative .lp-section').evaluateAll(els=>els.map(e=>e.getAttribute('data-layout')))).toEqual(['editorial','imersiva','mosaico','compacta'])
 await page.getByRole('button',{name:'Escolher B',exact:true}).click()
 await page.getByLabel('Título da alternativa').fill('Título manual da abertura')
 await page.getByRole('button',{name:'Salvar composição e versão'}).click()
 await expect(page.getByText('COMPOSIÇÃO · VERSÃO 1')).toBeVisible()
 const first=await(await request.get(root)).json()
 await page.getByLabel('Seção em edição').selectOption('servicos')
 await expect(page.locator('.ed-alternative')).toHaveCount(4)
 await page.getByRole('button',{name:'Escolher C',exact:true}).click()
 await page.getByLabel('Texto proposto da alternativa').fill('Serviço apenas fictício neste teste isolado')
 await page.getByRole('button',{name:'Salvar composição e versão'}).click()
 await expect(page.getByText('COMPOSIÇÃO · VERSÃO 2')).toBeVisible()
 const second=await(await request.get(root)).json();expect(second.secoes[0]).toEqual(first.secoes[0])
 await page.getByLabel('Seção em edição').selectOption('servicos')
 await page.getByText('Importar quatro alternativas externas do Codex',{exact:true}).click()
 await page.getByLabel('JSON das quatro alternativas').fill('[{},{},{},{}]')
 await page.getByRole('button',{name:'Importar alternativas para revisão'}).click()
 await expect(page.getByRole('alert')).toContainText('quatro alternativas')
 await expect(page.locator('.ed-alternative')).toHaveCount(4)
 await page.getByRole('button',{name:'Fechar aviso'}).click()
 await page.getByRole('button',{name:'Fixar escolha',exact:true}).click()
 await expect(page.getByLabel('Título da alternativa')).toBeDisabled()
 await page.getByRole('button',{name:'Salvar composição e versão'}).click()
 await expect(page.getByText('COMPOSIÇÃO · VERSÃO 3')).toBeVisible()
 await page.reload();await page.getByRole('button',{name:'Montar composição',exact:true}).click()
 await expect(page.getByLabel('Título da alternativa')).toHaveValue('Título manual da abertura')
 await page.getByRole('button',{name:'Ver composição completa'}).click()
 await expect(page.locator('.ed-composition-canvas .lp-section')).toHaveCount(4)
 expect((await new AxeBuilder({page}).analyze()).violations).toEqual([])
 await page.emulateMedia({reducedMotion:'reduce'})
 await expect(page.locator('.lp-section h2').first()).toHaveCSS('animation-name','none')
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Desktop',exact:true}).click()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
 expect((await new AxeBuilder({page}).analyze()).violations).toEqual([])
 expect(errors).toEqual([])
})

test('imagem original e versão local, ausência de IA e Instagram, teclado em aparência',async({page,request})=>{
 const lead=await(await request.post('/api/ed/empresas',{data:{nome:'Empresa fictícia · imagens',demonstracao:true}})).json()
 const image=await(await request.post(`/api/ed/empresas/${lead.id}/materiais`,{multipart:{arquivo:{name:'ilustracao.png',mimeType:'image/png',buffer:fs.readFileSync('../examples/evolucao-pao/ilustracao-demonstracao-edy.png')},origem:'Desenho de teste',atribuicao:'EDY',autorizado:'true',natureza:'ilustracao'}})).json()
 const root=`/api/ed/empresas/${lead.id}/materiais/${image.id}/studio`
 const version=await(await request.post(root+'/editar',{data:{acao:'local',recorte:[0,0,.7,1],natureza:'ilustracao',destino:'mobile'}})).json()
 await page.goto(`/empresas/${lead.id}`);await page.getByRole('button',{name:'Estúdio de imagens',exact:true}).click()
 await expect(page.getByText(/1600 × 1200/)).toBeVisible()
 await expect(page.getByText(/1120 × 1200/)).toBeVisible()
 await page.getByRole('button',{name:'Aprovar e usar versão',exact:true}).click()
 await expect.poll(async()=> (await(await request.get(root)).json()).versao_exportacao).toBe(version.id)
 await page.getByRole('button',{name:/Editar com IA/}).click()
 await expect(page.getByRole('alert')).toContainText('Sem credencial')
 await page.getByRole('button',{name:'Instagram',exact:true}).click()
 await page.getByRole('button',{name:'Pesquisar Instagram',exact:true}).click()
 await expect(page.getByRole('alert')).toContainText('Sem credencial')
 await page.goto('/configuracoes/aparencia')
 await page.getByRole('button',{name:/^Claro/}).press('Enter')
 await expect(page.locator('html')).toHaveAttribute('data-theme','claro')
 await expect(page.getByRole('button',{name:/^Claro/})).toBeFocused()
})
