import {test,expect} from '@playwright/test'
test('captura com dispositivo sintético de QA; ausência de credencial não simula transcrição',async({page,context})=>{
 await context.grantPermissions(['microphone'],{origin:'http://127.0.0.1:5129'})
 await page.goto('/assistente');await page.getByText('Preferências de voz',{exact:true}).click()
 await page.getByLabel('Transcrição',{exact:true}).selectOption('openai')
 await page.getByRole('button',{name:'Gravar comando'}).click()
 await expect(page.getByRole('button',{name:/Parar · 1s/})).toBeVisible()
 await page.getByRole('button',{name:/Parar ·/}).click()
 await page.getByText('Rever ou descartar áudio',{exact:true}).click()
 await expect(page.locator('audio')).toHaveCount(1)
 await expect(page.getByRole('alert')).toContainText('ED_CRM_VOICE_KEY')
 await expect(page.getByLabel('Seu comando')).toHaveValue('')
 await expect(page.locator('audio')).toHaveCount(1)
 await page.getByRole('button',{name:'Descartar captura'}).click();await expect(page.locator('audio')).toHaveCount(0)
})
test('rascunho revisado pela UI integra o pacote sem envio e sem perder edição',async({page,request})=>{
 const lead=await(await request.post('/api/ed/empresas',{data:{nome:'Empresa fictícia · prospecção QA',demonstracao:true}})).json()
 await page.goto('/empresas/'+lead.id);await page.getByRole('button',{name:'Documento e exportação'}).click()
 await page.getByLabel('Texto para WhatsApp',{exact:true}).fill('Proposta revisada de teste, sem prometer resultado ou contato anterior.')
 await page.getByRole('button',{name:'Salvar textos de prospecção'}).click();await expect(page.getByRole('status')).toContainText('Textos revisados salvos')
 await page.reload();await page.getByRole('button',{name:'Documento e exportação'}).click()
 await expect(page.getByLabel('Texto para WhatsApp',{exact:true})).toHaveValue('Proposta revisada de teste, sem prometer resultado ou contato anterior.')
 const draft=await(await request.get('/api/ed/empresas/'+lead.id+'/prospeccao')).json();expect(draft.enviado).toBe(false)
})

test('envio com falha preserva texto na conversa recém-criada e permite recuperar',async({page})=>{
 await page.goto('/assistente')
 await page.getByLabel('Seu comando',{exact:true}).fill('Mostre os leads sem site')
 await page.route('**/assistente/conversas/*/mensagens',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({erro:'QA: conexão interrompida'})}))
 await page.getByRole('button',{name:'Executar comando',exact:true}).click()
 await expect(page.getByRole('alert')).toContainText('conexão interrompida')
 await expect(page.getByLabel('Seu comando',{exact:true})).toHaveValue('Mostre os leads sem site')
 await page.unroute('**/assistente/conversas/*/mensagens')
 await page.getByRole('button',{name:'Executar comando',exact:true}).click()
 await expect(page.getByLabel('Seu comando',{exact:true})).toHaveValue('')
 await expect(page.getByText('Comando reconhecido e colocado na fila.',{exact:false})).toBeVisible()
})

test('permissão negada não inicia transcrição e preserva rascunho',async({page})=>{
 // Falha de dispositivo simulada para contrato de UI; não prova microfone humano.
 await page.addInitScript(()=>Object.defineProperty(navigator.mediaDevices,'getUserMedia',{value:()=>Promise.reject(new DOMException('QA: microfone recusado','NotAllowedError'))}))
 await page.goto('/assistente');await page.getByLabel('Seu comando',{exact:true}).fill('Rascunho manual preservado')
 await page.getByRole('button',{name:'Gravar comando',exact:true}).click()
 await expect(page.getByRole('alert')).toContainText('Microfone bloqueado pelo navegador')
 await expect(page.getByLabel('Seu comando',{exact:true})).toHaveValue('Rascunho manual preservado')
 await expect(page.getByRole('button',{name:'Executar comando',exact:true})).toBeEnabled()
})

test('orientação só se torna contexto após escolha explícita de escopo',async({page,request})=>{
 const lead=await(await request.post('/api/ed/empresas',{data:{nome:'QA instruções',nicho:'Academias',demonstracao:true}})).json()
 await page.goto('/assistente?empresa='+lead.id)
 await page.getByLabel('Seu comando',{exact:true}).fill('Preserve um hero amplo e não invente modalidades.')
 await page.locator('summary').filter({hasText:'opções e referências'}).click()
 await page.getByText('Salvar comando como orientação reutilizável',{exact:true}).click()
 await page.getByLabel('Aplicar orientação',{exact:true}).selectOption('lead')
 await page.getByRole('button',{name:'Salvar orientação revisada',exact:true}).click()
 await expect(page.getByText('Orientação versionada na Biblioteca.',{exact:false})).toBeVisible()
 const context=await(await request.get('/api/ed/empresas/'+lead.id+'/contexto')).json()
 expect(context.texto).toContain('Preserve um hero amplo')
 await expect(page.getByLabel('Seu comando',{exact:true})).toHaveValue('Preserve um hero amplo e não invente modalidades.')
})

test('lote no celular conserva projeto e controles em vez de ocultar colunas',async({page,request})=>{
 const lead=await(await request.post('/api/ed/empresas',{data:{nome:'QA lote celular',cidade:'Recife',confirmado:true,demonstracao:true}})).json()
 const response=await request.post('/api/ed/lotes',{data:{empresa_ids:[lead.id],chave:'qa-lote-celular',geracao:'templates'}})
 expect(response.status(),await response.text()).toBe(202)
 await page.setViewportSize({width:390,height:844});await page.goto('/assistente')
 await page.getByRole('button',{name:/^Execuções/}).click()
 const batch=page.getByRole('region',{name:'Prévia em lote',exact:true})
 await expect(batch.getByRole('cell',{name:/^Aguardando construção/})).toBeVisible()
 await expect(batch.getByRole('button',{name:'cancelar',exact:true})).toBeVisible()
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)
 expect(overflow).toBe(false)
})
