import {useState,type ReactNode} from 'react'
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query'
import {httpClient} from '@/services/httpClient'
import {accessState} from './accessState'
import {Field,Erro,Loading} from './shared'
import {ActorContext,useAccess,type Access} from './accessContext'
export function AccessGate({children}:{children:ReactNode}){
 const q=useQuery({queryKey:['ed','sessao'],queryFn:async()=>{const d=await httpClient.get<Access>('/api/ed/acesso/sessao');accessState.csrf=d.csrf||'';return d},retry:false})
 if(q.isPending)return <main className="ed-panel"><Loading/></main>
 if(q.isError)return <main className="ed-panel"><Erro error={q.error}/><button className="ed-button" onClick={()=>q.refetch()}>Tentar conexão local</button></main>
 if(q.data.login_necessario)return <Login/>
 return <ActorContext value={q.data}>{children}</ActorContext>
}
function Login(){
 const client=useQueryClient(),[name,setName]=useState(''),[password,setPassword]=useState('')
 const login=useMutation({mutationFn:()=>httpClient.post('/api/ed/acesso/login',{nome:name,senha:password}),onSuccess:()=>{setPassword('');client.clear();location.reload()}})
 return <main className="ed-login"><section className="ed-panel ed-form"><span className="ed-eyebrow">WORKSPACE LOCAL</span><h1>Entre no EDY CRM</h1><p>Seu acesso e papel são conferidos pelo backend.</p><form onSubmit={e=>{e.preventDefault();login.mutate()}}><Field label="Usuário"><input required maxLength={80} autoComplete="username" value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Senha"><input required type="password" maxLength={200} autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></Field><button className="ed-button primary" disabled={login.isPending}>Entrar</button></form>{login.isError&&<Erro error={login.error}/>}</section></main>
}
export function AccessPanel(){
 const d=useAccess(),client=useQueryClient(),[name,setName]=useState(''),[password,setPassword]=useState(''),[role,setRole]=useState('operador'),[workspace,setWorkspace]=useState('')
 const q=useQuery({queryKey:['ed','usuarios'],queryFn:()=>httpClient.get<{id:string;nome:string;papel:string}[]>('/api/ed/acesso/usuarios'),enabled:d?.ator?.papel==='administrador'})
 const change=useMutation({mutationFn:({id,...body}:{id:string;papel?:string;revogar?:boolean})=>httpClient.put('/api/ed/acesso/usuarios/'+id,body),onSuccess:()=>{client.invalidateQueries({queryKey:['ed','usuarios']});client.invalidateQueries({queryKey:['ed','sessao']})}})
 const action=useMutation({mutationFn:(kind:string)=>kind==='setup'?httpClient.post('/api/ed/acesso/setup',{nome:name,senha:password}):kind==='usuario'?httpClient.post('/api/ed/acesso/usuarios',{nome:name,senha:password,papel:role}):kind==='workspace'?httpClient.post('/api/ed/acesso/workspaces',{nome:workspace}):kind==='sair'?httpClient.post('/api/ed/acesso/sair'):httpClient.post('/api/ed/acesso/workspace',{id:kind}),onSuccess:(_,kind)=>{setPassword('');if(kind==='setup'||kind==='sair'||!['usuario','workspace'].includes(kind)){client.clear();location.reload()}else{client.invalidateQueries({queryKey:['ed','usuarios']});client.invalidateQueries({queryKey:['ed','sessao']})}}})
 return <section className="ed-panel ed-form"><h2>Usuários e workspaces</h2><p>{d?.ator?.nome} · {d?.ator?.papel}. {d?.ator?.modo==='local'?'Modo pessoal local. Ative usuários para exigir login; seus dados atuais permanecem no workspace principal.':'Acesso por sessão; bancos e arquivos separados por workspace.'}</p>
 {d?.ator?.modo==='sessao'&&<><Field label="Workspace selecionado"><select value={d.ator.workspace} disabled={action.isPending} onChange={e=>action.mutate(e.target.value)}>{d.workspaces.map(w=><option key={w.id} value={w.id}>{w.nome} · {w.papel}</option>)}</select></Field><button className="ed-button" onClick={()=>action.mutate('sair')}>Sair do CRM</button></>}
 {d?.ator?.papel==='administrador'&&<><details><summary>{d.ator.modo==='local'?'Ativar acesso por usuários':'Criar usuário neste workspace'}</summary><form onSubmit={e=>{e.preventDefault();action.mutate(d.ator!.modo==='local'?'setup':'usuario')}}><Field label="Nome do usuário"><input required value={name} maxLength={80} autoComplete="off" onChange={e=>setName(e.target.value)}/></Field><Field label="Nova senha do usuário" hint="Mínimo 12 caracteres. Não entra em histórico, ZIP ou respostas."><input type="password" required minLength={12} maxLength={200} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></Field>{d.ator.modo==='sessao'&&<Field label="Papel"><select value={role} onChange={e=>setRole(e.target.value)}>{['administrador','operador','leitura'].map(r=><option key={r}>{r}</option>)}</select></Field>}<button className="ed-button primary" disabled={action.isPending}>{d.ator.modo==='local'?'Ativar login no CRM':'Criar usuário'}</button></form></details>
 {d.ator.modo==='sessao'&&<details><summary>Criar workspace isolado</summary><Field label="Nome do novo workspace"><input maxLength={100} value={workspace} onChange={e=>setWorkspace(e.target.value)}/></Field><button className="ed-button" disabled={!workspace||action.isPending} onClick={()=>action.mutate('workspace')}>Criar workspace</button></details>}
 <ul>{q.data?.map(u=><li key={u.id}>{u.nome} · {d.ator?.modo==='sessao'?<><select aria-label={'Papel de '+u.nome} value={u.papel} disabled={change.isPending} onChange={e=>change.mutate({id:u.id,papel:e.target.value})}>{['administrador','operador','leitura'].map(r=><option key={r}>{r}</option>)}</select><button className="ed-button" disabled={change.isPending} onClick={()=>change.mutate({id:u.id,revogar:true})}>Revogar acesso ao workspace</button></>:u.papel}</li>)}</ul></>}{change.isError&&<Erro error={change.error}/>} {action.isError&&<Erro error={action.error}/>}{q.isError&&<Erro error={q.error}/>}{action.isSuccess&&<p role="status">Alteração salva no backend.</p>}</section>
}
