import { useRef, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { httpClient } from '@/services/httpClient'
import { useAccess } from './accessContext'
import { libraryApi, type Knowledge } from './libraryApi'
import { Badge, Erro, Field, Loading } from './shared'

const labels: Record<string,string> = { oportunidade:'Oportunidade · hipótese', jornada:'Jornada específica', objetivo:'Objetivo', publico:'Público · hipótese a revisar', oferta:'Oferta', cta:'Chamada principal', arquitetura:'Arquitetura das seções', copy:'Texto proposto por seção', direcao:'Contrato visual · propostas e decisões', interacoes:'Interações e estados', prospeccao:'Prospecção · rascunho sem envio' }
interface Source {valor:string;url:string;fornecedor:string;verificacao:string;consultado_em:string}
interface Dossier {empresa_id:string;projeto_id:string;nome:string;versao:number;estado:string;metodo:string;proposta:Record<string,string>;fatos:Record<string,Source>;candidatos:Record<string,Source>;pendencias:string[];edicoes_preservadas:string[];campos_editados:string[];skill:{sha256:string};correcoes_aplicaveis:Knowledge[];revisao:{documental:string;visual:string;observacoes:string;construcao_id?:string;checklist?:Record<string,boolean>}}
interface Construction {id:string;estado:string;criado_em:string}
interface Analysis {resultados:Dossier[];erros:{empresa_id:string;mensagem:string}[]}
interface NativeBrief {id:string;estado:string;progresso:number;mensagem:string;parametros:{projeto_id:string};resultado?:{proposta:Record<string,string>;observacoes_candidatas:string[];versao_base:number;modelo:string;modo:string;skill:{descoberta_no_runtime:boolean}}}
const root=(company:string)=>'/api/ed/empresas/'+company+'/adaptativo'

export function AdaptiveSelection({selected}:{selected:string[]}) {
  const key=useRef(''), client=useQueryClient(), readonly=useAccess()?.ator?.papel==='leitura'
  const analyze=useMutation({mutationFn:()=>{
    if(!key.current)key.current=crypto.randomUUID()
    return httpClient.post<Analysis>('/api/ed/adaptativo/analisar',{empresa_ids:selected,chave:key.current})
  },onSuccess:()=>{key.current='';client.invalidateQueries({queryKey:['ed','adaptativo']})}})
  if(!selected.length)return null
  return <section className="ed-panel ed-form" aria-label="Análise das selecionadas"><h2>Analisar e preparar briefs</h2><p>Somente as {selected.length} empresas selecionadas. Usa dados revisados e preparação existente, sem consumir IA. Não cria leads, publica ou envia mensagens.</p><button className="ed-button" disabled={readonly||analyze.isPending||selected.length>25} onClick={()=>analyze.mutate()}>{analyze.isPending?'Analisando dados e preparando briefs…':'Preparar briefs das selecionadas'}</button>{analyze.isError&&<Erro error={analyze.error}/>} {analyze.data&&<div role="status">{analyze.data.resultados.map(d=><p key={d.empresa_id}><Link to={'/empresas/'+d.empresa_id+'?aba=preparacao'}>{d.nome} · abrir brief v{d.versao} ↗</Link><small>{d.pendencias.length} pendências · {d.edicoes_preservadas.length} campos manuais preservados</small></p>)}{analyze.data.erros.map(e=><p key={e.empresa_id} className="ed-alert error">{e.mensagem}</p>)}</div>}</section>
}

export function AdaptivePanel({company}:{company:string}) {
  const [project,setProject]=useState(''), [unsaved,setUnsaved]=useState(false)
  const draftBase=useRef<Dossier|null>(null)
  const builds=useQuery({queryKey:['ed','construcoes',company],queryFn:()=>httpClient.get<Construction[]>('/api/ed/empresas/'+company+'/construcoes')})
  const q=useQuery({queryKey:['ed','adaptativo',company,project],queryFn:()=>httpClient.get<Dossier>(root(company)+(project?'?projeto_id='+encodeURIComponent(project):''))})
  // Uma atualização em outra janela não desmonta um rascunho ainda não salvo.
  if(q.data&&!unsaved)draftBase.current=q.data
  const shown=unsaved&&draftBase.current?draftBase.current:q.data
  return <section className="ed-panel ed-form ed-adaptive" aria-label="CRM Sites Adaptativo"><div className="ed-panel-head"><div><h2>CRM Sites Adaptativo</h2><p>Análise → brief específico → instruções → revisão → correções. Fatos, copy e design ficam separados.</p></div><Badge>Sem publicação automática</Badge></div><Field label="Escopo do brief e das correções" hint={unsaved?'Salve as edições antes de trocar de escopo.':undefined}><select disabled={unsaved} value={project} onChange={e=>setProject(e.target.value)}><option value="">Esta empresa · próximos projetos</option>{builds.data?.filter(b=>b.estado==='concluida').map(b=><option key={b.id} value={b.id}>Projeto {b.id.slice(0,8)} · {b.criado_em}</option>)}</select></Field>{builds.isError&&<Erro error={builds.error}/>} {unsaved&&q.data&&shown&&q.data.versao!==shown.versao&&<p className="ed-alert">Existe uma versão nova em outra janela. Seu rascunho está preservado; copie e compare antes de descartá-lo.</p>}{q.isPending?<Loading/>:q.isError?<Erro error={q.error}/>:shown&&<AdaptiveEditor key={company+'-'+project+'-'+shown.versao} value={shown} project={project} builds={builds.data||[]} onDirty={setUnsaved}/>}</section>
}

function AdaptiveEditor({value:d,project,builds,onDirty}:{value:Dossier;project:string;builds:Construction[];onDirty:(dirty:boolean)=>void}) {
  const [proposal,setProposal]=useState(d.proposta), [dirty,setDirty]=useState(false), [title,setTitle]=useState('Correção revisada'), [correction,setCorrection]=useState(''), [source,setSource]=useState('usuario_explicito'), [observations,setObservations]=useState(d.revisao.observacoes), [construction,setConstruction]=useState(project||d.revisao.construcao_id||''), [checks,setChecks]=useState<Record<string,boolean>>(d.revisao.checklist||{})
  const readonly=useAccess()?.ator?.papel==='leitura', client=useQueryClient(), key=useRef(''), nativeKey=useRef(''), buildKey=useRef(''), navigate=useNavigate()
  const [buildInstructions,setBuildInstructions]=useState('')
  const build=useMutation({mutationFn:()=>{
    if(!buildKey.current)buildKey.current=crypto.randomUUID()
    return httpClient.post<{chat_id:string;execucao_id:string}>(root(d.empresa_id)+'/construir',{versao:d.versao,projeto_id:project,chave:buildKey.current,instrucoes:buildInstructions})
  },onSuccess:r=>{buildKey.current='';invalidate();navigate('/assistente?chat='+r.chat_id)}})
  const invalidate=()=>client.invalidateQueries({queryKey:['ed']})
  const save=useMutation({mutationFn:()=>httpClient.put<Dossier>(root(d.empresa_id),{versao:d.versao,projeto_id:project,proposta:proposal}),onSuccess:()=>{setDirty(false);onDirty(false);invalidate()}})
  const analyze=useMutation({mutationFn:()=>{if(!key.current)key.current=crypto.randomUUID();return httpClient.post<Analysis>('/api/ed/adaptativo/analisar',{empresa_ids:[d.empresa_id],chave:key.current})},onSuccess:()=>{key.current='';invalidate()}})
  const review=useMutation({mutationFn:()=>httpClient.post<Dossier>(root(d.empresa_id)+'/revisar',{versao:d.versao,projeto_id:project,observacoes:observations,construcao_id:construction,checklist:checks}),onSuccess:invalidate})
  const correctionQuery=useQuery({queryKey:['ed','adaptativo-correcoes',d.empresa_id],queryFn:()=>httpClient.get<Knowledge[]>(root(d.empresa_id)+'/correcoes')})
  const correct=useMutation({mutationFn:()=>httpClient.post(root(d.empresa_id)+'/correcoes',{titulo:title,conteudo:correction,escopo:project?'projeto':'lead',projeto_id:project,origem_feedback:source}),onSuccess:()=>{setCorrection('');invalidate()}})
  const approve=useMutation({mutationFn:(x:Knowledge)=>httpClient.post(root(d.empresa_id)+'/correcoes/'+x.id+'/aprovar',{versao:x.versao}),onSuccess:invalidate})
  const disable=useMutation({mutationFn:(x:Knowledge)=>libraryApi.save({...x,estado:'inativo'}),onSuccess:invalidate})
  const exportPackage=useMutation({mutationFn:()=>httpClient.post<{zip_url:string}>('/api/ed/empresas/'+d.empresa_id+'/exportacoes',{projeto_id:project}),onSuccess:()=>client.invalidateQueries({queryKey:['ed','empresa',d.empresa_id]})})
  const jobs=useQuery({queryKey:['ed','adaptativo-codex',d.empresa_id],queryFn:()=>httpClient.get<NativeBrief[]>(root(d.empresa_id)+'/codex'),refetchInterval:q=>q.state.data?.some(j=>['na_fila','pesquisando'].includes(j.estado))?1500:false})
  const native=useMutation({mutationFn:()=>{if(!nativeKey.current)nativeKey.current=crypto.randomUUID();return httpClient.post(root(d.empresa_id)+'/codex',{versao:d.versao,projeto_id:project,chave:nativeKey.current})},onSuccess:()=>{nativeKey.current='';client.invalidateQueries({queryKey:['ed','adaptativo-codex',d.empresa_id]})}})
  const apply=useMutation({mutationFn:(j:NativeBrief)=>httpClient.post(root(d.empresa_id)+'/codex/'+j.id+'/aplicar',{versao:d.versao}),onSuccess:invalidate})
  const cancel=useMutation({mutationFn:(j:NativeBrief)=>httpClient.post('/api/ed/operacoes/'+j.id+'/cancelar',{}),onSuccess:()=>client.invalidateQueries({queryKey:['ed','adaptativo-codex',d.empresa_id]})})
  const nativeBusy=jobs.data?.some(j=>['na_fila','pesquisando'].includes(j.estado))
  const busy=save.isPending||analyze.isPending||review.isPending
  const facts=(sources:Record<string,Source>)=>Object.entries(sources).map(([k,s])=><div key={k}><strong>{k}</strong><p>{s.valor}</p><small>{s.fornecedor} · {s.consultado_em}{s.url&&<> · <a href={s.url} target="_blank" rel="noreferrer">Fonte ↗</a></>}</small></div>)
  return <>
    <p role="status">{d.versao?'Brief v'+d.versao:'Brief ainda não salvo'} · {d.estado.replaceAll('_',' ')} · {d.metodo==='codex_nativo_revisavel'?'proposta Codex revisável':'templates revisáveis, sem IA'}</p>
    {!!d.edicoes_preservadas.length&&<p>{d.edicoes_preservadas.length} campos manuais preservados na nova análise.</p>}
    <div className="ed-actions">{!project&&<button className="ed-button" disabled={readonly||busy||dirty} onClick={()=>analyze.mutate()}>{analyze.isPending?'Atualizando análise…':d.versao?'Atualizar dados sem apagar edições':'Analisar esta empresa'}</button>}<button className="ed-button primary" disabled={readonly||busy||!dirty} onClick={()=>save.mutate()}>{save.isPending?'Salvando…':'Salvar brief editado'}</button><Link className="ed-button" to={'/assistente?empresa='+d.empresa_id}>Continuar no comando</Link></div>
    {dirty&&<p className="ed-alert">Edições não salvas. Salve antes de atualizar, revisar ou exportar. <button className="ed-text-button" onClick={()=>{setProposal(d.proposta);setDirty(false);onDirty(false)}}>Descartar este rascunho não salvo</button></p>}
    <div className="ed-flow-card"><h3>Criar a partir do brief v{d.versao}</h3><p>Codex nativo · GPT-6.1 Sol · Alto · Padrão. A versão revisada, suas edições e o pacote ficam vinculados à conversa. Geração, validação e abertura usam a fila existente; depois refine na mesma conversa.</p><button className="ed-button primary" disabled={readonly||busy||dirty||!d.versao||!['conforme','com_pendencias'].includes(d.revisao.documental)} onClick={()=>navigate('/empresas/'+d.empresa_id+'?aba=visual'+(project?'&projeto='+project:''))}>Criar site · escolher composição</button><details><summary>Construção direta histórica · diagnóstico avançado</summary><Field label="Pedido específico desta prévia"><textarea rows={3} maxLength={4000} value={buildInstructions} disabled={build.isPending} onChange={e=>{setBuildInstructions(e.target.value);buildKey.current=''}}/></Field><button className="ed-button" disabled={readonly||busy||dirty||build.isPending||!d.versao||!['conforme','com_pendencias'].includes(d.revisao.documental)} onClick={()=>build.mutate()}>{build.isPending?'Vinculando brief e iniciando…':'Iniciar construção histórica'}</button></details>{!['conforme','com_pendencias'].includes(d.revisao.documental)&&<p className="ed-alert">Registre a revisão documental abaixo para habilitar a construção. Pendências identificadas podem permanecer.</p>}{build.isError&&<Erro error={build.error}/>}</div>
    <details><summary>Personalizar o brief com Codex · conta nativa</summary><p>GPT-6.1 Sol · Alto · Padrão. Usa a conexão nativa existente e as referências selecionadas. Compare as sugestões antes de aplicar; campos editados por você são preservados. Templates continuam disponíveis sem IA.</p><button className="ed-button" disabled={readonly||busy||dirty||native.isPending||nativeBusy} onClick={()=>native.mutate()}>Pedir proposta personalizada ao Codex</button>{jobs.data?.filter(j=>j.parametros.projeto_id===d.projeto_id).map(j=><article className="ed-flow-card" key={j.id}><h3>Proposta {j.id.slice(0,8)}{j.resultado&&' · base v'+j.resultado.versao_base}</h3><p role="status">{j.estado.replaceAll('_',' ')} · {j.mensagem}</p>{['na_fila','pesquisando'].includes(j.estado)&&<><progress max={100} value={j.progresso} aria-label="Preparação do brief pelo Codex"/><button className="ed-button" disabled={readonly||cancel.isPending} onClick={()=>cancel.mutate(j)}>Cancelar sem perder o brief</button></>}{j.resultado&&<><small>{j.resultado.modelo} · modo {j.resultado.modo} · habilidade {j.resultado.skill.descoberta_no_runtime?'descoberta no runtime e enviada no contrato':'enviada no contrato'} · propostas, não fatos confirmados</small><details><summary>Comparar campos propostos</summary>{Object.entries(j.resultado.proposta).map(([k,text])=><div key={k}><h3>{labels[k]}{d.campos_editados.includes(k)&&' · edição manual será preservada'}</h3><p>Atual: {proposal[k]}</p><p>Proposta Codex: {text}</p></div>)}{j.resultado.observacoes_candidatas.map((x,i)=><p key={i}>Observação candidata · {x}</p>)}</details><button className="ed-button" disabled={readonly||dirty||apply.isPending||j.resultado.versao_base!==d.versao} onClick={()=>apply.mutate(j)}>Aplicar sugestões aos campos sem edição manual</button></>}</article>)}</details>
    <details><summary>{Object.keys(d.fatos).length} fatos confirmados · {Object.keys(d.candidatos).length} candidatos</summary><h3>Confirmados e exportáveis</h3>{facts(d.fatos)}<h3>Candidatos · não afirmar na página</h3>{facts(d.candidatos)}<small>Não informar um site não comprova que a empresa não tenha site.</small></details>
    <details open><summary>Brief personalizado · texto e direção para revisão</summary><fieldset className="ed-prep-fieldset" disabled={readonly||busy}>{[['Objetivo e oferta',['objetivo','publico','oferta','cta']],['Oportunidade e estrutura',['oportunidade','jornada','arquitetura']],['Copy, identidade e interações',['copy','direcao','interacoes','prospeccao']]].map(([group,keys])=><details key={group as string}><summary>{group as string}</summary>{(keys as string[]).map(k=><Field key={k} label={labels[k]}><textarea rows={k==='copy'||k==='direcao'?5:3} maxLength={6000} value={proposal[k]} onChange={e=>{setProposal({...proposal,[k]:e.target.value});setDirty(true);onDirty(true)}}/></Field>)}</details>)}</fieldset></details>
    <details><summary>{d.pendencias.length} pendências de informações, materiais e aprovação</summary><ul>{d.pendencias.map(p=><li key={p}>{p}</li>)}</ul></details>
    <details><summary>Revisar resultado e registrar evidências</summary><p>Documental: {d.revisao.documental.replaceAll('_',' ')}. Visual: {d.revisao.visual.replaceAll('_',' ')}. Conferir documentos não aprova uma página.</p><Field label="Prévia realmente inspecionada"><select value={construction} onChange={e=>{setConstruction(e.target.value);setChecks({})}}><option value="">Somente revisão documental</option>{builds.filter(b=>b.estado==='concluida').map(b=><option key={b.id} value={b.id}>{b.id.slice(0,8)} · {b.criado_em}</option>)}</select></Field>{construction&&<div className="ed-actions">{Object.entries({desktop:'Desktop',mobile:'Celular',teclado:'Teclado e foco',movimento:'Movimento reduzido',fatos:'Fatos e imagens',links:'Links e CTA'}).map(([k,label])=><label key={k} className="ed-check"><input type="checkbox" checked={!!checks[k]} onChange={e=>setChecks({...checks,[k]:e.target.checked})}/>{label} conferido</label>)}</div>}<Field label="Observações da revisão"><textarea rows={3} maxLength={6000} value={observations} onChange={e=>setObservations(e.target.value)}/></Field><small>Checklist é uma declaração sua sobre a inspeção realizada, não um teste automático. Pendências comerciais e de imagens continuam registradas.</small><button className="ed-button" disabled={readonly||busy||dirty} onClick={()=>review.mutate()}>Registrar revisão</button></details>
    <details><summary>Correções por {project?'projeto':'empresa'} e observações candidatas</summary><p>Correções aprovadas entram nas próximas instruções deste escopo mesmo com seleção manual da Biblioteca. Outros clientes não recebem estas regras.</p><Field label="Título da correção"><input value={title} maxLength={120} onChange={e=>setTitle(e.target.value)}/></Field><Field label="Correção ou observação"><textarea rows={3} maxLength={6000} value={correction} onChange={e=>setCorrection(e.target.value)}/></Field><Field label="Origem do feedback"><select value={source} onChange={e=>setSource(e.target.value)}><option value="usuario_explicito">Correção explícita revisada por mim · aplicar</option><option value="observacao_modelo">Observação do modelo · candidata, não aplicar</option></select></Field><button className="ed-button" disabled={readonly||correct.isPending||!correction.trim()||!title.trim()} onClick={()=>correct.mutate()}>Registrar neste escopo</button>{correctionQuery.data?.map(x=><article className="ed-flow-card" key={x.id}><h3>{x.titulo} · v{x.versao}</h3><p>{x.conteudo}</p><small>{x.projeto_id?'Projeto '+x.projeto_id.slice(0,8):'Esta empresa'} · {x.estado==='ativo'?'Aplicável quando o escopo coincide':x.origem_feedback==='observacao_modelo'?'Candidata · não aplicada':'Desativada'}</small>{x.estado==='inativo'&&x.origem_feedback==='observacao_modelo'&&<button className="ed-button" disabled={readonly||approve.isPending} onClick={()=>approve.mutate(x)}>Revisei · aprovar para este escopo</button>}{x.estado==='ativo'&&<button className="ed-button" disabled={readonly||disable.isPending} onClick={()=>disable.mutate(x)}>Desativar preservando histórico</button>}</article>)}</details>
    <div className="ed-actions"><button className="ed-button" disabled={readonly||busy||dirty||exportPackage.isPending} onClick={()=>exportPackage.mutate()}>{exportPackage.isPending?'Montando pacote…':'Exportar brief, skill e materiais'}</button>{exportPackage.data&&<a className="ed-button primary" href={exportPackage.data.zip_url} download>Baixar ZIP deste escopo</a>}</div>
    {[save,analyze,review,correct,approve,disable,correctionQuery,exportPackage,jobs,native,apply,cancel].filter(m=>m.isError).map((m,i)=><Erro key={i} error={m.error}/>)}
    <small>Habilidade local materializada no pacote e consumida pelo executor · hash {d.skill.sha256.slice(0,12)}. Não é treinamento do modelo nem sincronização de uma instalação no ChatGPT.</small>
  </>
}
