import {useState,useRef} from 'react'
import {Link,useSearchParams} from 'react-router-dom'
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query'
import {Send,Plus,Paperclip} from 'lucide-react'
import {httpClient} from '@/services/httpClient'
import {api} from './api'
import {csrfHeaders} from './accessState'
import {useAccess} from './accessContext'
import {Erro,Field,Loading} from './shared'
import {SpokenReply} from './VoiceControl'
import {VoiceComposer,type Transcript} from './VoiceComposer'
import {WorkflowCard,type Workflow} from './WorkflowCard'
import {RoutinesPanel} from './RoutinesPanel'
import {BatchPanel} from './BatchPanel'
import {SaveInstruction} from './SaveInstruction'
import {useCreationMode} from './useCreationMode'
import './assistant.css'
interface Message{id:string;papel:string;texto:string;execucao_id?:string;interpretacao_id?:string;erro?:string}
interface AppliedBrief{versao:number;sha256:string;campos_editados:string[];documental:string;correcoes:{titulo:string;versao:number}[]}
interface Chat{id:string;titulo:string;contexto:{empresa_id?:string;geracao?:string;modo?:string;escopo?:string;construcao_id?:string;brief_adaptativo?:{dossier:{versao:number;projeto_id:string;nome:string};exportacao_id:string}};mensagens:Message[]}
const root='/api/ed/assistente/conversas'
function Interpretation({id}:{id:string}){
 const q=useQuery({queryKey:['ed','interpretacao',id],queryFn:()=>api.operacao(id),refetchInterval:d=>['na_fila','pesquisando'].includes(d.state.data?.estado||'na_fila')?1200:false})
 return q.isError?<Erro error={q.error}/>:<div role="status">{q.data?.mensagem||'Interpretando seu comando…'}{q.data?.estado==='erro'&&<p>Comando não executado. Texto preservado; revise a conexão e tente novamente.</p>}</div>
}
export function AssistantPage({home=false,initialCompany=''}:{home?:boolean;initialCompany?:string}){
 const [params]=useSearchParams(),[scope,setScope]=useState('previa')
 const client=useQueryClient(),readonly=useAccess()?.ator?.papel==='leitura'
 const [id,setId]=useState(params.get('chat')||''),[company,setCompany]=useState(initialCompany||params.get('empresa')||''),[mode,setMode]=useState('automatico'),[text,setText]=useState(''),[origin,setOrigin]=useState('texto'),[tab,setTab]=useState('chat')
 const [uploadError,setUploadError]=useState<Error|null>(null),input=useRef<HTMLTextAreaElement>(null),messageKey=useRef(''),chatId=useRef(params.get('chat')||'')
 const [transcript,setTranscript]=useState<Transcript|null>(null),drafts=useRef(new Map<string,{text:string;origin:string;transcript:Transcript|null}>())
 const {generation,setGeneration,validated}=useCreationMode()
 const companies=useQuery({queryKey:['ed','empresas'],queryFn:()=>api.empresas()}),history=useQuery({queryKey:['ed','conversas'],queryFn:()=>httpClient.get<Chat[]>(root)})
 const chat=useQuery({queryKey:['ed','conversa',id],queryFn:()=>httpClient.get<Chat>(root+'/'+id),enabled:!!id,refetchInterval:2000}),flows=useQuery({queryKey:['ed','fluxos'],queryFn:()=>httpClient.get<Workflow[]>('/api/ed/fluxos'),refetchInterval:3000})
 function selectChat(next:string,keepDraft=false){drafts.current.set(chatId.current,{text,origin,transcript});const draft=keepDraft?{text,origin,transcript}:drafts.current.get(next);setText(draft?.text||'');setOrigin(draft?.origin||'texto');setTranscript(draft?.transcript||null);setId(next);chatId.current=next;messageKey.current=''}
 const create=useMutation({mutationFn:()=>httpClient.post<Chat>(root,{empresa_id:company,geracao:params.get('motor')||generation,modo:mode,escopo:scope,...(params.get('selecionadas')?{empresa_ids:params.get('selecionadas')!.split(','),exigir_confirmadas:params.get('confirmadas')!=='0',concorrencia:Number(params.get('concorrencia')||1)}:{})}),onSuccess:d=>{selectChat(d.id,true);client.invalidateQueries({queryKey:['ed','conversas']});setTab('chat')}})
 const send=useMutation({mutationFn:async()=>{
   if(!chatId.current){const fresh=await create.mutateAsync();chatId.current=fresh.id}
   if(!messageKey.current)messageKey.current=crypto.randomUUID()
   return httpClient.post(root+'/'+chatId.current+'/mensagens',{texto:text,chave:messageKey.current,origem:origin,...(transcript?{transcricao_id:transcript.id}:{})})
 },onSuccess:()=>{setText('');setTranscript(null);setOrigin('texto');messageKey.current='';client.invalidateQueries({queryKey:['ed']});input.current?.focus()}})
 async function attach(file?:File){if(!file)return;if(!chatId.current){const fresh=await create.mutateAsync();chatId.current=fresh.id}const f=new FormData();f.append('arquivo',file);setUploadError(null);try{const r=await fetch(root+'/'+chatId.current+'/anexos',{method:'POST',body:f,headers:csrfHeaders()});if(!r.ok)throw new Error((await r.json()).erro);client.invalidateQueries({queryKey:['ed','conversa',id]})}catch(e){setUploadError(e instanceof Error?e:new Error('Não foi possível anexar a referência.'))}}
 const active=flows.data?.filter(x=>['na_fila','executando','aguardando_dependencia','pausada'].includes(x.estado))||[]
 const examples=params.get('selecionadas')?['Crie as prévias das '+params.get('selecionadas')!.split(',').length+' empresas selecionadas.']:(chat.data?.contexto.empresa_id||company)?['Prepare a prévia desta empresa.','Refine só o hero, mantendo as fotos.','Use a segunda alternativa do hero.']:['Mostre os leads sem site.','Pesquise 2 academias em Recife, organize os leads e prepare uma prévia.']
 return <><div className="ed-page-head"><div><h1>{home?'O que vamos criar hoje?':'Seu assistente'}</h1><p>Pesquise empresas, prepare uma prévia ou refine o que já criou.</p></div><Link className="ed-button" to="/nova-busca">Pesquisar pelo formulário</Link></div>
 <nav className="ed-settings-tabs" aria-label="Assistente"><button className="ed-button" aria-pressed={tab==='chat'} onClick={()=>setTab('chat')}>Comando</button><button className="ed-button" aria-pressed={tab==='fluxos'} onClick={()=>setTab('fluxos')}>Execuções{active.length?' · '+active.length+' pendente'+(active.length===1?'':'s'):''}</button><button className="ed-button" aria-pressed={tab==='rotinas'} onClick={()=>setTab('rotinas')}>Rotinas</button></nav>
 {tab==='chat'&&<><section className="ed-panel ed-form ed-command-workbench" aria-label="Comando de criação"><form onSubmit={e=>{e.preventDefault();if(text.trim())send.mutate()}}>
 <Field label="Seu comando"><textarea ref={input} rows={3} required maxLength={12000} disabled={readonly||send.isPending} placeholder="Ex.: Prepare uma prévia da PÃO, com composição editorial e contato claro." value={text} onChange={e=>{setText(e.target.value);messageKey.current=''}}/></Field>
 <VoiceComposer key={id||company||'nova'} disabled={readonly||send.isPending} onAutoSend={()=>{if(text.trim()&&!send.isPending)send.mutate()}} onText={(v,source)=>{setText(t=>t.trim()?t+'\n'+v:v);setTranscript(source);setOrigin('voz');messageKey.current='';input.current?.focus()}}/>
 <div className="ed-command-toolbar"><Field label={id?'Contexto desta conversa':'Empresa (opcional)'}><select disabled={!!id||send.isPending||!!initialCompany||!!params.get('selecionadas')} value={chat.data?.contexto.empresa_id||company} onChange={e=>setCompany(e.target.value)}><option value="">Pesquisa geral</option>{companies.data?.map(x=><option value={x.id} key={x.id}>{x.nome}</option>)}</select></Field><button className="ed-button primary" disabled={readonly||send.isPending||!text.trim()}><Send size={16}/>{send.isPending?'Registrando…':'Executar comando'}</button></div>{send.isError&&<Erro error={send.error}/>}</form>
 <div className="ed-command-examples" aria-label="Exemplos de comando">{examples.map(value=><button className="ed-button" type="button" disabled={send.isPending} key={value} onClick={()=>{setText(value);messageKey.current='';input.current?.focus()}}>{value}</button>)}</div>
 <details className="ed-creation-details"><summary>{(chat.data?.contexto.geracao||generation)==='codex_nativo'?'Criar com Codex nativo':'Montagem rápida local'} · opções e referências</summary><div className="ed-form-grid"><Field label="Construção"><select disabled={!!id||send.isPending||!!params.get('motor')} value={chat.data?.contexto.geracao||params.get('motor')||generation} onChange={e=>setGeneration(e.target.value)}><option value="codex_nativo">Codex nativo · plano ChatGPT</option><option value="openrouter">OpenRouter · modelo configurado / cobrança própria</option><option value="opencode">OpenCode · gratuito configurado</option><option value="gateway">Gateway local · modelo por tarefa validado</option><option value="templates">Montagem rápida · template local</option></select></Field><Field label="Escopo"><select disabled={!!id||send.isPending} value={chat.data?.contexto.escopo||scope} onChange={e=>setScope(e.target.value)}><option value="previa">Prévia para prospecção</option><option value="completo">Site completo · banco/login/admin local</option></select></Field><Field label="Até onde executar"><select disabled={!!id||send.isPending} value={chat.data?.contexto.modo||mode} onChange={e=>setMode(e.target.value)}><option value="automatico">Até a prévia renderizada</option><option value="assistido">Preparar o pacote para revisão</option></select></Field></div>
 <small>GPT-6.1 Sol · Alto · Padrão. {validated?'Modelo executado com a conta nativa selecionada.':'Confira o acesso ao modelo em Conexões.'} Pesquise até 25 leads; selecione até cinco para o lote. Uma construção por vez. Sem envio comercial ou publicação. Fallback usa somente rotas gratuitas autorizadas em Conexões; nenhum modelo pago automático.</small>
 <SaveInstruction key={chat.data?.contexto.empresa_id||company||'global'} company={chat.data?.contexto.empresa_id||company} niche={companies.data?.find(c=>c.id===(chat.data?.contexto.empresa_id||company))?.nicho} text={text} disabled={readonly||send.isPending}/>
 {<label className="ed-button"><Paperclip size={15}/> Anexar arquivo de referência<input className="ed-sr-only" type="file" accept=".txt,.md,.html,.htm" disabled={readonly} onChange={e=>attach(e.target.files?.[0])}/></label>}<Link to="/biblioteca/referencias">Revisar referências na biblioteca ↗</Link>{uploadError&&<Erro error={uploadError}/>}</details></section>
 <details className="ed-chat-history-panel"><summary>Conversas anteriores{history.data?.length?' · '+history.data.length:''}</summary><button className="ed-button" disabled={readonly||send.isPending||create.isPending} onClick={()=>{selectChat('');setText('');setTranscript(null);setOrigin('texto');input.current?.focus()}}><Plus size={16}/> Nova conversa</button><nav aria-label="Histórico do assistente">{history.data?.map(c=><button key={c.id} className="ed-chat-history" disabled={send.isPending} aria-pressed={id===c.id} onClick={()=>selectChat(c.id)}>{c.titulo}</button>)}</nav>{history.isError&&<Erro error={history.error}/>}</details>
 {chat.isPending&&id&&<Loading/>}{chat.isError&&<Erro error={chat.error}/>} {create.isError&&<Erro error={create.error}/>} {chat.data&&<section className="ed-chat-results" aria-label="Resultados da conversa"><ActiveProject chat={chat.data}/><h2>{chat.data.titulo}</h2>{chat.data.contexto.empresa_id&&<Link to={'/empresas/'+chat.data.contexto.empresa_id}>Abrir empresa ↗</Link>}<div className="ed-chat-messages">{chat.data.mensagens.map(m=><article key={m.id} className={'ed-message '+m.papel}><strong>{m.papel==='usuario'?'Você':m.papel==='anexo'?'Referência adicionada':'EDY'}</strong><p>{m.texto}</p>{m.erro&&<p role="alert">{m.erro}</p>}{m.interpretacao_id&&<Interpretation id={m.interpretacao_id}/>}</article>)}</div>{[...new Set(chat.data.mensagens.map(m=>m.execucao_id).filter(Boolean) as string[])].map(j=><WorkflowCard key={j} id={j}/>)}<details><summary>Ouvir resultado</summary><SpokenReply text={chat.data.mensagens.filter(m=>m.papel==='assistente').at(-1)?.texto||'Resultados disponíveis no histórico do EDY CRM.'}/></details></section>}
 {!id&&active.length>0&&<section><h2>Em andamento</h2>{active.slice(0,3).map(j=><WorkflowCard key={j.id} id={j.id}/>)}</section>}</>}
 {tab==='fluxos'&&<section className="ed-research"><BatchPanel/>{flows.isError&&<Erro error={flows.error}/>} {!flows.isPending&&!flows.data?.length&&<p>Nenhuma execução. Comece com um comando.</p>}{flows.data?.map(j=><WorkflowCard key={j.id} id={j.id}/>)}</section>}{tab==='rotinas'&&<RoutinesPanel/>}</>
}

function ActiveProject({chat}:{chat:Chat}){
 const company=chat.contexto.empresa_id,client=useQueryClient()
 const q=useQuery({queryKey:['ed','construcoes',company],enabled:!!company,queryFn:()=>httpClient.get<{id:string;estado:string;tipo:string;criado_em:string;resultado?:{escopo:string;brief_aplicado?:AppliedBrief;imagens_enviadas?:{arquivo:string;uso:string}[]}}[]>('/api/ed/empresas/'+company+'/construcoes'),refetchInterval:3000})
 const select=useMutation({mutationFn:(construcao_id:string)=>httpClient.put(root+'/'+chat.id+'/projeto',{construcao_id}),onSuccess:()=>client.invalidateQueries({queryKey:['ed','conversa',chat.id]})})
 if(!company)return null
 const done=q.data?.filter(x=>x.tipo==='codex_construcao'&&x.estado==='concluida')||[]
 const active=done.find(b=>b.id===chat.contexto.construcao_id),brief=active?.resultado?.brief_aplicado,pin=chat.contexto.brief_adaptativo
 return <div>{pin&&<p role="status">Brief selecionado: {pin.dossier.nome} · v{pin.dossier.versao}. Refinamentos preservam esta revisão; uma nova seleção de brief inicia outra conversa.</p>}<Field label="Projeto e versão ativos" hint="O refinamento usa a versão escolhida; as demais permanecem no histórico."><select value={chat.contexto.construcao_id||''} disabled={select.isPending} onChange={e=>select.mutate(e.target.value)}><option value="">Última versão concluída desta empresa{done[0]?' · '+done[0].id.slice(0,8):' · ainda não criada'}</option>{done.map(b=><option key={b.id} value={b.id}>{b.id.slice(0,8)} · {b.criado_em} · {b.resultado?.escopo==='completo'?'site completo':'prévia'}</option>)}</select></Field>{brief&&<details><summary>Contexto efetivamente enviado ao executor · brief v{brief.versao}</summary><p>Revisão documental: {brief.documental} · SHA-256 {brief.sha256}</p><p>Edições manuais: {brief.campos_editados.join(', ')||'nenhuma'}</p><p>Correções deste escopo: {brief.correcoes.map(x=>x.titulo+' v'+x.versao).join('; ')||'nenhuma'}</p><ul>{active?.resultado?.imagens_enviadas?.map(x=><li key={x.arquivo}>{x.arquivo} · {x.uso}</li>)}</ul><small>Registro do payload enviado, independente de aprovação visual. O ledger completo permanece no workspace como contexto-executor.json e no resultado da execução.</small></details>}{select.isError&&<Erro error={select.error}/>}</div>
}
