import { useEffect,useState } from 'react'
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query'
import { Download,Lock,Plus,ArrowUp,ArrowDown,Maximize2 } from 'lucide-react'
import type { Empresa } from './types'
import { studioApi,type Composition,type Alternative } from './studioApi'
import { SectionRenderer } from './SectionRenderer'
import { Field,Erro,Loading,Badge } from './shared'
import { date } from './domain'
import './studio.css'
import { libraryApi } from './libraryApi'

const kinds=['hero','apresentacao','servicos','produtos','galeria','equipe','processo','faq','prova','contato','cta','rodape','dados','operacoes']
const motions:Record<string,string[]>={titulos:['nenhum','suave','escalonado'],transicoes:['nenhuma','revelar'],imagens:['nenhuma','zoom'],cartoes:['nenhuma','elevar'],botoes:['nenhuma','deslocar'],cursor:['nenhum','halo'],parallax:['desligado','leve'],shader:['desligado','gradiente']}
const layouts=['editorial','imersiva','mosaico','compacta']
export function CompositionPanel({empresa}:{empresa:Empresa}){
 const q=useQuery({queryKey:['ed','composicao',empresa.id],queryFn:()=>studioApi.composition(empresa.id)})
 if(q.isPending)return <Loading/>
 if(q.isError)return <Erro error={q.error}/>
 return <Composer key={`${empresa.id}:${q.data.revisao}`} company={empresa} initial={q.data}/>
}
function Composer({company,initial}:{company:Empresa;initial:Composition}){
 const [importing,setImporting]=useState(false)
 const [hidden,setHidden]=useState(document.hidden)
 useEffect(()=>{const visibility=()=>setHidden(document.hidden);document.addEventListener('visibilitychange',visibility);return()=>document.removeEventListener('visibilitychange',visibility)},[])
 const client=useQueryClient(),[state,setState]=useState(initial),[sectionId,setSectionId]=useState(initial.secoes[0].id),[mobile,setMobile]=useState(false),[large,setLarge]=useState(''),[whole,setWhole]=useState(false),[newKind,setNewKind]=useState('servicos'),[error,setError]=useState(''),[importText,setImportText]=useState('')
 const section=state.secoes.find(s=>s.id===sectionId)||state.secoes[0]
 const [memoryScope,setMemoryScope]=useState('projeto'),[memoryTitle,setMemoryTitle]=useState(''),[memoryText,setMemoryText]=useState('')
 const memory=useMutation({mutationFn:()=>libraryApi.save({tipo:'contexto',titulo:memoryTitle,conteudo:memoryText,escopo:memoryScope,vinculo:memoryScope==='global'?'':memoryScope==='nicho'?company.nicho:company.id,origem:'Refinamento revisado no estúdio',estado:'ativo'}),onSuccess:()=>{client.invalidateQueries({queryKey:['ed','biblioteca']});client.invalidateQueries({queryKey:['ed','contexto',company.id]})}})
 const selected=section.alternativas.find(a=>a.id===section.escolhida)!
 const history=useQuery({queryKey:['ed','composicao-historico',company.id],queryFn:()=>studioApi.history(company.id)})
 const save=useMutation({mutationFn:()=>studioApi.saveComposition(company.id,state),onSuccess:s=>{client.setQueryData(['ed','composicao',company.id],s);client.invalidateQueries({queryKey:['ed','composicao-historico',company.id]})}})
 const change=(key:string,value:unknown)=>setState({...state,[key]:value})
 const updateSection=(value:Partial<typeof section>)=>{if(section.fixada&&value.fixada!==false){setError('Desfixe a seção para refiná-la.');return}setState({...state,secoes:state.secoes.map(s=>s.id===section.id?{...s,...value}:s)})}
 const updateAlternative=(value:Partial<Alternative>)=>updateSection({alternativas:section.alternativas.map(a=>a.id===selected.id?{...a,...value,versao:a.versao+1}:a)})
 const reorder=(delta:number)=>{const list=[...state.secoes],i=list.findIndex(s=>s.id===section.id),j=i+delta;if(j<0||j>=list.length)return;[list[i],list[j]]=[list[j],list[i]];change('secoes',list)}
 const download=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='composicao.json';a.click();URL.revokeObjectURL(url)}
 const importAlternatives=async()=>{setImporting(true);try{const data=JSON.parse(importText);if(!Array.isArray(data)||data.length!==4||data.some(a=>!a||typeof a!=='object'))throw Error('Importe quatro alternativas no contrato do estúdio.');const alternativas=data.map(a=>{const clean={...a};delete clean.arquivo;delete clean.arquivo_mobile;delete clean.pendencia_material;return {...clean,origem:'Codex externo · contrato importado'}});const validated=await studioApi.validateComposition(company.id,{...state,secoes:state.secoes.map(s=>s.id===section.id?{...s,alternativas}:s)});setState(validated);setImportText('');setError('')}catch(e){setError(e instanceof Error?e.message:'Contrato inválido.')}finally{setImporting(false)}}
 return <fieldset disabled={save.isPending||importing} className={`ed-studio ed-studio-fieldset ${hidden?'is-hidden':''}`} ><section className="ed-panel ed-form"><div className="ed-panel-head"><div><span className="ed-eyebrow">COMPOSIÇÃO · VERSÃO {state.revisao}</span><h2>Monte a direção da prévia</h2><p>Quatro layouts renderizados por seção. Escolha, refine e fixe cada parte sem substituir as demais.</p></div><Badge tone="amber">Composição visual · construção na aba Construir</Badge></div>
 <details><summary>Salvar uma decisão na biblioteca</summary><p>Revise o aprendizado e escolha seu alcance. Uma decisão de projeto não é aplicada a outras marcas.</p><Field label="Título da decisão"><input value={memoryTitle} maxLength={500} onChange={e=>setMemoryTitle(e.target.value)}/></Field><Field label="Alcance da decisão"><select value={memoryScope} onChange={e=>setMemoryScope(e.target.value)}><option value="projeto">Somente este projeto</option><option value="lead">Esta empresa</option><option value="nicho">Este nicho · {company.nicho}</option><option value="global">Preferência global revisada</option></select></Field><Field label="Aprendizado revisado"><textarea rows={3} maxLength={20000} value={memoryText} onChange={e=>setMemoryText(e.target.value)}/></Field><button className="ed-button" disabled={!memoryTitle.trim()||!memoryText.trim()||memory.isPending||(memoryScope==='nicho'&&!company.nicho)} onClick={()=>memory.mutate()}>Salvar decisão versionada</button>{memory.isSuccess&&<p role="status">Decisão salva. Confira O que será usado antes de gerar um novo pacote.</p>}{memory.isError&&<Erro error={memory.error}/>}</details>
 <fieldset disabled={save.isPending} className="ed-studio-fieldset"><div className="ed-form-grid"><Field label="Tipo de projeto"><select value={state.tipo} onChange={e=>change('tipo',e.target.value)}><option value="landing">Landing page para prospecção</option><option value="site">Site completo</option><option value="dashboard">Dashboard</option><option value="admin">Painel administrativo</option></select></Field><Field label="Tipografia da composição"><select value={state.identidade.fonte} onChange={e=>change('identidade',{...state.identidade,fonte:e.target.value})}><option value="editorial">Editorial · serifada</option><option value="moderna">Moderna · sem serifa</option></select></Field>{(['fundo','tinta','acento'] as const).map(k=><Field key={k} label={`Cor ${k}`}><input type="color" value={state.identidade[k]} onChange={e=>change('identidade',{...state.identidade,[k]:e.target.value})}/></Field>)}</div>
 {state.tipo!=='landing'&&<details open><summary>Requisitos funcionais para construção</summary><p>Registrar requisitos não implementa banco, login ou CRUD. A construção precisa de testes próprios.</p><div className="ed-form-grid">{Object.entries(state.requisitos).map(([k,v])=><Field key={k} label={k}><textarea rows={2} maxLength={4000} value={v} onChange={e=>change('requisitos',{...state.requisitos,[k]:e.target.value})}/></Field>)}</div></details>}
 <details><summary>Direção de movimento</summary><div className="ed-form-grid">{Object.entries(motions).map(([k,opts])=><Field key={k} label={`Movimento · ${k}`}><select value={state.movimento[k]} onChange={e=>change('movimento',{...state.movimento,[k]:e.target.value})}>{opts.map(v=><option key={v}>{v}</option>)}</select></Field>)}</div><p>Gradiente é o fundo estático/animado leve disponível aqui; shaders adicionais são instruções para o Codex. Cursor desativado em toque e movimento reduzido. Animações contínuas pausam com aba oculta.</p></details>
 <details><summary>Biblioteca de referências ({state.referencias.length})</summary><p>Guarde observações e screenshots enviados em Materiais. Referências não autorizam copiar fotos ou identidade.</p>{state.referencias.map((r,i)=><div className="ed-reference-editor" key={i}><div className="ed-form-grid">{['url','nicho','secoes','elementos','observacoes'].map(k=><Field key={k} label={`Referência ${i+1} · ${k}`}><input value={r[k as keyof typeof r]} maxLength={2000} onChange={e=>change('referencias',state.referencias.map((x,n)=>n===i?{...x,[k]:e.target.value}:x))}/></Field>)}<Field label={`Screenshot da referência ${i+1}`}><select value={r.material_id} onChange={e=>change('referencias',state.referencias.map((x,n)=>n===i?{...x,material_id:e.target.value}:x))}><option value="">Sem screenshot</option>{company.materiais.map(m=><option key={m.id} value={m.id}>{m.nome_original}</option>)}</select></Field></div><button className="ed-button" onClick={()=>change('referencias',state.referencias.filter((_,n)=>n!==i))}>Remover referência {i+1}</button></div>)}<button className="ed-button" disabled={state.referencias.length>=30} onClick={()=>change('referencias',[...state.referencias,{url:'',material_id:'',nicho:company.nicho,secoes:'',elementos:'',observacoes:''}])}>Adicionar referência</button></details>
 <details><summary>Aprovação pelo titular · {state.aprovacao_titular.estado}</summary><p>A revisão técnica do CRM é independente da autorização comercial do titular.</p><Field label="Situação da aprovação"><select value={state.aprovacao_titular.estado} onChange={e=>change('aprovacao_titular',{...state.aprovacao_titular,estado:e.target.value})}><option value="pendente">Pendente</option><option value="aprovado">Aprovado pelo titular</option></select></Field><Field label="Evidência da aprovação do titular"><textarea value={state.aprovacao_titular.evidencia} maxLength={2000} onChange={e=>change('aprovacao_titular',{...state.aprovacao_titular,evidencia:e.target.value})}/></Field></details>
 </fieldset><div className="ed-form-actions"><button className="ed-button primary" disabled={save.isPending} onClick={()=>save.mutate()}>{save.isPending?'Salvando…':'Salvar composição e versão'}</button><button className="ed-button" onClick={download}><Download size={16}/> Contrato para Codex externo</button><button className="ed-button" aria-pressed={whole} onClick={()=>setWhole(!whole)}>{whole?'Comparar seções':'Ver composição completa'}</button></div>{save.isError&&<Erro error={save.error}/>} {error&&<div role="alert" className="ed-alert error">{error}<button className="ed-button" onClick={()=>setError('')}>Fechar aviso</button></div>}
 <small>Salve antes de exportar. O pacote utiliza a última composição salva; edições locais ainda não salvas não entram no ZIP.</small></section>
 <div className="ed-studio-toolbar"><Field label="Seção em edição"><select value={section.id} onChange={e=>{setSectionId(e.target.value);setLarge('')}}>{state.secoes.map(s=><option key={s.id} value={s.id}>{s.tipo} · {s.id}{s.fixada?' · fixada':''}</option>)}</select></Field><button className="ed-button" aria-pressed={mobile} onClick={()=>setMobile(!mobile)}>{mobile?'Celular · 390 px':'Desktop'}</button><button className="ed-button" disabled={state.secoes.findIndex(s=>s.id===section.id)===0} onClick={()=>reorder(-1)}><ArrowUp size={16}/> Subir seção</button><button className="ed-button" disabled={state.secoes.at(-1)?.id===section.id} onClick={()=>reorder(1)}><ArrowDown size={16}/> Descer seção</button><button className="ed-button" aria-pressed={section.fixada} onClick={()=>updateSection({fixada:!section.fixada})}><Lock size={16}/>{section.fixada?'Desfixar seção':'Fixar escolha'}</button></div>
 {whole?<div className={`ed-composition-canvas ${mobile?'mobile':''}`} aria-label="Composição completa">{state.secoes.map(s=><SectionRenderer key={s.id} company={company} composition={state} block={s} alternative={s.alternativas.find(a=>a.id===s.escolhida)!} mobile={mobile} page/>)}</div>:<div className="ed-alternative-grid">{section.alternativas.map(a=><article key={a.id} className={`ed-alternative ${a.id===section.escolhida?'chosen':''}`}><div className="ed-alternative-head"><strong>Opção {a.id.toUpperCase()} · {a.layout}</strong><span>v{a.versao}</span></div><div className={`ed-alternative-canvas ${mobile?'mobile':''}`}><SectionRenderer company={company} composition={state} block={section} alternative={a} mobile={mobile}/></div><div className="ed-form-actions"><button className="ed-button" aria-pressed={a.id===section.escolhida} disabled={section.fixada} onClick={()=>updateSection({escolhida:a.id})}>{a.id===section.escolhida?'Escolhida':'Escolher'} {a.id.toUpperCase()}</button><button className="ed-button" onClick={()=>setLarge(a.id)}><Maximize2 size={14}/> Ampliar {a.id.toUpperCase()}</button></div></article>)}</div>}
 {large&&<section className="ed-panel ed-form" aria-label="Alternativa ampliada"><div className="ed-panel-head"><h3>Alternativa {large.toUpperCase()} ampliada</h3><button className="ed-button" onClick={()=>setLarge('')}>Fechar ampliação</button></div><div className={`ed-composition-canvas ${mobile?'mobile':''}`}><SectionRenderer company={company} composition={state} block={section} alternative={section.alternativas.find(a=>a.id===large)!} mobile={mobile}/></div></section>}
 <section className="ed-panel ed-form"><h2>Refinar somente a opção {selected.id.toUpperCase()} · {section.tipo}</h2><fieldset className="ed-studio-fieldset" disabled={section.fixada||save.isPending}><div className="ed-form-grid"><Field label="Título da alternativa"><input value={selected.titulo} maxLength={300} onChange={e=>updateAlternative({titulo:e.target.value,revisado:false})}/></Field><Field label="CTA da alternativa"><input value={selected.cta} maxLength={300} onChange={e=>updateAlternative({cta:e.target.value,revisado:false})}/></Field><Field label="Material da seção"><select value={selected.material_id} onChange={e=>updateAlternative({material_id:e.target.value})}><option value="">Placeholder identificado</option>{company.materiais.filter(m=>m.autorizado&&m.selecionado).map(m=><option key={m.id} value={m.id}>{m.nome_original}</option>)}</select></Field><Field label="Composição da alternativa"><select value={selected.layout} onChange={e=>updateAlternative({layout:e.target.value})}>{layouts.map(x=><option key={x}>{x}</option>)}</select></Field></div><Field label="Texto proposto da alternativa"><textarea value={selected.texto} maxLength={4000} rows={4} onChange={e=>updateAlternative({texto:e.target.value,revisado:false})}/></Field><Field label="Pedido de refinamento da seção" hint="Guarda direção específica para o Codex; não chama IA automaticamente."><textarea value={selected.instrucoes} rows={2} onChange={e=>updateAlternative({instrucoes:e.target.value})}/></Field><div className="ed-form-grid">{(['desktop','mobile'] as const).flatMap(mode=>[0,1].map(i=><Field key={mode+i} label={`Enquadramento ${mode} ${i?'Y':'X'} (%)`}><input type="number" min={0} max={100} value={selected[mode][i]} onChange={e=>updateAlternative({[mode]:selected[mode].map((x,n)=>n===i?Number(e.target.value):x)})}/></Field>))}</div><label className="ed-check"><input type="checkbox" checked={selected.revisado} onChange={e=>updateAlternative({revisado:e.target.checked})}/> Texto revisado tecnicamente; aprovação do titular continua separada.</label>
 <button className="ed-button" onClick={()=>updateAlternative({layout:layouts[(layouts.indexOf(selected.layout)+1)%4],origem:'template_local · recomposição manual'})}>Recompor somente esta alternativa</button><details><summary>Importar quatro alternativas externas do Codex</summary><p>Use a lista “alternativas” desta seção no composicao.json. O contrato aceita conteúdo, materiais desta empresa, recortes e quatro layouts suportados. Código arbitrário não é executado no CRM.</p><textarea aria-label="JSON das quatro alternativas" rows={5} value={importText} onChange={e=>setImportText(e.target.value)}/><button className="ed-button" onClick={importAlternatives}>Importar alternativas para revisão</button></details></fieldset></section>
 <section className="ed-panel ed-form"><div className="ed-form-actions"><Field label="Tipo da nova seção"><select value={newKind} onChange={e=>setNewKind(e.target.value)}>{kinds.map(x=><option key={x}>{x}</option>)}</select></Field><button className="ed-button" disabled={state.secoes.length>=30} onClick={()=>{const id=newKind+'-'+Date.now();change('secoes',[...state.secoes,{id,tipo:newKind,fixada:false,escolhida:'a',alternativas:layouts.map((layout,i)=>({...selected,id:'abcd'[i],layout,titulo:newKind,texto:'',revisado:false,instrucoes:'',versao:1,origem:'template_local',material_id:''}))}]);setSectionId(id)}}><Plus size={16}/> Incluir seção</button><button className="ed-button" disabled={section.fixada||state.secoes.length===1} onClick={()=>{change('secoes',state.secoes.filter(s=>s.id!==section.id));setSectionId('')}}>Remover seção {section.tipo}</button></div>
 <details><summary>Recuperar versões ({history.data?.length||0})</summary>{history.data?.map(h=><p key={h.composicao.revisao}>Versão {h.composicao.revisao} · {date(h.criado_em)} <button className="ed-button" onClick={()=>{setState({...h.composicao,revisao:state.revisao,secoes:h.composicao.secoes.map(s=>({...s,fixada:false}))});setSectionId(h.composicao.secoes[0].id)}}>Carregar versão {h.composicao.revisao} para revisão</button></p>)}<small>Desfixe escolhas atuais antes de restaurar uma versão diferente. Salvar cria uma nova versão; não apaga o histórico.</small></details></section>
 </fieldset>
}
