import {useQuery} from '@tanstack/react-query'
import {Link} from 'react-router-dom'
import {Building2,Files,PanelsTopLeft,Workflow} from 'lucide-react'
import {httpClient} from '@/services/httpClient'
import {api} from './api'
import {Badge,Erro,Loading} from './shared'
import {date,etapas} from './domain'
import type {Stage} from './crmApi'
import './dashboard-glass.css'

export function DashboardOverview(){
 const q=useQuery({queryKey:['ed','dashboard'],queryFn:()=>httpClient.get<{empresas:number;reais:number;demonstracoes:number;oportunidades:number;tarefas_abertas:number;vencidas:number;pacotes:number;previas:number;fases:(Stage&{total:number})[];fonte:string}>('/api/ed/crm/resumo')})
 const leads=useQuery({queryKey:['ed','empresas'],queryFn:()=>api.empresas()})
 const flows=useQuery({queryKey:['ed','fluxos'],queryFn:()=>httpClient.get<{id:string;estado:string;criado_em:string;mensagem:string;plano:{acao:string}}[]>('/api/ed/fluxos')})
 if(q.isPending)return <Loading/>;if(q.isError)return <Erro error={q.error}/>
 const d=q.data,stats=[{nome:'Empresas',valor:d.empresas,nota:`${d.reais} reais · ${d.demonstracoes} demonstração`,icon:Building2,url:'/leads'},{nome:'Oportunidades',valor:d.oportunidades,nota:'Registros no funil do workspace',icon:Workflow,url:'/crm/funil'},{nome:'Pacotes',valor:d.pacotes,nota:'Exportações com histórico',icon:Files,url:'/leads'},{nome:'Versões de prévia',valor:d.previas,nota:'Projetos e refinamentos registrados',icon:PanelsTopLeft,url:'/previas'}]
 const colors=['#56c5f2','#c099fa','#53cd8b','#f5be61','#ffa88f','#ef839b']
 let offset=0
 return <div className="ed-dashboard-overview"><div className="ed-dashboard-stats">{stats.map((s,i)=><Link to={s.url} key={s.nome} className="ed-dashboard-stat"><span className="ed-dashboard-stat-icon" style={{color:colors[i]}}><s.icon size={15}/></span><span>{s.nome}</span><strong>{s.valor}</strong><small>{s.nota}</small></Link>)}</div>
 {d.vencidas>0&&<div role="status" className="ed-alert">{d.vencidas} tarefa(s) vencida(s). <Link to="/crm/tarefas">Revisar lembretes internos ↗</Link></div>}
 <div className="ed-dashboard-grid"><section className="ed-panel ed-form ed-dashboard-panel"><div className="ed-dashboard-panel-head"><h2>Distribuição no funil</h2><Link className="ed-text-button" to="/crm/funil">Abrir funil ↗</Link></div><div className="ed-dashboard-bars">{d.fases.map((s,i)=><div className="ed-stage-bar" key={s.id}><span>{s.nome}</span><progress max={Math.max(1,d.oportunidades)} value={s.total} aria-label={s.nome} style={{accentColor:colors[i%colors.length]}}/><strong>{s.total}</strong></div>)}</div><small>{d.fonte}</small></section>
 <section className="ed-panel ed-form ed-dashboard-panel"><h2>Oportunidades por etapa</h2><div className="ed-dashboard-donut"><svg viewBox="0 0 120 120" role="img" aria-label={d.fases.map(s=>s.nome+': '+s.total).join('; ')}><circle cx="60" cy="60" r="45" fill="none" stroke="var(--ed-border)" strokeWidth="10"/>{d.fases.filter(s=>s.total).map(s=>{const length=s.total/Math.max(1,d.oportunidades)*282.74;const start=offset;offset+=length;return <circle key={s.id} cx="60" cy="60" r="45" fill="none" stroke={colors[d.fases.findIndex(f=>f.id===s.id)%colors.length]} strokeWidth="10" strokeDasharray={`${length} 282.74`} strokeDashoffset={-start}/>})}</svg><div><strong>{d.oportunidades}</strong><small>No funil</small></div></div><div className="ed-dashboard-legend">{d.fases.map((s,i)=><div key={s.id}><span><i style={{background:colors[i%colors.length]}}/>{s.nome}</span><strong>{s.total}</strong></div>)}</div></section></div>
 <div className="ed-dashboard-grid"><section className="ed-panel ed-form ed-dashboard-panel"><div className="ed-dashboard-panel-head"><h2>Empresas recentes</h2><Link className="ed-text-button" to="/leads">Todas as empresas ↗</Link></div>{leads.isError?<Erro error={leads.error}/>:leads.isPending?<Loading/>:<div className="ed-table-wrap"><table className="ed-table"><thead><tr><th>Empresa</th><th>Nicho</th><th>Etapa</th></tr></thead><tbody>{[...leads.data].sort((a,b)=>b.atualizado_em.localeCompare(a.atualizado_em)).slice(0,5).map(l=><tr key={l.id}><td><Link className="ed-dashboard-company" to={'/empresas/'+l.id}><span>{l.nome.slice(0,1)}</span><span><strong>{l.nome}</strong><small>{l.cidade||'Localização a revisar'}{l.demonstracao?' · demonstração':''}</small></span></Link></td><td>{l.nicho}</td><td><Badge tone={l.etapa==='previa_pronta'?'green':'amber'}>{etapas[l.etapa]||l.etapa}</Badge></td></tr>)}</tbody></table></div>}</section>
 <section className="ed-panel ed-form ed-dashboard-panel"><div className="ed-dashboard-panel-head"><h2>Últimas execuções</h2><Link className="ed-text-button" to="/assistente">Acompanhar ↗</Link></div>{flows.isError?<Erro error={flows.error}/>:flows.isPending?<Loading/>:flows.data.length?<ul className="ed-dashboard-log">{flows.data.slice(0,5).map(f=><li key={f.id}><strong>{({preparar:'Preparar prévia',refinar:'Refinar projeto',pesquisar:'Pesquisar empresas',consultar:'Consultar leads'} as Record<string,string>)[f.plano.acao]||'Execução do CRM'}</strong><p>{f.mensagem}</p><small>{date(f.criado_em)} · {f.estado==='parcial'?'Revisão pendente':f.estado}</small></li>)}</ul>:<p>Nenhuma execução. <Link to="/">Começar com um comando ↗</Link></p>}<Link to="/crm/tarefas" className="ed-dashboard-task-link">{d.tarefas_abertas} tarefa(s) aberta(s) · revisar tarefas ↗</Link></section></div></div>
}
