import {useState} from 'react'
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query'
import {httpClient} from '@/services/httpClient'
import {api} from './api'
import {Field,Erro,Badge,Loading,External} from './shared'
interface Destination{id:string;nome:string;grupo:string;finalidade:string;campos:Record<string,string>;config:Record<string,string>;acesso:string;estado:string;credencial_presente:boolean;docs:string;prova:{data?:string;mensagem?:string;capacidade?:string;conta?:string;recursos?:{id?:string;nome:string;modo?:string}[]}}
export function DestinationCards(){
 const q=useQuery({queryKey:['ed','destinos'],queryFn:()=>httpClient.get<Destination[]>('/api/ed/destinos')})
 return q.isPending?<Loading/>:q.isError?<Erro error={q.error}/>:<>{['Publicar e armazenar','Automatizar'].map(group=><section key={group} className="ed-connection-group"><h2>{group}</h2>{q.data.filter(x=>x.grupo===group).map(c=><DestinationCard key={c.id+JSON.stringify(c.config)} c={c}/>)}{group==='Automatizar'&&<p><a href="/api/ed/destinos/n8n/rascunhos">Baixar três rascunhos n8n</a> · Envelopes de demonstração inativos, sem operação remota.</p>}</section>)}</>
}
function DestinationCard({c}:{c:Destination}){
 const client=useQueryClient(),[settings,setSettings]=useState(c.config),[secret,setSecret]=useState(''),[access,setAccess]=useState(''),[jobId,setJobId]=useState('')
 const save=useMutation({mutationFn:()=>httpClient.put('/api/ed/destinos/'+c.id,{...settings,...secret?{credencial:secret}:{},...access?{access_key:access}:{}}),onSuccess:()=>{setSecret('');setAccess('');client.invalidateQueries({queryKey:['ed','destinos']})}})
 const test=useMutation({mutationFn:()=>httpClient.post<{id:string}>('/api/ed/destinos/'+c.id+'/testar'),onSuccess:d=>setJobId(d.id)})
 const job=useQuery({queryKey:['ed','operacao',jobId],queryFn:async()=>{const j=await api.operacao(jobId);if(!['na_fila','pesquisando'].includes(j.estado))client.invalidateQueries({queryKey:['ed','destinos']});return j},enabled:!!jobId,refetchInterval:q=>['na_fila','pesquisando'].includes(q.state.data?.estado||'')?1200:false})
 const running=!!job.data&&['na_fila','pesquisando'].includes(job.data.estado)
 const cancel=useMutation({mutationFn:()=>api.cancelarOperacao(jobId),onSuccess:()=>client.invalidateQueries({queryKey:['ed','operacao',jobId]})})
 const remove=useMutation({mutationFn:()=>httpClient.put('/api/ed/destinos/'+c.id,{remover_credencial:true}),onSuccess:()=>client.invalidateQueries({queryKey:['ed','destinos']})})
 return <details className="ed-panel ed-connection-disclosure"><summary><strong>{c.nome}</strong><span>{c.finalidade}</span><Badge tone={c.estado==='limitado'?'green':'amber'}>{c.estado==='limitado'?'Capacidade validada · limitada':c.estado==='sem_credencial'?'Sem credencial':c.estado==='erro'?'Erro':'Acesso não validado'}</Badge></summary><div className="ed-form"><p>{c.acesso}</p>{c.prova.mensagem&&<p role="status">{c.prova.mensagem}</p>}<p>Última execução: {c.prova.data||'Nenhuma'}. Conta: {c.prova.conta||'Não informada'}. Consumo: não informado.</p><form onSubmit={e=>{e.preventDefault();save.mutate()}}><div className="ed-form-grid">{Object.entries(c.campos).map(([key,label])=><Field key={key} label={label}>{key==='modo'||key==='tipo'?<select value={settings[key]} onChange={e=>setSettings({...settings,[key]:e.target.value})}>{(key==='modo'?['cli','token']:['r2','s3']).map(v=><option key={v}>{v}</option>)}</select>:<input maxLength={300} type={key==='base_url'?'url':'text'} value={settings[key]||''} onChange={e=>setSettings({...settings,[key]:e.target.value})}/>}</Field>)}</div>{(c.id!=='github'||settings.modo==='token')&&<Field label={'Credencial protegida · '+c.nome}><input type="password" autoComplete="new-password" maxLength={4000} value={secret} onChange={e=>setSecret(e.target.value)} placeholder="Vazio preserva a credencial"/></Field>}{c.id==='storage'&&<Field label="Access key ID protegida"><input type="password" autoComplete="new-password" value={access} onChange={e=>setAccess(e.target.value)}/></Field>}<button className="ed-button" disabled={running||save.isPending}>Salvar configuração</button></form>
 {c.prova.recursos?.length&&<Field label={'Destino disponível · '+c.nome}><select defaultValue="" onChange={e=>{const key=c.id==='github'?'repositorio':c.id==='cloudflare'?(settings.account_id?'projeto':'account_id'):c.id==='n8n'?'workflow_id':'';if(key)setSettings({...settings,[key]:e.target.value})}}><option value="">Selecione e salve a configuração</option>{c.prova.recursos.map((r,i)=><option key={r.id||i} value={c.id==='github'||c.id==='cloudflare'&&settings.account_id?r.nome:r.id||r.nome}>{r.nome}{r.modo?' · '+r.modo:''}</option>)}</select></Field>}
 <div className="ed-actions"><button className="ed-button" disabled={!c.credencial_presente||running||save.isPending||test.isPending||!!secret||!!access||JSON.stringify(settings)!==JSON.stringify(c.config)} onClick={()=>test.mutate()}>{running?'Testando…':c.id==='storage'?'Testar gravação e leitura (63 bytes)':'Testar acesso e consultar destinos'}</button>{running&&<button className="ed-button" disabled={cancel.isPending} onClick={()=>cancel.mutate()}>Cancelar teste</button>}{c.credencial_presente&&<button className="ed-button" disabled={running||remove.isPending} onClick={()=>remove.mutate()}>Remover credencial local</button>}</div>{c.id==='github'&&settings.modo==='cli'&&<small>A sessão da CLI permanece. Para renovar ou revogar essa sessão, use gh auth login/logout no terminal; não há troca automática de conta.</small>}{job.data&&<div role="status"><p>{job.data.mensagem}</p><progress aria-label={'Teste '+c.nome} value={job.data.progresso} max={100}/></div>}{[save.error,test.error,job.error,cancel.error,remove.error].filter(Boolean).map((e,i)=><Erro key={i} error={e}/>)}<External url={c.docs}>Documentação oficial</External></div></details>
}
