import {csrfHeaders} from './accessState'
import { useState } from 'react'
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query'
import type { Empresa,Material } from './types'
import { studioApi } from './studioApi'
import type { ImageVersion } from './studioApi'
import { api } from './api'
import { Field,Erro,Loading,Badge } from './shared'

export function ImageStudioPanel({empresa}:{empresa:Empresa}){
 const [selected,setSelected]=useState(empresa.materiais[0]?.id||'')
 const material=empresa.materiais.find(m=>m.id===selected)
 return <div className="ed-research"><section className="ed-panel ed-form"><div className="ed-section-title"><h2>Estúdio de imagens</h2><p>Preserve o original. Compare versões, confira identidade e autorize o uso antes de exportar.</p></div>
 <Field label="Original para preparar"><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Escolha um material</option>{empresa.materiais.map(m=><option key={m.id} value={m.id}>{m.nome_original} · {m.autorizado?'uso autorizado':'autorização pendente'}</option>)}</select></Field>
 {!empresa.materiais.length&&<p>Envie uma imagem em Materiais. Fotos remotas precisam ser importadas e ter direitos conferidos.</p>}</section>
 {material&&<ImageEditor key={material.id} company={empresa} material={material}/>}</div>
}
function ImageEditor({company,material:m}:{company:Empresa;material:Material}){
 const client=useQueryClient(),[compare,setCompare]=useState(''),[jobId,setJobId]=useState('')
 const [crop,setCrop]=useState([0,0,100,100]),[exposure,setExposure]=useState(1),[contrast,setContrast]=useState(1),[target,setTarget]=useState('desktop')
 const [nature,setNature]=useState('a_confirmar'),[instructions,setInstructions]=useState(''),[protectedRegions,setProtected]=useState<number[][]>([]),[region,setRegion]=useState([20,10,60,60]),[logo,setLogo]=useState(''),[background,setBackground]=useState('preservar')
 const query=useQuery({queryKey:['ed','imagem-studio',company.id,m.id],queryFn:()=>studioApi.image(company.id,m.id)})
 const refresh=()=>client.invalidateQueries({queryKey:['ed']})
 const edit=useMutation({mutationFn:(action:string)=>studioApi.editImage(company.id,m.id,{acao:action,recorte:crop.map(x=>x/100),exposicao:exposure,contraste:contrast,destino:target,instrucoes:instructions,natureza:nature,protegidas:protectedRegions.map(r=>r.map(x=>x/100)),logo_id:logo,fundo:background}),onSuccess:r=>{if('fornecedor'in r)setJobId(r.id);else{setCompare(r.id);refresh()}}})
 const select=useMutation({mutationFn:({id,selected}:{id:string;selected:boolean})=>studioApi.selectImage(company.id,m.id,id,selected),onSuccess:refresh})
 const job=useQuery({queryKey:['ed','operacao',jobId],queryFn:async()=>{const j=await api.operacao(jobId);if(!['na_fila','pesquisando'].includes(j.estado))refresh();return j},enabled:!!jobId,refetchInterval:q=>q.state.data&&['na_fila','pesquisando'].includes(q.state.data.estado)?1500:false})
 const cancel=useMutation({mutationFn:()=>api.cancelarOperacao(jobId),onSuccess:refresh})
 const packet=useMutation({mutationFn:async()=>{const r=await fetch(`/api/ed/empresas/${company.id}/materiais/${m.id}/studio/pacote-edicao`,{method:'POST',headers:{'Content-Type':'application/json',...csrfHeaders()},body:JSON.stringify({acao:'local',recorte:crop.map(x=>x/100),exposicao:exposure,contraste:contrast,destino:target,instrucoes:instructions,natureza:nature,protegidas:protectedRegions.map(r=>r.map(x=>x/100)),logo_id:logo,fundo:background})});if(!r.ok)throw Error((await r.json()).erro);const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download='pedido-edicao-edy.zip';a.click();URL.revokeObjectURL(url)}})
 if(query.isPending)return <Loading/>
 if(query.isError)return <Erro error={query.error}/>
 const data=query.data,version=data.versoes.find(v=>v.id===compare)||data.versoes.at(-1)
 const busy=edit.isPending||!!job.data&&['na_fila','pesquisando'].includes(job.data.estado)
 return <><section className="ed-panel ed-form"><h2>Qualidade e adequação</h2><p>{data.avaliacao.largura} × {data.avaliacao.altura} px · proporção {data.avaliacao.proporcao} · {(data.avaliacao.bytes/1024).toFixed(0)} KB</p><ul>{data.avaliacao.motivos.map(x=><li key={x}>{x}</li>)}</ul><p>{data.avaliacao.incertezas.join(' ')}</p><dl className="ed-facts">{Object.entries(data.avaliacao.adequacao).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></section>
 <section className="ed-panel ed-form"><div className="ed-panel-head"><h2>Original e versão</h2><Badge tone={m.autorizado?'green':'amber'}>{m.autorizado?'Autorização declarada':'Uso pendente'}</Badge></div><div className="ed-image-comparison"><figure><div className="ed-protection-preview"><img src={m.arquivo_url} alt={`Original: ${m.nome_original}`}/>{protectedRegions.map((r,i)=><span key={i} style={{left:r[0]+'%',top:r[1]+'%',width:r[2]+'%',height:r[3]+'%'}} aria-hidden="true"/>)}</div><figcaption>Original imutável · {data.original_sha256.slice(0,12)}</figcaption></figure><figure>{version?<><img src={version.arquivo_url} alt={`Versão preparada: ${m.nome_original}`}/><figcaption>{version.largura} × {version.altura} · {version.modelo} · {version.natureza} · {version.estado}</figcaption></>:<div className="ed-candidate-unavailable">Ainda sem versão. Prepare um recorte ou ajuste.</div>}</figure></div>
 <div className="ed-form-grid"><Field label="Comparar versão"><select value={version?.id||''} onChange={e=>setCompare(e.target.value)}><option value="">Última preparada</option>{data.versoes.map((v,i)=><option key={v.id} value={v.id}>Versão {i+1} · {v.estado} · {v.modelo}</option>)}</select></Field><Field label="Destino do recorte"><select value={target} onChange={e=>setTarget(e.target.value)}><option>desktop</option><option>mobile</option></select></Field>
 {['X (%)','Y (%)','Largura (%)','Altura (%)'].map((label,i)=><Field key={label} label={label}><input type="number" min={0} max={100} value={crop[i]} onChange={e=>setCrop(crop.map((x,n)=>n===i?Number(e.target.value):x))}/></Field>)}
 <Field label={`Exposição · ${exposure}`}><input type="range" min="0.5" max="1.5" step="0.05" value={exposure} onChange={e=>setExposure(Number(e.target.value))}/></Field><Field label={`Contraste · ${contrast}`}><input type="range" min="0.5" max="1.5" step="0.05" value={contrast} onChange={e=>setContrast(Number(e.target.value))}/></Field>
 <Field label="Natureza confirmada por você"><select value={nature} onChange={e=>setNature(e.target.value)}>{['a_confirmar','pessoa','produto','ambiente','ilustracao'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Fundo local" hint="Chave de cor clara: somente para fundos brancos uniformes; pode remover partes brancas do produto. Confira antes/depois."><select value={background} onChange={e=>setBackground(e.target.value)}><option value="preservar">Preservar</option><option value="remover_claro">Remover branco uniforme</option><option value="substituir_claro">Substituir branco por branco puro</option></select></Field>
 <Field label="Compor logo oficial" hint="Sobreposição do arquivo autorizado, sem redesenhar texto ou forma."><select value={logo} onChange={e=>setLogo(e.target.value)}><option value="">Sem composição</option>{company.materiais.filter(x=>x.id!==m.id&&x.autorizado).map(x=><option key={x.id} value={x.id}>{x.nome_original}</option>)}</select></Field></div>
 <Field label="Instruções para preparar ou refinar"><textarea value={instructions} maxLength={4000} rows={3} onChange={e=>setInstructions(e.target.value)}/></Field>
 <details><summary>Proteger regiões da pessoa, produto ou marca</summary><p>Marque rosto, cabelo, pele e contorno, ou embalagem e rótulo. Pixels originais dessas regiões são restaurados. Bordas e recortes ainda exigem revisão; não há garantia de identidade fora das regiões.</p><div className="ed-form-grid">{['Proteção X (%)','Proteção Y (%)','Proteção largura (%)','Proteção altura (%)'].map((label,i)=><Field key={label} label={label}><input type="number" min={0} max={100} value={region[i]} onChange={e=>setRegion(region.map((x,n)=>n===i?Number(e.target.value):x))}/></Field>)}</div><button className="ed-button" disabled={protectedRegions.length>=10} onClick={()=>setProtected([...protectedRegions,region])}>Adicionar região protegida</button>{protectedRegions.map((r,i)=><p key={i}>{r.join(' / ')}% <button className="ed-button" onClick={()=>setProtected(protectedRegions.filter((_,n)=>n!==i))}>Remover região {i+1}</button></p>)}</details>
 <div className="ed-form-actions"><button className="ed-button primary" disabled={busy} onClick={()=>edit.mutate('local')}>Preparar ajuste local</button><button className="ed-button" disabled={busy} onClick={()=>edit.mutate('ia')}>Editar com IA</button><button className="ed-button" disabled={!m.autorizado||select.isPending} onClick={()=>select.mutate({id:'original',selected:true})}>Usar original na exportação</button>{version&&<><button className="ed-button" disabled={!m.autorizado||select.isPending} onClick={()=>select.mutate({id:version.id,selected:true})}>Aprovar e usar versão</button><button className="ed-button" disabled={select.isPending} onClick={()=>select.mutate({id:version.id,selected:false})}>Rejeitar versão</button></>}</div>
 <button className="ed-button" disabled={!m.autorizado||packet.isPending} onClick={()=>packet.mutate()}>Exportar pedido de edição com original</button>{packet.isError&&<Erro error={packet.error}/>}<p>O pedido inclui o original e os parâmetros, marcado como não executado. Funciona sem credencial de imagens.</p><p>Versões aprovadas deste material selecionado acompanham o ZIP; rejeite alternativas que não deseja incluir. O recorte mobile aprovado pode ser usado como imagem responsiva.</p><p>Seleção atual: {data.versao_exportacao==='original'?'Original':`Versão ${data.versoes.findIndex((v:ImageVersion)=>v.id===data.versao_exportacao)+1}`}. IA usa chave e cobrança próprias. Sem acesso, nenhuma geração é simulada.</p>
 {edit.isError&&<Erro error={edit.error}/>} {select.isError&&<Erro error={select.error}/>} {cancel.isError&&<Erro error={cancel.error}/>} {job.data&&<div role="status"><p>{job.data.estado} · {job.data.mensagem}</p><progress max={100} value={job.data.progresso} aria-label="Progresso da edição"/>{busy&&<button className="ed-button" onClick={()=>cancel.mutate()}>Cancelar edição</button>}</div>}
 </section></>
}
