import {FileInput} from './shared'
import {useState,useRef,useEffect} from 'react'
import {Link,useParams} from 'react-router-dom'
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query'
import {httpClient} from '@/services/httpClient'
import {api} from './api'
import {crmApi,type CrmRecord} from './crmApi'
import {useAccess} from './accessContext'
import {csrfHeaders} from './accessState'
import {Field,Erro,Loading,Badge} from './shared'
import {date} from './domain'
import './operational.css'
import {LeadsNav} from './LeadsNav'
import {DashboardOverview} from './DashboardOverview'

const definitions:Record<string,[string,string,string][]>= {
 contato:[['nome','Nome','text'],['cargo','Cargo / associação','text'],['telefone','Telefone','text'],['email','E-mail','email'],['observacoes','Observações','textarea']],
 oportunidade:[['titulo','Título da oportunidade','text'],['fase','Fase do funil','fase'],['responsavel','Responsável','text'],['prioridade','Prioridade','prioridade'],['origem','Origem','text'],['tags','Tags separadas por vírgula','tags'],['valor','Valor estimado revisado (opcional)','text'],['motivo','Motivo de ganho, perda ou arquivamento','textarea']],
 tarefa:[['titulo','Título da tarefa','text'],['vencimento','Vencimento','date'],['responsavel','Responsável','text'],['prioridade','Prioridade','prioridade'],['observacoes','Observações da tarefa','textarea']],
 atividade:[['texto','Nota ou registro de contato','textarea'],['tipo_atividade','Tipo de atividade','text'],['canal','Canal de contato','text'],['proximo_contato','Próximo acompanhamento','date']],
 lista:[['titulo','Nome da lista','text'],['objetivo','Objetivo da campanha','textarea'],['estado_lista','Situação da lista','text']],
 visao:[['titulo','Nome da visualização','text']],
}
const names:Record<string,string>={contato:'Contato',oportunidade:'Oportunidade',tarefa:'Tarefa',atividade:'Atividade',lista:'Lista de prospecção',visao:'Visualização'}
const title=(x:CrmRecord)=>String(x.titulo||x.nome||x.texto||'Registro')

export function RecordEditor({kind,company='',record,onClose}:{kind:string;company?:string;record?:CrmRecord;onClose:()=>void}){
 const client=useQueryClient(),[data,setData]=useState<Partial<CrmRecord>>(record||{empresa_id:company||null}),[ids,setIds]=useState<string[]>((record?.empresa_ids as string[])||[])
 const companies=useQuery({queryKey:['ed','empresas'],queryFn:()=>api.empresas()})
 const stages=useQuery({queryKey:['ed','funil'],queryFn:crmApi.stages})
 const related=useQuery({queryKey:['ed','empresa',data.empresa_id],queryFn:()=>api.empresa(data.empresa_id!),enabled:kind==='oportunidade'&&!!data.empresa_id})
 const save=useMutation({mutationFn:()=>crmApi.save(kind,kind==='lista'?{...data,empresa_ids:ids}:data),onSuccess:()=>{client.invalidateQueries({queryKey:['ed']});onClose()}})
 const change=(key:string,value:unknown)=>setData({...data,[key]:value})
 return <section className="ed-panel ed-form ed-record-editor"><h2>{record?'Editar':'Criar'} {names[kind]}</h2><form onSubmit={e=>{e.preventDefault();save.mutate()}}>
 {!company&&!['lista','visao'].includes(kind)&&<Field label="Empresa relacionada"><select required={['contato','oportunidade'].includes(kind)} value={data.empresa_id||''} onChange={e=>change('empresa_id',e.target.value||null)}><option value="">Sem empresa (tarefa geral)</option>{companies.data?.map(e=><option key={e.id} value={e.id}>{e.nome}</option>)}</select></Field>}
 <div className="ed-form-grid">{definitions[kind].filter(([key])=>key!=='motivo'||['ganho','perdido'].includes(String(data.fase))).map(([key,label,type],i)=><Field key={key} label={label}>{type==='textarea'?<textarea required={i===0} rows={3} maxLength={4000} value={String(data[key]||'')} onChange={e=>change(key,e.target.value)}/>:type==='fase'||type==='prioridade'?<select value={String(data[key]|| (type==='prioridade'?'normal':stages.data?.[0]?.id||''))} onChange={e=>change(key,e.target.value)}>{(type==='fase'?stages.data||[]:[{id:'baixa',nome:'Baixa'},{id:'normal',nome:'Normal'},{id:'alta',nome:'Alta'}]).map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select>:<input required={i===0} type={type==='tags'?'text':type} maxLength={500} value={type==='tags'?(data[key] as string[]||[]).join(', '):String(data[key]||'')} onChange={e=>change(key,type==='tags'?e.target.value.split(',').map(x=>x.trim()).filter(Boolean):e.target.value)}/>}</Field>)}</div>
 {kind==='lista'&&<fieldset><legend>Empresas da lista</legend><div className="ed-company-picker">{companies.data?.map(e=><label className="ed-check" key={e.id}><input type="checkbox" checked={ids.includes(e.id)} onChange={v=>setIds(v.target.checked?[...ids,e.id]:ids.filter(id=>id!==e.id))}/>{e.nome}</label>)}</div></fieldset>}
 {kind==='oportunidade'&&related.data&&<div className="ed-form-grid"><Field label="Pacote da proposta"><select value={String(data.pacote_id||'')} onChange={e=>change('pacote_id',e.target.value)}><option value="">Ainda não associado</option>{related.data.exportacoes.map(x=><option key={x.id} value={x.id}>Pacote v{x.versao}</option>)}</select></Field><Field label="Prévia relacionada"><select value={String(data.previa_id||'')} onChange={e=>change('previa_id',e.target.value)}><option value="">Ainda não associada</option>{related.data.previas.map(x=><option key={x.id} value={x.id}>{x.url}</option>)}</select></Field></div>}
 <div className="ed-actions"><button className="ed-button primary" disabled={save.isPending}>Salvar {names[kind]}</button><button type="button" className="ed-button" onClick={onClose}>Fechar formulário</button></div>{save.isError&&<Erro error={save.error}/>}</form></section>
}

function RecordDrawer({record,onClose}:{record:CrmRecord;onClose:()=>void}){
 const ref=useRef<HTMLDialogElement>(null)
 useEffect(()=>{const element=ref.current;element?.showModal();return()=>element?.close()},[])
 return <dialog ref={ref} className="ed-record-drawer" aria-labelledby="ed-drawer-title" onCancel={onClose}><button className="ed-button" autoFocus onClick={onClose}>Fechar detalhes</button><h2 id="ed-drawer-title">{title(record)}</h2><p>{String(record.observacoes||record.objetivo||'Sem observações adicionais.')}</p><p>{record.concluida?'Concluída':'Aberta'} · {String(record.responsavel||'Responsável a definir')}</p>{record.empresa_id&&<Link to={'/empresas/'+record.empresa_id} onClick={onClose}>Ficha da empresa ↗</Link>}<RecordHistory record={record}/></dialog>
}

export function RecordsPanel({kind,company=''}:{kind:string;company?:string}){
 const client=useQueryClient(),access=useAccess(),readonly=access?.ator?.papel==='leitura',[editor,setEditor]=useState<CrmRecord|null|false>(false),[archived,setArchived]=useState(false),[page,setPage]=useState(1),[search,setSearch]=useState(''),[detail,setDetail]=useState<CrmRecord|null>(null)
 const detailTrigger=useRef<HTMLButtonElement|null>(null)
 function closeDetail(){setDetail(null);requestAnimationFrame(()=>detailTrigger.current?.focus())}
 const q=useQuery({queryKey:['ed','crm',kind,company,archived,page,search],queryFn:()=>crmApi.list(kind,company,archived,page,search)})
 const change=useMutation({mutationFn:(r:CrmRecord)=>crmApi.save(kind,r),onSuccess:()=>client.invalidateQueries({queryKey:['ed']})})
 return <section className="ed-records"><Field label={'Buscar '+names[kind]}><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></Field><label className="ed-check"><input type="checkbox" checked={archived} onChange={e=>{setArchived(e.target.checked);setPage(1)}}/> Mostrar registros arquivados</label><div className="ed-panel-head"><h2>{names[kind]}{kind!=='atividade'?'s':'s e linha do tempo'}</h2>{!readonly&&<button className="ed-button" onClick={()=>setEditor(null)}>Adicionar {names[kind]}</button>}</div>{q.isPending?<Loading/>:q.isError?<Erro error={q.error}/>:!q.data.items.length?<p className="ed-muted">Nenhum registro. {kind==='lista'?<Link to="/nova-busca">Pesquisar empresas para sua primeira lista ↗</Link>:'Adicione um registro para organizar o acompanhamento.'}</p>:q.data.items.map(r=><article key={r.id} className="ed-record-card"><div><Badge tone={r.concluida?'green':'amber'}>{String(r.prioridade||r.tipo_atividade||r.estado)} · v{r.versao}</Badge><h3>{title(r)}</h3><p>{String(r.observacoes||r.objetivo||r.cargo||'')}</p>{Boolean(r.vencimento)&&<small>Vencimento: {String(r.vencimento)} · {r.concluida?'Concluída':'Aberta'}</small>}{Boolean(r.telefone)&&<p>{String(r.telefone)}</p>}{Boolean(r.email)&&<p>{String(r.email)}</p>}{r.empresa_id&&!company&&<Link to={'/empresas/'+r.empresa_id}>Abrir empresa ↗</Link>}<small>{date(r.atualizado_em)} · registro do workspace</small><button className="ed-text-button" onClick={e=>{detailTrigger.current=e.currentTarget;setDetail(r)}}>Ver detalhes e histórico</button></div>{!readonly&&<div className="ed-actions"><button className="ed-button" onClick={()=>setEditor(r)}>Editar</button>{kind==='tarefa'&&<button className="ed-button" disabled={change.isPending} onClick={()=>change.mutate({...r,concluida:!r.concluida})}>{r.concluida?'Reabrir tarefa':'Concluir tarefa'}</button>}<button className="ed-button" disabled={change.isPending} onClick={()=>change.mutate({...r,estado:r.estado==='arquivado'?'ativo':'arquivado'})}>{r.estado==='arquivado'?'Restaurar registro':'Arquivar registro'}</button></div>}</article>)}{q.data&&<PageControls data={q.data} onPage={setPage}/>} {editor!==false&&<RecordEditor key={editor?.id||'new'} kind={kind} company={company} record={editor||undefined} onClose={()=>setEditor(false)}/>} {detail&&<RecordDrawer record={detail} onClose={closeDetail}/>} {change.isError&&<Erro error={change.error}/>}</section>
}

function Pipeline(){
 const client=useQueryClient(),[editor,setEditor]=useState<CrmRecord|null|false>(false),[drag,setDrag]=useState(''),[view,setView]=useState('kanban'),[page,setPage]=useState(1),[search,setSearch]=useState(''),[reason,setReason]=useState(''),[stageText,setStageText]=useState(''),readonly=useAccess()?.ator?.papel==='leitura'
 const stages=useQuery({queryKey:['ed','funil'],queryFn:crmApi.stages}),records=useQuery({queryKey:['ed','crm','oportunidade','',page,search],queryFn:()=>crmApi.list('oportunidade','',false,page,search)})
 const [transition,setTransition]=useState<{record:CrmRecord;fase:string}|null>(null)
 const move=useMutation({mutationFn:({record,fase}:{record:CrmRecord;fase:string})=>crmApi.save('oportunidade',{...record,fase,motivo:['ganho','perdido'].includes(fase)?reason:record.motivo}),onSuccess:()=>{setTransition(null);setReason('');client.invalidateQueries({queryKey:['ed']})}})
 function requestMove(record:CrmRecord,fase:string){if(['ganho','perdido'].includes(fase)){setReason('');setTransition({record,fase})}else move.mutate({record,fase})}
 const configure=useMutation({mutationFn:()=>httpClient.put('/api/ed/crm/funil',JSON.parse(stageText)),onSuccess:()=>client.invalidateQueries({queryKey:['ed','funil']})})
 return <><div className="ed-panel-head"><h2>Funil de oportunidades</h2><button className="ed-button" onClick={()=>setView(view==='kanban'?'tabela':'kanban')}>{view==='kanban'?'Ver em tabela':'Ver em Kanban'}</button>{!readonly&&<button className="ed-button primary" onClick={()=>setEditor(null)}>Nova oportunidade</button>}</div><Field label="Buscar oportunidades"><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></Field>{view==='kanban'?<div className="ed-kanban" aria-label="Kanban de oportunidades">{stages.data?.map(s=><section key={s.id} onDragOver={e=>e.preventDefault()} onDrop={()=>{const r=records.data?.items.find(x=>x.id===drag);if(r&&!readonly)requestMove(r,s.id);setDrag('')}}><h3>{s.nome} <span>{records.data?.items.filter(x=>x.fase===s.id).length||0}</span></h3>{records.data?.items.filter(x=>x.fase===s.id).map(r=><article key={r.id} draggable={!readonly} onDragStart={()=>setDrag(r.id)} className="ed-opportunity"><Badge tone="amber">{String(r.prioridade)} · v{r.versao}</Badge><h4>{title(r)}</h4><p>{String(r.responsavel||'Responsável a definir')}</p><p>{(r.tags as string[]).join(' · ')}</p><Link to={'/empresas/'+r.empresa_id}>Ficha da empresa ↗</Link><Field label={'Mover '+title(r)}><select disabled={readonly||move.isPending} value={String(r.fase)} onChange={e=>requestMove(r,e.target.value)}>{stages.data?.map(k=><option key={k.id} value={k.id}>{k.nome}</option>)}</select></Field>{!readonly&&<button className="ed-button" onClick={()=>setEditor(r)}>Editar oportunidade</button>}</article>)}</section>)}</div>:<div className="ed-table-wrap"><table className="ed-table"><caption>Oportunidades · registros deste workspace</caption><thead><tr><th>Proposta / empresa</th><th>Responsável</th><th>Prioridade / tags</th><th>Fase</th><th>Ação</th></tr></thead><tbody>{records.data?.items.map(r=><tr key={r.id}><td><strong>{title(r)}</strong><Link to={'/empresas/'+r.empresa_id}>Ficha da empresa ↗</Link></td><td>{String(r.responsavel||'A definir')}</td><td>{String(r.prioridade)}<small>{(r.tags as string[]).join(' · ')}</small></td><td><Field label={'Mover '+title(r)}><select disabled={readonly||move.isPending} value={String(r.fase)} onChange={e=>requestMove(r,e.target.value)}>{stages.data?.map(k=><option key={k.id} value={k.id}>{k.nome}</option>)}</select></Field></td><td>{!readonly&&<button className="ed-button" onClick={()=>setEditor(r)}>Editar oportunidade</button>}</td></tr>)}</tbody></table></div>}{records.data&&<PageControls data={records.data} onPage={setPage}/>}
 {transition&&<section className="ed-panel ed-form" role="region" aria-label="Concluir oportunidade"><h2>{transition.fase==='ganho'?'Registrar ganho':'Registrar perda'}</h2><p>{title(transition.record)} · a fase atual permanece até você confirmar.</p><form onSubmit={e=>{e.preventDefault();move.mutate(transition)}}><Field label="Motivo da conclusão"><textarea autoFocus required maxLength={4000} value={reason} onChange={e=>setReason(e.target.value)}/></Field><div className="ed-actions"><button className="ed-button primary" disabled={move.isPending||!reason.trim()}>Confirmar conclusão</button><button className="ed-button" type="button" onClick={()=>setTransition(null)}>Cancelar alteração</button></div></form></section>}{editor!==false&&<RecordEditor kind="oportunidade" record={editor||undefined} onClose={()=>setEditor(false)}/>}{move.isError&&<Erro error={move.error}/>} {records.isError&&<Erro error={records.error}/>}
 {!readonly&&<details><summary>Configurar fases do funil</summary><p>IDs usados por oportunidades precisam permanecer. Editar os nomes preserva os registros.</p><Field label="Fases em JSON"><textarea rows={6} value={stageText||JSON.stringify(stages.data,null,2)||''} onChange={e=>setStageText(e.target.value)}/></Field><button className="ed-button" onClick={()=>configure.mutate()}>Salvar fases</button>{configure.isError&&<Erro error={configure.error}/>}</details>}</>
}

function Dashboard(){
 return <><DashboardOverview/><RecordsPanel kind="tarefa"/></>
}

function CsvPanel(){
 const client=useQueryClient(),[preview,setPreview]=useState<{id:string;linhas:{linha:number;dados:{nome:string};erro:string}[];validas:number}|null>(null),[chosen,setChosen]=useState<number[]>([]),[error,setError]=useState('')
 const [file,setFile]=useState<File|null>(null),[columns,setColumns]=useState<string[]>([]),[fields,setFields]=useState<string[]>([]),[mapping,setMapping]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false)
 async function upload(source:File,analyze=true){setBusy(true);setError('');setPreview(null);save.reset();try{const data=new FormData();data.set('arquivo',source);if(analyze)data.set('analisar','true');else data.set('mapeamento',JSON.stringify(mapping));const r=await fetch('/api/ed/crm/csv/validar',{method:'POST',headers:csrfHeaders(),body:data});const value=await r.json();if(!r.ok)throw Error(value.erro);if(analyze){setFile(source);setColumns(value.cabecalhos);setFields(value.campos);setMapping(Object.fromEntries(value.cabecalhos.map((x:string)=>[x,value.campos.includes(x)?x:''])))}else{setPreview(value);setChosen(value.linhas.filter((x:{erro:string})=>!x.erro).map((x:{linha:number})=>x.linha))}}catch(e){setError(String(e))}finally{setBusy(false)}}

 const save=useMutation({mutationFn:()=>httpClient.post('/api/ed/crm/csv/importar',{id:preview?.id,linhas:chosen}),onSuccess:()=>client.invalidateQueries({queryKey:['ed']})})
 return <section className="ed-panel ed-form"><h2>Importação e exportação CSV</h2><p>CSV UTF-8 com vírgula ou ponto e vírgula. Associe as colunas aos campos da ficha. Até 500 linhas; dados entram pendentes de revisão. Repetir o mesmo arquivo não cria novas empresas.</p><a className="ed-button" href="/api/ed/crm/csv">Exportar empresas do workspace</a><Field label="CSV para revisar"><FileInput accept=".csv" onChange={e=>{if(e.target.files?.[0])void upload(e.target.files[0])}}/></Field>{columns.length>0&&<><h3>Associar colunas</h3><div className="ed-form-grid">{columns.map(c=><Field key={c} label={'Coluna: '+c}><select value={mapping[c]||''} onChange={e=>{setMapping({...mapping,[c]:e.target.value});setPreview(null);save.reset()}}><option value="">Ignorar esta coluna</option>{fields.map(f=><option key={f}>{f}</option>)}</select></Field>)}</div><button className="ed-button" disabled={busy||!file} onClick={()=>{if(file)void upload(file,false)}}>{busy?'Validando…':'Revisar linhas mapeadas'}</button></>}<details><summary>Exemplo de arquivo</summary><pre>nome,cidade,uf,telefone{String.fromCharCode(10)}Empresa fictícia de exemplo,Recife,PE,</pre><p>Exemplo demonstrativo. Não representa um estabelecimento real.</p></details>{preview&&<><p>{preview.validas} linha(s) válidas.</p><div className="ed-table-wrap"><table className="ed-table"><thead><tr><th>Importar</th><th>Linha</th><th>Empresa</th><th>Diagnóstico</th></tr></thead><tbody>{preview.linhas.map(r=><tr key={r.linha}><td><input type="checkbox" aria-label={'Importar linha '+r.linha} disabled={!!r.erro} checked={chosen.includes(r.linha)} onChange={e=>setChosen(e.target.checked?[...chosen,r.linha]:chosen.filter(x=>x!==r.linha))}/></td><td>{r.linha}</td><td>{r.dados.nome}</td><td>{r.erro||'Válida · revisar associação'}</td></tr>)}</tbody></table></div><button className="ed-button primary" disabled={!chosen.length||save.isPending} onClick={()=>save.mutate()}>Importar linhas revisadas</button></>}{save.isSuccess&&<p role="status">Importação persistida.</p>}{save.isError&&<Erro error={save.error}/>} {error&&<p role="alert">{error}</p>}</section>
}

export function MergePanel(){
 const client=useQueryClient(),[source,setSource]=useState(''),[target,setTarget]=useState(''),[chosen,setChosen]=useState<string[]>([])
 const companies=useQuery({queryKey:['ed','empresas'],queryFn:()=>api.empresas()}),history=useQuery({queryKey:['ed','unioes'],queryFn:()=>httpClient.get<{id:string;origem:string;destino:string;estado:string}[]>('/api/ed/crm/unioes')})
 const preview=useMutation({mutationFn:()=>httpClient.post<{revisao:string;conflitos:{campo:string;origem:string;destino:string}[]}>('/api/ed/crm/unioes/avaliar',{origem:source,destino:target}),onSuccess:()=>setChosen([])})
 const merge=useMutation({mutationFn:()=>httpClient.post('/api/ed/crm/unioes',{origem:source,destino:target,revisao:preview.data?.revisao,preferir_origem:chosen}),onSuccess:()=>{preview.reset();client.invalidateQueries({queryKey:['ed']})}})
 const restore=useMutation({mutationFn:(id:string)=>httpClient.post('/api/ed/crm/unioes/'+id+'/restaurar'),onSuccess:()=>client.invalidateQueries({queryKey:['ed']})})
 return <section className="ed-panel ed-form"><h2>União revisável de duplicatas</h2><p>Campos vazios do destino podem ser preenchidos. Conflitos exigem escolha. Materiais, pacotes e versões permanecem vinculados na ficha de origem; nenhuma imagem é apagada.</p><div className="ed-form-grid">{[['Origem a unir',source,setSource],['Destino preservado',target,setTarget]].map(([label,value,set])=><Field key={String(label)} label={String(label)}><select value={String(value)} onChange={e=>{(set as (s:string)=>void)(e.target.value);preview.reset()}}><option value="">Escolha empresa</option>{companies.data?.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select></Field>)}</div><button className="ed-button" disabled={!source||!target||source===target||preview.isPending} onClick={()=>preview.mutate()}>Revisar união</button>{preview.data&&<><h3>Conflitos · mantenha destino ou prefira origem</h3>{preview.data.conflitos.map(c=><label className="ed-context-option" key={c.campo}><input type="checkbox" checked={chosen.includes(c.campo)} onChange={e=>setChosen(e.target.checked?[...chosen,c.campo]:chosen.filter(k=>k!==c.campo))}/><span>{c.campo}: destino “{c.destino}”; preferir origem “{c.origem}”</span></label>)}<button className="ed-button primary" disabled={merge.isPending} onClick={()=>merge.mutate()}>Aplicar união revisada</button></>}{history.data?.map(h=><p key={h.id}>{h.estado} · <Link to={'/empresas/'+h.destino}>Destino ↗</Link> · <Link to={'/empresas/'+h.origem}>Histórico de origem ↗</Link>{h.estado==='aplicada'&&<button className="ed-button" disabled={restore.isPending} onClick={()=>restore.mutate(h.id)}>Restaurar união</button>}</p>)}{[preview.error,merge.error,restore.error].filter(Boolean).map((e,i)=><Erro key={i} error={e}/>)}</section>
}

export function LeadOperationsPanel({company}:{company:string}){return <div className="ed-research"><RecordsPanel kind="contato" company={company}/><RecordsPanel kind="oportunidade" company={company}/><RecordsPanel kind="tarefa" company={company}/><RecordsPanel kind="atividade" company={company}/></div>}
export function OperationalPage(){
 const {area='dashboard'}=useParams()
 return <><div className="ed-page-head"><div><span className="ed-eyebrow">OPERAÇÃO DO WORKSPACE</span><h1>{({dashboard:'Visão do trabalho',funil:'Funil',tarefas:'Tarefas',listas:'Listas',csv:'Importar e revisar',contatos:'Contatos'} as Record<string,string>)[area]||'Leads'}</h1><p>Oportunidades, tarefas e acompanhamento ligados aos registros reais.</p></div></div><LeadsNav/><div className="ed-research">{area==='dashboard'?<Dashboard/>:area==='funil'?<Pipeline/>:area==='contatos'?<RecordsPanel kind="contato"/>:area==='tarefas'?<RecordsPanel kind="tarefa"/>:area==='listas'?<RecordsPanel kind="lista"/>:area==='csv'?<><CsvPanel/><details><summary>Comparar e unir duplicatas</summary><MergePanel/></details></>:<p>Área não encontrada.</p>}</div></>
}

function PageControls({data,onPage}:{data:{total:number;pagina:number;limite:number};onPage:(n:number)=>void}){if(data.total<=data.limite)return null;return <div className="ed-actions"><small>{data.total} registros · página {data.pagina} de {Math.max(1,Math.ceil(data.total/data.limite))}</small><button className="ed-button" disabled={data.pagina<=1} onClick={()=>onPage(data.pagina-1)}>Anterior</button><button className="ed-button" disabled={data.pagina*data.limite>=data.total} onClick={()=>onPage(data.pagina+1)}>Próxima</button></div>}
function RecordHistory({record}:{record:CrmRecord}){const [open,setOpen]=useState(false),q=useQuery({queryKey:['ed','registro-versoes',record.id,record.versao],queryFn:()=>httpClient.get<CrmRecord[]>('/api/ed/crm/registros/'+record.tipo+'/'+record.id+'/versoes'),enabled:open});return <details onToggle={e=>setOpen(e.currentTarget.open)}><summary>Histórico de versões</summary>{q.isPending&&open?<Loading/>:q.isError?<Erro error={q.error}/>:q.data?.map(v=><p key={v.versao}>v{v.versao} · {date(v.atualizado_em)} · {title(v)} · {String(v.fase||v.estado)}{v.concluida?' · concluída':''}</p>)}</details>}
