import { useState } from 'react'
import { useQuery,useMutation,useQueryClient } from '@tanstack/react-query'
import { httpClient } from '@/services/httpClient'
import { api } from './api'
import type { Empresa } from './types'
import type { Operation } from './preparationTypes'
import { Field,Erro,External,Badge } from './shared'
interface Project extends Operation {resultado?:{modo:string;modulos:string[]};parametros:{exportacao_id:string;modo:string};criado_em:string}
const active=(j:Project)=>['na_fila','pesquisando'].includes(j.estado)
export function ProjectPanel({empresa}:{empresa:Empresa}){
 const root=`/api/ed/empresas/${empresa.id}/projetos`,client=useQueryClient(),[mode,setMode]=useState('previa'),[modules,setModules]=useState(['catalogo','contatos','uploads']),[exportId,setExport]=useState(empresa.exportacoes[0]?.id||''),[urls,setUrls]=useState<Record<string,string>>({})
 const q=useQuery({queryKey:['ed','projetos',empresa.id],queryFn:()=>httpClient.get<Project[]>(root),refetchInterval:q=>q.state.data?.some(active)?1200:false})
 const create=useMutation({mutationFn:()=>httpClient.post<Project>(root,{modo:mode,modulos:modules,exportacao_id:exportId}),onSuccess:()=>client.invalidateQueries({queryKey:['ed','projetos',empresa.id]})})
 const open=useMutation({mutationFn:(id:string)=>httpClient.post<{url:string}>(root+'/'+id+'/abrir'),onSuccess:(d,id)=>{setUrls({...urls,[id]:d.url});client.invalidateQueries({queryKey:['ed','empresa',empresa.id]})}})
 const cancel=useMutation({mutationFn:api.cancelarOperacao,onSuccess:()=>client.invalidateQueries({queryKey:['ed','projetos',empresa.id]})})
 return <section className="ed-panel ed-form"><div className="ed-panel-head"><div><h2>Construção local executável</h2><p>Use o pacote revisado para construir sem IA. O Codex integrado permanece disponível abaixo para geração e refinamento.</p></div><Badge tone="amber">Templates locais · sem inferência IA</Badge></div><div className="ed-form-grid"><Field label="Modo de construção local"><select value={mode} onChange={e=>setMode(e.target.value)}><option value="previa">Prévia de prospecção</option><option value="site">Site institucional · páginas + formulário local</option><option value="aplicacao">Aplicação · site + banco + administração</option></select></Field><Field label="Pacote revisado para o projeto"><select value={exportId} onChange={e=>setExport(e.target.value)}><option value="">Exporte primeiro</option>{empresa.exportacoes.map(x=><option key={x.id} value={x.id}>v{x.versao} · {x.id.slice(0,8)}</option>)}</select></Field></div>
 {mode==='aplicacao'&&<div><h3>Módulos funcionais disponíveis</h3><div className="ed-actions">{['catalogo','contatos','uploads'].map(k=><label key={k} className="ed-check"><input type="checkbox" checked={modules.includes(k)} onChange={e=>setModules(e.target.checked?[...modules,k]:modules.filter(x=>x!==k))}/>{k}</label>)}</div><p>Login, papéis administrador/editor, CRUD, upload e SQLite próprios. Dados locais são demonstrativos; pagamentos, estoque e agenda dependem de módulos futuros.</p></div>}
 <button className="ed-button primary" disabled={!exportId||create.isPending||q.data?.some(active)} onClick={()=>create.mutate()}>Construir projeto local</button>{create.isError&&<Erro error={create.error}/>} {open.isError&&<Erro error={open.error}/>} {cancel.isError&&<Erro error={cancel.error}/>} {q.isError&&<Erro error={q.error}/>}
 {q.data?.map(j=><article key={j.id}><strong>{j.parametros.modo} · {j.estado}</strong><p role="status">{j.mensagem}</p>{active(j)?<><progress value={j.progresso} max={100} aria-label="Construção do projeto"/><button className="ed-button" onClick={()=>cancel.mutate(j.id)}>Cancelar projeto</button></>:j.estado==='concluida'?<div className="ed-actions"><button className="ed-button" disabled={open.isPending} onClick={()=>open.mutate(j.id)}>Abrir servidor separado</button><a className="ed-button" href={root+'/'+j.id+'/zip'}>ZIP executável</a>{urls[j.id]&&<External url={urls[j.id]}>Ver projeto local</External>}</div>:<button className="ed-button" onClick={()=>{setMode(j.parametros.modo);setExport(j.parametros.exportacao_id)}}>Recuperar parâmetros para nova tentativa</button>}</article>)}
 <small>Extraia o ZIP em outra pasta e siga INICIAR.md. Dados, login e segredos do CRM não acompanham o projeto. Publicação é uma etapa posterior.</small></section>
}
