import {useState} from 'react'
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query'
import {httpClient} from '@/services/httpClient'
import {api} from './api'
import {Field,Erro} from './shared'
import {useAccess} from './accessContext'
import {useCreationMode} from './useCreationMode'
import {WorkflowCard} from './WorkflowCard'
interface Routine{id:string;nome:string;ativo:boolean;intervalo_minutos:number;plano:Record<string,unknown>;condicao:string;ultima_execucao?:string;erro?:string}
export function RoutinesPanel(){
 const client=useQueryClient(),readonly=useAccess()?.ator?.papel==='leitura'
 const [name,setName]=useState(''),[interval,setInterval]=useState(1440),[action,setAction]=useState('consultar')
 const [company,setCompany]=useState(''),[niche,setNiche]=useState('Academias'),[city,setCity]=useState(''),[uf,setUf]=useState('PE'),[amount,setAmount]=useState(2)
 const {generation,setGeneration}=useCreationMode()
 const q=useQuery({queryKey:['ed','rotinas'],queryFn:()=>httpClient.get<Routine[]>('/api/ed/rotinas')})
 const companies=useQuery({queryKey:['ed','empresas'],queryFn:()=>api.empresas()}),config=useQuery({queryKey:['ed','config'],queryFn:api.config})
 const plan=action==='consultar'?{acao:'consultar',sem_site:true}:action==='preparar'?{acao:'preparar',empresa_id:company,geracao:generation,modo:'automatico'}:{acao:'pesquisar',nicho:niche,cidade:city,uf,quantidade:amount,geracao:generation,modo:'automatico',objetivo:'Prévia de prospecção com revisão de fatos e direitos.'}
 const save=useMutation({mutationFn:(old?:Routine)=>old?httpClient.put('/api/ed/rotinas/'+old.id,{nome:old.nome,intervalo_minutos:old.intervalo_minutos,plano:old.plano,condicao:old.condicao,ativo:!old.ativo}):httpClient.post('/api/ed/rotinas',{nome:name,intervalo_minutos:interval,plano:plan,condicao:'sem_execucao_ativa',ativo:true}),onSuccess:()=>client.invalidateQueries({queryKey:['ed','rotinas']})})
 return <section className="ed-panel ed-form"><h2>Seu próximo trabalho, programado</h2><p>Rotinas funcionam enquanto o CRM e o computador estiverem ligados. Resultados ficam no histórico; mensagens comerciais não são enviadas.</p>
 <form className="ed-routine-builder" onSubmit={e=>{e.preventDefault();save.mutate(undefined)}}><Field label="Nome da rotina"><input required maxLength={120} placeholder="Ex.: Revisar empresas sem site" value={name} onChange={e=>setName(e.target.value)}/></Field>
 <div className="ed-form-grid"><Field label="Quando"><select value={interval} onChange={e=>setInterval(Number(e.target.value))}><option value={60}>A cada hora</option><option value={360}>A cada 6 horas</option><option value={1440}>Uma vez ao dia</option><option value={10080}>Uma vez por semana</option></select></Field><Field label="Fazer"><select value={action} onChange={e=>setAction(e.target.value)}><option value="consultar">Listar leads sem site informado</option><option value="pesquisar">Pesquisar empresas e preparar uma prévia</option><option value="preparar">Preparar a prévia de um lead</option></select></Field></div>
 {action==='preparar'&&<Field label="Empresa"><select required value={company} onChange={e=>setCompany(e.target.value)}><option value="">Escolha o lead</option>{companies.data?.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select></Field>}
 {action==='pesquisar'&&<div className="ed-form-grid"><Field label="Nicho"><select value={niche} onChange={e=>setNiche(e.target.value)}>{(config.data?.nichos||['Academias']).map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Cidade"><input required maxLength={120} value={city} onChange={e=>setCity(e.target.value)}/></Field><Field label="UF"><select value={uf} onChange={e=>setUf(e.target.value)}>{'AC AL AP AM BA CE DF ES GO MA MT MS MG PA PB PR PE PI RJ RN RS RO RR SC SP SE TO'.split(' ').map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Limite de leads"><input required type="number" min={1} max={5} value={amount} onChange={e=>setAmount(Number(e.target.value))}/></Field></div>}
 {action!=='consultar'&&<Field label="Criar usando"><select value={generation} onChange={e=>setGeneration(e.target.value)}><option value="codex_nativo">Codex nativo · plano ChatGPT</option><option value="templates">Montagem rápida · template local</option></select></Field>}
 <p className="ed-muted">Uma execução por vez{action!=='consultar'?' · até uma prévia por ocorrência':''}. A conta e a rota selecionadas são mantidas; falhas ficam para revisão.</p><details><summary>Detalhes da ação e limites</summary><pre>{JSON.stringify(plan,null,2)}</pre><small>Contrato gerado pelo formulário e validado no servidor.</small></details><button className="ed-button primary" disabled={readonly||save.isPending}>Salvar e ativar rotina</button></form>
 {q.isError&&<Erro error={q.error}/>} {!q.isPending&&!q.data?.length&&<p className="ed-muted">Nenhuma rotina criada. Comece com uma consulta de leads.</p>}{q.data?.map(r=><article className="ed-record-card" key={r.id}><div><h3>{r.nome}</h3><small>{r.ativo?'Ativa':'Pausada'} · a cada {r.intervalo_minutos>=1440?r.intervalo_minutos/1440+' dia(s)':r.intervalo_minutos+' minutos'}{r.erro?' · '+r.erro:''}</small><details><summary>Última execução e ação</summary><pre>{JSON.stringify(r.plano,null,2)}</pre>{r.ultima_execucao&&<WorkflowCard id={r.ultima_execucao}/>}</details></div><button className="ed-button" disabled={readonly||save.isPending} onClick={()=>save.mutate(r)}>{r.ativo?'Pausar rotina':'Ativar rotina'}</button></article>)}{save.isError&&<Erro error={save.error}/>} {save.isSuccess&&<p role="status">Rotina salva.</p>}</section>
}
