import { useEffect, useState } from 'react'
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query'
import { httpClient } from '@/services/httpClient'
import { api } from './api'
import type { Empresa } from './types'
import type { Operation } from './preparationTypes'
import { Badge,Erro,Field,External } from './shared'
import { date } from './domain'
import {NativeFollowControl} from './NativeFollowControl'

interface Diagnostic {categoria:string;http_status?:number;request_id?:string;codigo?:unknown;erro:unknown}
interface RuntimeInfo {versao?:string;provider?:string;endpoint?:string}
interface RuntimeStatus {
 estado:string;mensagem:string;data?:string;modo?:string;runtime?:RuntimeInfo;diagnostico?:Diagnostic;
 conta?:{rotulo:string;identificador:string;workspace?:string};modelos?:string[];origem_catalogo?:string;
 conta_nativa_selecionada?:{rotulo:string;identificador:string};
 modelos_detalhados?:{slug:string;display_name:string}[];
 acessos_modelos?:{modo:string;modelo:string;conta:string;estado:string;data:string}[];
 oauth?:{estado:string;selecionada:string|null;contas:{id:string;rotulo:string}[]}
}
interface Build extends Operation {
 tipo:string;criado_em:string;parametros:{exportacao_id?:string;modo?:string;modelo?:string;instrucoes?:string;anterior?:string};diagnostico?:Diagnostic;runtime?:RuntimeInfo;
 resultado?:{contexto_snapshot?:{id:string;versao:number;tipo:string;sha256:string}[];arquivos?:string[];pendencias?:string[];resposta?:string;consumo?:Record<string,number>}
}
const states:Record<string,string>={listado:'Modelo listado',acesso_nao_validado:'Acesso ainda não validado',execucao_concluida:'Execução concluída',modelo_recusado:'Modelo recusado',autenticacao:'Falha de autenticação',permissao:'Falha de permissão',servico:'Falha de serviço',incompleta:'Resposta incompleta',interrompida:'Interrompida',configuracao:'Configuração pendente'}
function Modes(){return <><option value="plano">ChatGPT · autenticação nativa da CLI</option><option value="oauth_plano">ChatGPT · OAuth autorizado para EDY CRM</option><option value="api">API key · cobrança separada</option></>}
function Details({value}:{value:Diagnostic}){return <details className="ed-runtime-details"><summary>{states[value.categoria]||value.categoria}{value.http_status?` · HTTP ${value.http_status}`:''}</summary><p>Request ID: {value.request_id||'Não informado pelo fornecedor'}. Código: {JSON.stringify(value.codigo)||'Não informado'}.</p><pre>{JSON.stringify(value.erro,null,2)}</pre><p>Revise conta, modo e modelo, teste novamente ou escolha explicitamente outra alternativa. Briefing, composição e versões anteriores permanecem disponíveis.</p></details>}
export function RuntimeCard({modo,onMode}:{modo?:string;onMode?:(mode:string)=>void}){
 const client=useQueryClient(),[localMode,setMode]=useState('plano'),[authUrl,setAuthUrl]=useState(''),mode=modo||localMode
 const query=useQuery({queryKey:['ed','runtime'],queryFn:()=>httpClient.get<RuntimeStatus>('/api/ed/runtime')})
 const refresh=()=>client.invalidateQueries({queryKey:['ed','runtime']})
 const test=useMutation({mutationFn:()=>httpClient.post('/api/ed/runtime/testar',{modo:mode}),onSuccess:refresh})
 const auth=useMutation({mutationFn:()=>httpClient.post<{url:string}>('/api/ed/runtime/oauth/iniciar',{}),onSuccess:r=>setAuthUrl(r.url)})
 const select=useMutation({mutationFn:(conta:string)=>httpClient.post('/api/ed/runtime/oauth/selecionar',{conta}),onSuccess:refresh})
 const d=query.data
 return <section className="ed-panel ed-form"><div className="ed-panel-head"><h2>Codex app-server</h2><Badge tone={d?.estado==='conectado'?'green':'amber'}>{d?.estado||'Teste pendente'}</Badge></div><p>Geração em workspace separado, com streaming até a conclusão. Autenticação e catálogo válidos ainda exigem teste real de inferência.</p>
 <Field label="Modo para testar autenticação"><select value={mode} onChange={e=>(onMode||setMode)(e.target.value)}><Modes/></select></Field>
 {mode==='oauth_plano'&&<div className="ed-form"><p>OAuth do CRM: {d?.oauth?.estado||'Sem autorização'}. Exige consentimento próprio para consumir o plano; o login nativo permanece separado.</p>{!!d?.oauth?.contas.length&&<Field label="Conta OAuth selecionada"><select value={d.oauth.selecionada||''} disabled={select.isPending} onChange={e=>select.mutate(e.target.value)}><option value="" disabled>Selecione uma conta</option>{d.oauth.contas.map(a=><option key={a.id} value={a.id}>{a.rotulo} · {a.id.slice(0,6)}</option>)}</select></Field>}<button className="ed-button" disabled={auth.isPending} onClick={()=>auth.mutate()}>Autorizar EDY CRM pelo ChatGPT</button>{authUrl&&<External url={authUrl}>Continuar na página oficial de autorização</External>}<small>Depois da autorização, volte e teste a conexão. Nenhum fallback para API key.</small></div>}
 <NativeFollowControl/><button className="ed-button" disabled={test.isPending} onClick={()=>test.mutate()}>{test.isPending?'Conferindo autenticação…':'Testar app-server'}</button>
 {d&&<><p role="status">{d.mensagem}</p><small>{d.data&&date(d.data)} · modo do último diagnóstico: {d.modo||'Não registrado'}</small><p>Conta: {d.conta?.rotulo||'Não validada'}{d.conta?.workspace&&` · workspace ${d.conta.workspace}`}</p><details><summary>Runtime e catálogo · detalhes técnicos</summary><p>Runtime: {d.runtime?.versao||'Não inspecionado'} · provider {d.runtime?.provider||'Não inspecionado'}. {d.runtime?.endpoint}</p><p>Catálogo: {d.modelos?.join(', ')||'Não consultado'}. {d.origem_catalogo||'Não comprova acesso ao modelo.'}</p>{d.diagnostico&&<Details value={d.diagnostico}/>}</details></>}
 {test.isError&&<Erro error={test.error}/>} {auth.isError&&<Erro error={auth.error}/>} {select.isError&&<Erro error={select.error}/>} {query.isError&&<Erro error={query.error}/>}<p>API exige ED_CRM_CODEX_API_KEY no backend e usa cobrança separada, somente quando escolhida. Exportação e montagem local continuam disponíveis.</p><External url="https://learn.chatgpt.com/docs/app-server">Protocolo oficial</External></section>
}
export function RuntimePanel({empresa}:{empresa:Empresa}){
 const client=useQueryClient(),root=`/api/ed/empresas/${empresa.id}/construcoes`
 const [exportId,setExportId]=useState(empresa.exportacoes[0]?.id||''),[mode,setMode]=useState('plano'),[model,setModel]=useState('gpt-6.1-sol'),[instructions,setInstructions]=useState(''),[previous,setPrevious]=useState(''),[url,setUrl]=useState('')
 const q=useQuery({queryKey:['ed','construcoes',empresa.id],queryFn:()=>httpClient.get<Build[]>(root),refetchInterval:q=>q.state.data?.some(j=>['na_fila','pesquisando'].includes(j.estado))?1500:false})
 useEffect(()=>{if(q.data?.length&&!q.data.some(j=>['na_fila','pesquisando'].includes(j.estado)))void client.invalidateQueries({queryKey:['ed','runtime']})},[q.data,client])
 const runtime=useQuery({queryKey:['ed','runtime'],queryFn:()=>httpClient.get<RuntimeStatus>('/api/ed/runtime')})
 const refresh=()=>client.invalidateQueries({queryKey:['ed']})
 const build=useMutation({mutationFn:(engine:string)=>engine==='local'?httpClient.post<Build>(root+'/local',{exportacao_id:exportId}):engine==='teste'?httpClient.post<Build>(root+'/teste',{modo:mode,modelo:model}):httpClient.post<Build>(root,{exportacao_id:exportId,modo:mode,modelo:model,instrucoes:instructions,anterior:previous}),onSuccess:refresh})
 const open=useMutation({mutationFn:(id:string)=>httpClient.post<{url:string}>(root+'/'+id+'/abrir',{}),onSuccess:r=>{setUrl(r.url);refresh()}})
 const cancel=useMutation({mutationFn:(id:string)=>api.cancelarOperacao(id),onSuccess:refresh})
 const busy=q.data?.some(j=>['na_fila','pesquisando'].includes(j.estado))
 const recover=(j:Build)=>{setExportId(j.parametros.exportacao_id||exportId);setMode(j.parametros.modo||mode);setModel(j.parametros.modelo||model);setInstructions(j.parametros.instrucoes||'');setPrevious(j.parametros.anterior||'')}
 const account=mode==='oauth_plano'?runtime.data?.oauth?.selecionada:mode==='plano'?runtime.data?.conta_nativa_selecionada?.identificador:runtime.data?.modo===mode?runtime.data?.conta?.identificador:null
 const access=runtime.data?.acessos_modelos?.find(a=>a.modo===mode&&a.modelo===model&&a.conta===account)
 const entries=runtime.data?.modo===mode&&(mode!=='oauth_plano'||runtime.data.conta?.identificador===account)?runtime.data.modelos_detalhados||[]:[]
 return <div className="ed-research"><section className="ed-panel ed-form"><h2>Construir e refinar a prévia</h2><p>Primeiro teste uma solicitação pequena, depois gere uma seção. Refinar cria outra versão e preserva a original. Publicação é uma etapa posterior.</p>
 <div className="ed-form-grid"><Field label="Pacote para construir"><select value={exportId} onChange={e=>setExportId(e.target.value)}><option value="">Exporte um pacote primeiro</option>{empresa.exportacoes.map(e=><option value={e.id} key={e.id}>Versão {e.versao} · {date(e.criado_em)}</option>)}</select></Field><Field label="Autenticação da construção"><select value={mode} disabled={busy} onChange={e=>setMode(e.target.value)}><Modes/></select></Field>
 <Field label="Modelo do runtime" hint="GPT-6.1 Sol permanece como preferência. Escolha uma alternativa explicitamente."><input value={model} list="ed-runtime-models" maxLength={100} onChange={e=>setModel(e.target.value)}/></Field><datalist id="ed-runtime-models">{entries.map(m=><option key={m.slug} value={m.slug}>{m.display_name}</option>)}</datalist><Field label="Alternativa do catálogo"><select value={entries.some(m=>m.slug===model)?model:''} onChange={e=>{if(e.target.value)setModel(e.target.value)}}><option value="">Manter modelo solicitado</option>{entries.map(m=><option key={m.slug} value={m.slug}>{m.display_name} · {m.slug}</option>)}</select></Field>
 <Field label="Prévia anterior para refinar"><select value={previous} onChange={e=>setPrevious(e.target.value)}><option value="">Construção nova</option>{q.data?.filter(j=>j.tipo==='codex_construcao'&&j.estado==='concluida').map(j=><option key={j.id} value={j.id}>{date(j.criado_em)} · {j.id.slice(0,8)}</option>)}</select></Field></div>
 <p role="status">Modelo selecionado: <strong>{model}</strong> · {states[access?.estado||(entries.some(m=>m.slug===model)?'listado':'acesso_nao_validado')]||access?.estado}. {access&&`Verificado em ${date(access.data)}.`}</p><Field label="Pedido para construir ou refinar"><textarea rows={3} maxLength={4000} value={instructions} onChange={e=>setInstructions(e.target.value)}/></Field>
 <div className="ed-form-actions"><button className="ed-button" disabled={!model||busy||build.isPending} onClick={()=>build.mutate('teste')}>Testar inferência pequena</button><button className="ed-button primary" disabled={!exportId||busy||build.isPending} onClick={()=>build.mutate('local')}>Montar prévia local · sem IA</button><button className="ed-button" disabled={!exportId||!model||busy||build.isPending} onClick={()=>build.mutate('codex')}>{previous?'Refinar com Codex app-server':'Construir com Codex app-server'}</button></div><small>Raciocínio Alto · velocidade Padrão. Falhas preservam o pedido e não mudam modelo ou cobrança. Este servidor serve HTML/CSS/JS; backend exige implementação adicional.</small>{build.isError&&<Erro error={build.error}/>} {url&&<External url={url}>Abrir prévia local</External>}</section><RuntimeCard modo={mode} onMode={setMode}/>
 <section className="ed-panel ed-form"><h2>Construções e refinamentos</h2>{q.isError&&<Erro error={q.error}/>} {!q.data?.length&&<p>Nenhuma construção registrada. Exportação externa e registro manual continuam disponíveis.</p>}{q.data?.map(j=><article key={j.id} className="ed-runtime-job"><div className="ed-panel-head"><strong>{j.tipo==='codex_teste'?'Teste mínimo · inferência real':j.tipo==='codex_construcao'?'Codex app-server':'Templates locais · sem IA'}</strong><Badge tone={j.estado==='concluida'?'green':'amber'}>{j.estado}</Badge></div><small>{date(j.criado_em)} · {j.parametros.exportacao_id?`pacote ${j.parametros.exportacao_id.slice(0,8)}`:'Sem arquivos'} · {j.parametros.modelo} · {j.parametros.modo}</small><p role="status">{j.mensagem}</p>{j.runtime&&<small>{j.runtime.versao} · {j.runtime.provider}</small>}<progress max={100} value={j.progresso} aria-label="Progresso da construção"/>{j.diagnostico&&<Details value={j.diagnostico}/>} {j.estado==='erro'&&<button className="ed-button" disabled={busy} onClick={()=>recover(j)}>Reutilizar pedido desta tentativa</button>} {['na_fila','pesquisando'].includes(j.estado)&&<button className="ed-button" onClick={()=>cancel.mutate(j.id)}>Cancelar construção</button>}{j.resultado&&<>{j.resultado.resposta&&<p>Resposta concluída: {j.resultado.resposta}</p>}{j.resultado.arquivos&&<p>Arquivos: {j.resultado.arquivos.join(', ')}</p>}{j.resultado.contexto_snapshot&&<details><summary>Contexto e skills utilizados ({j.resultado.contexto_snapshot.length})</summary><ul>{j.resultado.contexto_snapshot.map(x=><li key={x.id}>{x.tipo} · {x.id.slice(0,8)} · v{x.versao} · SHA {x.sha256.slice(0,12)}</li>)}</ul></details>}{j.resultado.consumo&&<small>Consumo informado: {JSON.stringify(j.resultado.consumo)}</small>}<ul>{j.resultado.pendencias?.map(x=><li key={x}>{x}</li>)}</ul>{j.tipo!=='codex_teste'&&j.estado==='concluida'&&<a className="ed-button" href={root+'/'+j.id+'/entrega'}>Baixar código e preparar entrega</a>}{j.tipo!=='codex_teste'&&<button className="ed-button" disabled={open.isPending} onClick={()=>open.mutate(j.id)}>Servir e associar prévia ao pacote</button>}</>}</article>)}{open.isError&&<Erro error={open.error}/>} {cancel.isError&&<Erro error={cancel.error}/>}</section></div>
}
