import { useEffect, useRef, type CSSProperties } from 'react'
import type { Empresa } from './types'
import type { Alternative, Block, Composition } from './studioApi'

export function SectionRenderer({company,composition,block,alternative,mobile=false,page=false}:{company:Empresa;composition:Composition;block:Block;alternative:Alternative;mobile?:boolean;page?:boolean}){
 const ref=useRef<HTMLElement>(null), m=company.materiais.find(m=>m.id===alternative.material_id)
 const prepared=m as typeof m & {versoes?:{id:string;arquivo_url:string;estado:string;instrucoes:{destino:string}}[]}
 const mobileVersion=prepared?.versoes?.filter(v=>v.estado==='aprovada'&&v.instrucoes.destino==='mobile').at(-1)
 const version=(m as typeof m & {versoes?:{id:string;arquivo_url:string}[];versao_exportacao?:string})?.versoes?.find(v=>v.id===(m as typeof m & {versao_exportacao?:string})?.versao_exportacao)
 const image=m?.autorizado&&m.selecionado?(mobile&&mobileVersion?mobileVersion.arquivo_url:version?.arquivo_url||m.arquivo_url):''
 const pos=mobile?alternative.mobile:alternative.desktop, motion=composition.movimento
 useEffect(()=>{
  const node=ref.current
  if(!node||motion.cursor!=='halo'||!matchMedia('(hover:hover) and (pointer:fine) and (prefers-reduced-motion:no-preference)').matches)return
  const move=(e:PointerEvent)=>{if(document.hidden||matchMedia('(prefers-reduced-motion:reduce)').matches)return;const b=node.getBoundingClientRect();node.style.setProperty('--cursor-x',`${e.clientX-b.left}px`);node.style.setProperty('--cursor-y',`${e.clientY-b.top}px`)}
  node.addEventListener('pointermove',move,{passive:true});return()=>node.removeEventListener('pointermove',move)
 },[motion.cursor])
 const visuals=<div className="lp-visual">{image?<img src={image} alt={m?.nome_original||'Material selecionado'} style={{objectPosition:pos.join('% ')+'%'}} loading="lazy"/>:<div className="lp-placeholder"><svg viewBox="0 0 200 200" aria-hidden="true"><circle cx="100" cy="100" r="75"/><path d="M45 135 78 95l28 25 29-42 30 57M55 150h90"/></svg><span>Imagem autorizada pendente</span><small>{block.tipo==='hero'?'Abertura':block.tipo} · enquadramento {pos.join(' / ')}%</small></div>}</div>
 const lines=alternative.texto.split(/\n+/).filter(Boolean)
 const content=<div className="lp-copy"><span className="lp-eyebrow">{company.nome} · {company.nicho||'Informações a revisar'}</span><h2>{alternative.titulo||company.nome}</h2>{lines.length?lines.map((text,i)=><p key={i}>{text}</p>):<p className="lp-missing">Texto pendente de revisão. Não criar informações comerciais.</p>}{m?.natureza==='ilustracao'&&<small className="lp-review">Ilustração de demonstração · não representa produtos ou instalações reais.</small>}{!alternative.revisado&&<small className="lp-review">Sugestão de texto · revisão pendente</small>}<a className="lp-cta" href="#contato">{alternative.cta||'Entrar em contato'} <span aria-hidden="true">↗</span></a></div>
 const style={'--lp-paper':composition.identidade.fundo,'--lp-ink':composition.identidade.tinta,'--lp-accent':composition.identidade.acento} as CSSProperties
 const structural=['servicos','produtos','processo','faq','galeria','equipe','rodape','cta','dados','operacoes'].includes(block.tipo)
 const header=<div className="lp-section-heading"><span className="lp-eyebrow">{company.nome} · {block.tipo}</span><h2>{alternative.titulo||company.nome}</h2>{!alternative.revisado&&<small className="lp-review">Texto proposto · revisão pendente</small>}</div>
 const fileFor=(x:typeof company.materiais[number])=>{const derivatives=(x as typeof x & {versoes?:{id:string;estado:string;arquivo_url:string;instrucoes:{destino:string}}[];versao_exportacao?:string});const approved=derivatives.versoes?.filter(v=>v.estado==='aprovada');return (mobile?approved?.filter(v=>v.instrucoes.destino==='mobile').at(-1):undefined)?.arquivo_url||approved?.find(v=>v.id===derivatives.versao_exportacao)?.arquivo_url||x.arquivo_url}
 const gallery=company.materiais.filter(x=>x.autorizado&&x.selecionado&&x.arquivo_url&&(block.tipo!=='equipe'||x.natureza==='pessoa'))
 const specialized=<>{header}{block.tipo==='faq'?<div className="lp-items">{lines.length?lines.map((t,i)=>{const [question,...answer]=t.split('|');return <details key={i}><summary>{question}</summary><p>{answer.join('|')||'Resposta a revisar; não inventar.'}</p></details>}):<p>Perguntas e respostas verificadas pendentes.</p>}</div>:['galeria','equipe'].includes(block.tipo)?<><p>{alternative.texto||'Legenda e associação dos materiais a revisar.'}</p><div className="lp-media-grid">{gallery.length?gallery.map(x=><figure key={x.id}><img src={fileFor(x)} style={{objectPosition:pos.join('% ')+'%'}} alt={x.nome_original} loading="lazy"/><figcaption>{x.natureza==='ilustracao'?'Ilustração de demonstração':x.nome_original}</figcaption></figure>):visuals}</div></>:block.tipo==='rodape'?<><p>{alternative.texto}</p><nav aria-label="Links do rodapé"><a href="#contato">Contato</a>{company.associacao_site.estado==='confirmado'&&company.site&&<a href={company.site} rel="noreferrer" target="_blank">Site confirmado ↗</a>}</nav><small>Prévia para revisão · não publicada</small></>:block.tipo==='cta'?<><p>{alternative.texto}</p><a className="lp-cta" href="#contato">{alternative.cta||'Entrar em contato'} ↗</a></>:<div className={`lp-items ${block.tipo==='processo'?'lp-steps':''}`}>{lines.length?lines.map((t,i)=><article key={i}><span className="lp-item-number">{String(i+1).padStart(2,'0')}</span><p>{t}</p></article>):<p>Conteúdo confirmado pendente.</p>}</div>}</>
 return <section ref={ref} id={page?(block.tipo==='contato'&&composition.secoes.find(s=>s.tipo==='contato')?.id===block.id?'contato':block.id):undefined} data-layout={alternative.layout} className={`lp-section lp-${alternative.layout} lp-${block.tipo} ${mobile?'lp-mobile':''} lp-font-${composition.identidade.fonte} lp-title-${motion.titulos} lp-transition-${motion.transicoes} lp-image-${motion.imagens} lp-card-${motion.cartoes} lp-button-${motion.botoes} lp-cursor-${motion.cursor} lp-parallax-${motion.parallax} lp-shader-${motion.shader}`} style={style}>
 {structural?specialized:alternative.layout==='mosaico'?<><div className="lp-mosaic-label"><span>01 / {block.tipo}</span><strong>{company.nome}</strong></div>{content}{visuals}</>:alternative.layout==='compacta'?<>{visuals}{content}</>:<>{content}{visuals}</>}
 {block.tipo==='contato'&&<div className="lp-contact"><h3>Informações revisadas</h3>{(['endereco','horarios','telefone','email'] as const).map(key=>company.fontes[key]?.verificacao==='confirmado_usuario'&&company[key]?<p key={key}>{key==='telefone'?<a href={`tel:${company[key].replace(/[^\d+]/g,'')}`}>{company[key]}</a>:key==='email'?<a href={`mailto:${company[key]}`}>{company[key]}</a>:company[key]}</p>:null)}{company.fonte_mapa_url&&<a href={company.fonte_mapa_url} target="_blank" rel="noreferrer">Abrir fonte de localização ↗</a>}</div>}
 </section>
}
