import {useEffect,useRef,useState} from 'react'
import {Link,useParams} from 'react-router-dom'
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query'
import {ArrowLeft,ArrowUpRight,Monitor,Smartphone,Send,RotateCcw} from 'lucide-react'
import {httpClient} from '@/services/httpClient'
import {csrfHeaders} from './accessState'
import {useAccess} from './accessContext'
import {Badge,Erro,Loading,FileInput,ResearchProgress} from './shared'
import {VoiceComposer,type Transcript} from './VoiceComposer'
import './siteRefinement.css'

interface Version {id:string;numero:number;base?:string;url?:string;modelo?:string;fornecedor:string;brief_versao:number;arquivos:string[];arquivos_devolvidos:string[];pendencias:string[];build?:unknown;contexto_executor?:unknown}
interface Message {id:string;papel:string;texto:string;estado_fila?:string;origem?:string;versao_id?:string;transcricao_id?:string}
interface Session {revisao_contexto?:{autorizacao_id:string;contexto_hash:string;alteracoes:{titulo:string;situacao:string;versao:number}[]};id:string;empresa_id:string;chat_id:string;estado:string;brief_versao:number;variante_id:string;autorizacao_id?:string;atual?:string;url?:string;execucao_id?:string;lacunas:string[];versoes:Version[];comandos:Message[];mensagens:Message[];rascunho:string;fluxo?:{estado:string;mensagem:string;operacao?:{mensagem:string;progresso:number;modelo?:string};etapas:{nome:string;estado:string;resultado?:unknown}[]}}
const labels:Record<string,string>={construindo:'Construindo primeira prévia',refinando:'Aplicando refinamento',pronta:'Prévia de trabalho pronta',escolhas_pendentes:'Escolhas pendentes',pausada:'Execução pausada',aguardando_dependencia:'Acesso ou operação requer revisão',falhou:'Falha · última versão preservada',cancelada:'Execução cancelada'}
const queued:Record<string,string>={aguardando_base:'Salvo · aguardando a base HTML',na_fila:'Salvo · na fila',executando:'Aplicando à versão indicada',aguardando_recuperacao:'Salvo · aguardando recuperação da execução',concluida:'Nova versão salva'}

export function SiteRefinementPage(){
 const {id='',session=''}=useParams(),client=useQueryClient(),readonly=useAccess()?.ator?.papel==='leitura'
 const root=`/api/ed/empresas/${id}/refinamento-site/${session}`
 const query=useQuery({queryKey:['ed','refinamento-site',id,session],queryFn:()=>httpClient.get<Session>(root),refetchInterval:q=>['construindo','refinando'].includes(q.state.data?.estado||'')||q.state.data?.comandos.some(c=>['na_fila','aguardando_base'].includes(c.estado_fila||''))?1500:5000})
 const [text,setText]=useState(''),[voice,setVoice]=useState<Transcript|null>(null),[mobile,setMobile]=useState(()=>window.matchMedia('(max-width:800px)').matches),[tab,setTab]=useState('previa'),[width,setWidth]=useState(380),[compare,setCompare]=useState(''),[error,setError]=useState<Error|null>(null),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false),[frameSize,setFrameSize]=useState({width:1080,height:620})
 const frame=useRef<HTMLDivElement>(null)
 const autoOpened=useRef('')
 const initialized=useRef(false),textarea=useRef<HTMLTextAreaElement>(null),key=useRef(crypto.randomUUID()),draftSequence=useRef(0)
 const reload=()=>client.invalidateQueries({queryKey:['ed','refinamento-site',id,session]})
 useEffect(()=>{
  const element=frame.current;if(!element)return
  const observer=new ResizeObserver(entries=>{const box=entries[0].contentRect;setFrameSize({width:box.width,height:box.height})})
  observer.observe(element);return()=>observer.disconnect()
 },[query.data?.url,mobile,tab])
 useEffect(()=>{if(query.data&&!initialized.current){initialized.current=true;setText(query.data.rascunho)}},[query.data])
 useEffect(()=>{
  if(!initialized.current||readonly)return
  setSaved(false);const seq=++draftSequence.current
  const timer=setTimeout(()=>{setSaving(true);httpClient.put(root+'/rascunho',{texto:text}).then(()=>{if(seq===draftSequence.current){setSaved(true);setError(null)}}).catch(e=>setError(e as Error)).finally(()=>setSaving(false))},600)
  return()=>clearTimeout(timer)
 },[text,root,readonly])
 const send=useMutation({mutationFn:()=>httpClient.post(`/api/ed/assistente/conversas/${query.data!.chat_id}/mensagens`,{texto:text,chave:key.current,origem:voice?'voz':'texto',...(voice?{transcricao_id:voice.id}:{})}),onSuccess:()=>{key.current=crypto.randomUUID();setText('');setVoice(null);void reload();setTab('conversa')}})
 const reviewContext=useMutation({mutationFn:()=>httpClient.post(root+'/contexto',{autorizacao_id:query.data!.revisao_contexto!.autorizacao_id,contexto_hash:query.data!.revisao_contexto!.contexto_hash}),onSuccess:reload})
 const resume=useMutation({mutationFn:()=>httpClient.post(root+'/continuar',{}),onSuccess:reload})
 const restore=useMutation({mutationFn:(version:string)=>httpClient.post(root+'/restaurar',{versao_id:version}),onSuccess:()=>{setCompare('');void reload()}})
 const open=useMutation({mutationFn:(version:string)=>httpClient.post<{url:string}>(`/api/ed/empresas/${id}/construcoes/${version}/abrir`,{}),onSuccess:reload})
 useEffect(()=>{const s=query.data;if(s?.atual&&!s.url&&!readonly&&autoOpened.current!==s.atual){autoOpened.current=s.atual;open.mutate(s.atual)}},[query.data,readonly,open])
 const action=useMutation({mutationFn:(op:string)=>httpClient.post(`/api/ed/fluxos/${query.data!.execucao_id}/${op}`,{}),onSuccess:reload})
 async function attach(file:File){try{setError(null);const form=new FormData();form.set('arquivo',file);const r=await fetch(`/api/ed/assistente/conversas/${query.data!.chat_id}/anexos`,{method:'POST',headers:csrfHeaders(),body:form});const body=await r.json();if(!r.ok)throw Error(body.erro);await reload()}catch(e){setError(e as Error)}}
 if(query.isPending)return <Loading/>
 if(query.isError)return <Erro error={query.error}/>
 const s=query.data,busy=['construindo','refinando'].includes(s.estado),version=s.versoes.find(v=>v.id===s.atual),comparison=s.versoes.find(v=>v.id===compare)
 const lastCommand=s.comandos.at(-1),resultVersion=s.versoes.find(v=>v.id===lastCommand?.versao_id)
 const stage=s.fluxo?.etapas.find(e=>e.estado==='executando')?.nome
 const progressMessage=stage==='exportar'?'Preparando suas instruções e os materiais selecionados.':stage==='verificar'?'Conferindo os arquivos e abrindo a nova versão.':stage==='prospeccao'?'Salvando o resultado e o texto de prospecção, sem enviar.':'Codex está aplicando seu comando ao site. A versão anterior continua disponível.'
 const validUrl=(url?:string)=>url&&/^http:\/\/127\.0\.0\.1:51(?:3[1-9]|[4-8][0-9]|90)\/$/.test(url)?url:undefined
 const url=validUrl(comparison?comparison.url:s.url)
 return <div className="ed-site-studio">
  <header className="ed-site-head"><div><Link className="ed-link" to={`/empresas/${id}?aba=visual`}><ArrowLeft size={15}/> Voltar à galeria</Link><h1>Refinar site</h1><p>Brief v{s.brief_versao} · {version?'Versão '+version.numero:'Primeira versão'} · Codex nativo</p></div><Badge tone={s.estado==='pronta'?'green':'amber'}>{labels[s.estado]||s.estado}</Badge></header>
  <div className="ed-site-toolbar"><div className="ed-actions"><button className="ed-button" aria-pressed={!mobile} onClick={()=>setMobile(false)}><Monitor size={16}/> Desktop</button><button className="ed-button" aria-pressed={mobile} onClick={()=>setMobile(true)}><Smartphone size={16}/> Celular</button>{url&&<a className="ed-button" href={url} target="_blank" rel="noopener noreferrer">Abrir em nova aba <ArrowUpRight size={15}/></a>}</div><label className="ed-site-versions">Comparar versões<select aria-label="Comparar versões" value={compare} onChange={e=>setCompare(e.target.value)}><option value="">Versão corrente{version?' · '+version.numero:''}</option>{s.versoes.filter(v=>v.id!==s.atual).map(v=><option key={v.id} value={v.id}>Versão {v.numero} · {v.modelo}</option>)}</select></label>{comparison&&<button className="ed-button" disabled={readonly||restore.isPending} onClick={()=>restore.mutate(comparison.id)}><RotateCcw size={15}/> Restaurar versão {comparison.numero}</button>}</div>
  {s.revisao_contexto&&<section className="ed-panel" aria-label="Contexto atualizado"><h2>Revisar contexto antes de retomar</h2><p>As instruções ou referências selecionadas mudaram. A composição escolhida, o brief e a versão anterior continuam preservados.</p><ul>{s.revisao_contexto.alteracoes.map((a,i)=><li key={i}>{a.titulo} · v{a.versao} · {a.situacao}</li>)}</ul><button className="ed-button primary" disabled={readonly||busy||reviewContext.isPending} onClick={()=>reviewContext.mutate()}>Usar contexto atualizado nesta conversa</button><p className="ed-muted">Confirma somente as alterações acima para esta conversa; depois retome pelos checkpoints. Mudanças no brief, na montagem ou nos materiais ainda exigem revisão própria.</p></section>}
  {busy&&<ResearchProgress active message={progressMessage} value={s.fluxo?Math.floor((s.fluxo.etapas.filter(e=>e.estado==='concluida').length*100+(s.fluxo.operacao?.progresso||0))/s.fluxo.etapas.length):undefined} label="Progresso da construção"/>}
  <nav className="ed-site-mobile-tabs" aria-label="Área de trabalho"><button className="ed-button" aria-pressed={tab==='previa'} onClick={()=>setTab('previa')}>Prévia</button><button className="ed-button" aria-pressed={tab==='conversa'} onClick={()=>setTab('conversa')}>Conversa{s.comandos.some(c=>c.estado_fila!=='concluida')?' · comandos salvos':''}</button></nav>
  <div className="ed-site-grid" style={{gridTemplateColumns:`minmax(0,1fr) 12px ${width}px`}}>
   <section className={'ed-site-preview'+(tab!=='previa'?' mobile-hidden':'')} aria-label="Prévia HTML real">
    {comparison&&<p className="ed-alert">Comparando a versão {comparison.numero}. A versão corrente permanece preservada.</p>}
    {url?<><div ref={frame} className={'ed-site-frame'+(mobile?' phone':'')}><iframe title={`Prévia HTML · versão ${comparison?.numero||version?.numero}`} src={url} style={{width:mobile?390:Math.max(1080,frameSize.width),height:frameSize.height/Math.min(1,frameSize.width/(mobile?390:1080)),transform:`scale(${Math.min(1,frameSize.width/(mobile?390:1080))})`,transformOrigin:'top left'}} sandbox="allow-scripts allow-popups allow-popups-to-escape-sandbox" referrerPolicy="no-referrer" allow="camera 'none'; microphone 'none'; geolocation 'none'"/></div>{busy&&<p role="status">A versão anterior continua aberta enquanto a nova é construída e validada.</p>}</>:<div className="ed-site-wait"><h2>{s.atual?'Abrir a versão preservada':labels[s.estado]||'Aguardando HTML'}</h2><p>{s.atual?'A prévia não está aberta nesta sessão do CRM. Os arquivos e versões continuam salvos.':busy?'O Codex está reconstruindo elementos reais a partir da composição escolhida. Você já pode enviar ajustes na conversa.':'O HTML ainda não foi concluído. Confira as etapas e pendências na conversa.'}</p>{s.atual&&<button className="ed-button primary" disabled={readonly||open.isPending} onClick={()=>open.mutate(comparison?.id||s.atual!)}>Abrir prévia local</button>}{s.lacunas.length>0&&<><h3>Escolhas que faltam</h3><ul>{s.lacunas.map(g=><li key={g}>{g}</li>)}</ul><Link className="ed-button" to={`/empresas/${id}?aba=visual`}>Revisar escolhas na galeria</Link><button className="ed-button primary" disabled={readonly||resume.isPending} onClick={()=>resume.mutate()}>Continuar com a montagem atual</button></>}</div>}
   </section>
   <div className="ed-site-divider" role="separator" tabIndex={0} aria-label="Redimensionar painel de conversa" aria-orientation="vertical" aria-valuemin={320} aria-valuemax={600} aria-valuenow={width} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();setWidth(w=>e.key==='Home'?320:e.key==='End'?600:Math.min(600,Math.max(320,w+(e.key==='ArrowLeft'?20:-20))))}}} onPointerDown={e=>e.currentTarget.setPointerCapture(e.pointerId)} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId)){const right=e.currentTarget.parentElement!.getBoundingClientRect().right;setWidth(Math.min(600,Math.max(320,right-e.clientX)))}}}/>
   <aside className={'ed-panel ed-site-chat'+(tab!=='conversa'?' mobile-hidden':'')} aria-label="Conversa de refinamento">
    <h2>Trabalhar nesta prévia</h2><p>Comandos ficam salvos nesta empresa e projeto. A versão anterior continua restaurável.</p>
    {lastCommand&&<div className="ed-site-receipt" role="status"><strong>{lastCommand.origem==='voz'?'Áudio transcrito e comando recebido':'Comando recebido'}</strong><p>{lastCommand.estado_fila==='concluida'?`Seus ajustes foram aplicados na versão ${resultVersion?.numero||'salva'}.`:lastCommand.estado_fila==='executando'?'Refinamento em andamento pelo Codex. Não precisa enviar novamente.':lastCommand.estado_fila==='aguardando_recuperacao'?'A execução precisa de recuperação. Seu comando e o site anterior estão salvos.':'Seu comando está salvo e aguarda a conclusão da etapa anterior.'}</p>{resultVersion&&<button type="button" className="ed-button primary" onClick={()=>{setCompare(resultVersion.id===s.atual?'':resultVersion.id);setTab('previa');frame.current?.scrollIntoView({block:'start'})}}>Ver resultado · versão {resultVersion.numero}</button>}</div>}
    <details><summary>Ver conversa e referências ({s.mensagens.length})</summary><div className="ed-site-messages" aria-label="Histórico da conversa">{s.mensagens.map(m=><article key={m.id} className={m.papel==='usuario'?'operator':'system'}>{m.origem==='brief_revisado'?<><small>Composição escolhida · brief v{s.brief_versao}</small><p>Direção, materiais e informações revisadas encaminhados ao Codex.</p><details><summary>Ver instrução de construção</summary><p>{m.texto}</p></details></>:<><small>{m.papel==='usuario'?'Você':m.papel==='anexo'?'Referência anexada':'CRM'}{m.origem==='voz'?' · áudio revisado':''}</small><p>{m.texto}</p></>}{m.estado_fila&&<Badge>{queued[m.estado_fila]||m.estado_fila}</Badge>}</article>)}</div></details>
    <form onSubmit={e=>{e.preventDefault();if(text.trim())send.mutate()}}><label htmlFor="ed-site-command">{voice?'Revisar transcrição':'Seu comando'}</label><textarea ref={textarea} id="ed-site-command" rows={5} value={text} maxLength={12000} disabled={readonly||send.isPending} onChange={e=>{setText(e.target.value);send.reset();key.current=crypto.randomUUID()}} placeholder="Ex.: diminuir o espaço da abertura e preservar as outras seções."/><small role="status">{saving?'Salvando rascunho…':saved?'Rascunho salvo no CRM':'Revise antes de enviar.'}</small><VoiceComposer submitted={s.comandos.filter(c=>c.origem==='voz').at(-1)?.transcricao_id} disabled={readonly} onText={(t,source)=>{setText(t);setVoice(source);key.current=crypto.randomUUID();textarea.current?.focus()}}/>{voice&&<button type="button" className="ed-button" onClick={()=>textarea.current?.focus()}>Revisar transcrição</button>}<button className="ed-button primary" disabled={readonly||!text.trim()||send.isPending}><Send size={16}/> {busy?'Enviar · aguardar na fila':'Enviar refinamento'}</button></form>
    <details><summary>Adicionar arquivo de referência</summary><p>HTML: até 8 MB, com original preservado e análise estática de tecnologias, animações e composição. TXT/Markdown: até 256 KB. Aplicação restrita a esta conversa; sem preferência global.</p><FileInput accept=".html,.htm,.txt,.md" disabled={readonly} onChange={e=>{const f=e.target.files?.[0];if(f)void attach(f);e.target.value=''}}/></details>
    <details><summary>Etapas, contexto aplicado e pendências</summary>{s.fluxo?.operacao&&<p>{s.fluxo.operacao.mensagem}</p>}<p>Autorização de trabalho: {s.autorizacao_id||'Aguardando escolhas'}. Sem aprovação estética final, do titular ou publicação.</p><p>Conversa {s.chat_id} · composição {s.variante_id}</p>{s.fluxo&&<><p role="status">{s.fluxo.mensagem}</p><ol>{s.fluxo.etapas.map(e=><li key={e.nome}>{e.nome} · {e.estado}</li>)}</ol></>}{version&&<><p>{version.fornecedor} · {version.modelo} · brief v{version.brief_versao}</p><ul>{version.pendencias.map((p,i)=><li key={i}>{p}</li>)}</ul><pre>{JSON.stringify({build:version.build,arquivos:version.arquivos_devolvidos,contexto:version.contexto_executor},null,2)}</pre></>}{busy&&<button className="ed-button" disabled={readonly||action.isPending} onClick={()=>action.mutate('pausar')}>Pausar execução</button>}{s.execucao_id&&!busy&&s.estado!=='pronta'&&<button className="ed-button" disabled={readonly||resume.isPending} onClick={()=>resume.mutate()}>Retomar por checkpoints</button>}</details>
    {[send,resume,restore,open,action,reviewContext].filter(m=>m.isError).map((m,i)=><Erro key={i} error={m.error}/>)}{error&&<Erro error={error}/>}<p className="ed-muted">Fotos e logo conceituais não comprovam produtos, instalações ou aprovação do titular. Nada é publicado ou enviado.</p>
   </aside>
  </div>
 </div>
}
