import { useState } from 'react'
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query'
import { httpClient } from '@/services/httpClient'
import { api } from './api'
import type { Empresa } from './types'
import type { Operation } from './preparationTypes'
import { Field,Erro,External,Badge } from './shared'
import { date } from './domain'
interface SocialImage {id:string;url:string;origem:string;legenda:string;largura:number|null;altura:number|null;data_post:string;carrossel_indice:number}
interface Result {perfis:{usuario:string;nome:string;bio:string;site:string;origem:string;evidencias?:string[]}[];imagens:SocialImage[];pendencias:string[]}
interface SocialJob extends Operation {resultado?:Result;parcial?:Result;criado_em:string;consumo?:Record<string,number>}
interface Social {associacao:{estado:string;url:string;evidencia:string};execucoes:SocialJob[]}
export function SocialPanel({empresa}:{empresa:Empresa}){
 const client=useQueryClient(),root=`/api/ed/empresas/${empresa.id}/instagram`
 const [profile,setProfile]=useState(empresa.instagram),[evidence,setEvidence]=useState(''),[reviewed,setReviewed]=useState(false),[provider,setProvider]=useState('apify'),[mode,setMode]=useState('materiais'),[query,setQuery]=useState(`${empresa.nome} ${empresa.cidade}`),[limit,setLimit]=useState(6),[budget,setBudget]=useState(.05),[jobId,setJobId]=useState('')
 const q=useQuery({queryKey:['ed','social',empresa.id],queryFn:()=>httpClient.get<Social>(root),refetchInterval:q=>q.state.data?.execucoes.some(j=>['na_fila','pesquisando'].includes(j.estado))?1500:false})
 const refresh=()=>client.invalidateQueries({queryKey:['ed']})
 const confirm=useMutation({mutationFn:()=>httpClient.post(root+'/confirmar',{perfil:profile,valor_anterior:empresa.instagram,evidencia:evidence}),onSuccess:()=>{setReviewed(false);refresh()}})
 const start=useMutation({mutationFn:()=>httpClient.post<SocialJob>(root+'/pesquisar',{fornecedor:provider,perfil:profile,modo:mode,consulta:query,limite:limit,orcamento:budget}),onSuccess:j=>{setJobId(j.id);refresh()}})
 const activeJob=jobId?q.data?.execucoes.find(j=>j.id===jobId):q.data?.execucoes[0]
 const busy=!!activeJob&&['na_fila','pesquisando'].includes(activeJob.estado)
 const cancel=useMutation({mutationFn:()=>api.cancelarOperacao(activeJob!.id),onSuccess:refresh})
 const result=activeJob?.resultado||activeJob?.parcial
 return <div className="ed-research"><section className="ed-panel ed-form"><h2>Instagram · associação e materiais</h2><p>Nome semelhante não confirma identidade. Registre endereço, contato ou vínculo entre site e perfil. Cadastro e upload permanecem disponíveis.</p><Badge tone={q.data?.associacao.estado==='confirmado'?'green':'amber'}>{q.data?.associacao.estado==='confirmado'?'Perfil confirmado por revisão humana':'Associação pendente'}</Badge>{q.data?.associacao.evidencia&&<p>{q.data.associacao.evidencia}</p>}
 <Field label="Perfil, @usuário ou URL"><input maxLength={500} value={profile} onChange={e=>{setProfile(e.target.value);setReviewed(false)}}/></Field><Field label="Evidências revisadas do perfil"><textarea value={evidence} rows={3} maxLength={2000} onChange={e=>{setEvidence(e.target.value);setReviewed(false)}}/></Field><label className="ed-check"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/> Conferi empresa, filial e vínculo deste perfil.</label><button className="ed-button" disabled={!reviewed||evidence.trim().length<15||confirm.isPending} onClick={()=>confirm.mutate()}>Confirmar perfil com evidências</button>{confirm.isError&&<Erro error={confirm.error}/>} {q.isError&&<Erro error={q.error}/>}</section>
 <section className="ed-panel ed-form"><h2>Consultar a fonte</h2><div className="ed-form-grid"><Field label="Fonte de Instagram"><select value={provider} onChange={e=>{setProvider(e.target.value);if(e.target.value!=='apify')setMode('materiais')}}><option value="apify">Apify · perfis públicos</option><option value="instagram">Meta · própria conta autorizada</option><option value="meta_discovery">Meta · outro perfil profissional (Facebook Login)</option></select></Field><Field label="Objetivo da coleta"><select value={mode} onChange={e=>setMode(e.target.value)}><option value="materiais">Materiais de perfil confirmado</option><option value="descobrir" disabled={provider!=='apify'}>Descobrir candidatos por consulta</option></select></Field><Field label="Limite de resultados"><input type="number" min={1} max={20} value={limit} onChange={e=>setLimit(Number(e.target.value))}/></Field>{provider==='apify'&&<Field label="Teto Apify por execução (US$)" hint="Enviado ao Actor; consulte preços e custos no painel. Pode retornar coleta parcial ao atingir o teto."><input type="number" step=".01" min=".01" max="5" value={budget} onChange={e=>setBudget(Number(e.target.value))}/></Field>}</div>{mode==='descobrir'&&<Field label="Nome e localização para candidatos"><input value={query} maxLength={300} onChange={e=>setQuery(e.target.value)}/></Field>}<button className="ed-button primary" disabled={busy||start.isPending} onClick={()=>start.mutate()}>Pesquisar Instagram</button><p>Meta autorizada só lê a conta do token. Business Discovery consulta outros perfis profissionais com permissões distintas. Apify exige token/saldo e não concede autorização de uso.</p>{start.isError&&<Erro error={start.error}/>} {cancel.isError&&<Erro error={cancel.error}/>} {activeJob&&<div role="status"><p>{activeJob.estado} · {activeJob.mensagem}</p><progress max={100} value={activeJob.progresso} aria-label="Progresso do Instagram"/>{busy&&<button className="ed-button" onClick={()=>cancel.mutate()}>Cancelar coleta</button>}{activeJob.consumo&&<p>Consumo informado: {JSON.stringify(activeJob.consumo)}</p>}</div>}</section>
 {result&&<section className="ed-panel ed-form"><h2>Resultados para revisão</h2>{result.perfis.map((p,i)=><article key={i} className="ed-suggestion"><h3>{p.nome||p.usuario}</h3><p>{p.bio}</p><External url={p.origem}>Perfil candidato @{p.usuario}</External>{p.site&&<External url={p.site}>Link publicado pelo perfil</External>}<ul>{p.evidencias?.map(x=><li key={x}>{x}</li>)}</ul><small>Compare localização, contato e fontes. Nenhuma confirmação automática.</small><button className="ed-button" onClick={()=>{setProfile(p.origem);setReviewed(false)}}>Revisar candidato @{p.usuario}</button></article>)}<ul>{result.pendencias.map(x=><li key={x}>{x}</li>)}</ul><div className="ed-suggestion-list">{result.imagens.map(im=><ImportSocialImage key={im.id} root={root} job={activeJob!.id} image={im}/>)}</div></section>}
 <section className="ed-panel ed-form"><details><summary>Histórico de coletas ({q.data?.execucoes.length||0})</summary>{q.data?.execucoes.map(j=><p key={j.id}>{date(j.criado_em)} · {j.fornecedor} · {j.estado} <button className="ed-button" onClick={()=>setJobId(j.id)}>Ver coleta</button></p>)}</details></section></div>
}
function ImportSocialImage({root,job,image:im}:{root:string;job:string;image:SocialImage}){
 const client=useQueryClient(),[preview,setPreview]=useState(false),[authorized,setAuthorized]=useState(false),[attribution,setAttribution]=useState('')
 const url=`${root}/${job}/imagens/${im.id}`
 const imported=useMutation({mutationFn:()=>httpClient.post(url+'/importar',{autorizado:authorized,atribuicao:attribution}),onSuccess:()=>client.invalidateQueries({queryKey:['ed']})})
 return <article className="ed-suggestion">{preview?<img src={url} alt="Mídia candidata; identidade e direitos a confirmar" onError={()=>setPreview(false)}/>:<button className="ed-button" onClick={()=>setPreview(true)}>Carregar prévia da fonte</button>}<p>{im.legenda||'Legenda não disponibilizada'}</p><small>Item {im.carrossel_indice+1} · {im.largura||'?'} × {im.altura||'?'} · {im.data_post||'Data não informada'}</small><External url={im.origem}>Post e origem</External><label className="ed-check"><input type="checkbox" checked={authorized} onChange={e=>setAuthorized(e.target.checked)}/> Tenho autorização de uso desta mídia.</label><Field label={`Titular / atribuição · item ${im.carrossel_indice+1}`}><input value={attribution} maxLength={1000} onChange={e=>setAttribution(e.target.value)}/></Field><button className="ed-button" disabled={imported.isPending||imported.isSuccess||authorized&&!attribution} onClick={()=>imported.mutate()}>{imported.isSuccess?'Importado':'Importar original disponível'}</button><small>Sem autorização, fica fora da seleção e do ZIP. Erro de mídia pode indicar link expirado; use upload.</small>{imported.isError&&<Erro error={imported.error}/>}</article>
}
