import {useState} from 'react'
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query'
import {httpClient} from '@/services/httpClient'
import {api} from './api'
import {Field,Erro} from './shared'
import type {Operation} from './preparationTypes'
type VisualResult = {biblioteca_id?:string;capturas?:{viewport:string;url:string}[]}
export function VisualResearch({company=''}:{company?:string}){
 const client=useQueryClient(),[url,setUrl]=useState(''),[title,setTitle]=useState(''),[source,setSource]=useState('browser'),[mode,setMode]=useState('inspirar'),[jobId,setJobId]=useState('')
 const start=useMutation({mutationFn:()=>httpClient.post<{id:string}>('/api/ed/biblioteca/pesquisar-visual',{url,titulo:title,fonte:source,modo:mode,empresa_id:company}),onSuccess:d=>setJobId(d.id)})
 const q=useQuery({queryKey:['ed','operacao',jobId],enabled:!!jobId,queryFn:async()=>{const j=await api.operacao(jobId) as Operation<VisualResult>;if(!['na_fila','pesquisando'].includes(j.estado))client.invalidateQueries({queryKey:['ed','biblioteca']});return j},refetchInterval:q=>['na_fila','pesquisando'].includes(q.state.data?.estado||'')?1200:false})
 const active=['na_fila','pesquisando'].includes(q.data?.estado||''),cancel=useMutation({mutationFn:()=>api.cancelarOperacao(jobId),onSuccess:()=>client.invalidateQueries({queryKey:['ed','operacao',jobId]})})
 return <details className="ed-panel ed-form"><summary>Pesquisar direção visual de um site</summary><p>Cria uma sugestão na biblioteca. Revise e ative antes de usar; suas decisões existentes são preservadas.</p><form onSubmit={e=>{e.preventDefault();start.mutate()}}><div className="ed-form-grid"><Field label="URL da referência"><input type="url" required maxLength={2000} value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://site-publico.com"/></Field><Field label="Nome da referência"><input required maxLength={150} value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="Leitura visual"><select value={source} onChange={e=>setSource(e.target.value)}><option value="browser">Chrome local isolado · desktop e celular</option><option value="local">HTML/CSS local · sem JavaScript</option><option value="firecrawl">HTML renderizado · Firecrawl configurado</option></select></Field><Field label="Como aproveitar"><select value={mode} onChange={e=>setMode(e.target.value)}><option value="inspirar">Inspirar uma identidade própria</option><option value="recriar_composicao">Recriar composição com conteúdo próprio</option></select></Field></div><button className="ed-button" disabled={active||start.isPending}>Pesquisar referência</button></form>{q.data&&<div role="status"><p>{q.data.mensagem}</p><progress aria-label="Pesquisa visual" value={q.data.progresso} max={100}/>{q.data.estado==='concluida'&&<p>Perfil disponível como sugestão inativa. Confirme o resultado renderizado, recortes e interações antes de ativar.</p>}{q.data.resultado?.biblioteca_id&&<p><a className="ed-text-button" href="/biblioteca/referencias">Revisar sugestão na biblioteca ↗</a></p>}{q.data.resultado?.capturas&&<div className="ed-reference-captures">{q.data.resultado.capturas.map(c=><figure key={c.viewport}><img src={c.url} alt={"Referência renderizada · "+c.viewport} loading="lazy"/><figcaption>{c.viewport} · inspiração; direitos não transferidos</figcaption></figure>)}</div>}{active&&<button className="ed-button" onClick={()=>cancel.mutate()} disabled={cancel.isPending}>Cancelar pesquisa</button>}</div>}{[start.error,q.error,cancel.error].filter(Boolean).map((e,i)=><Erro key={i} error={e}/>)}<small>Chrome não usa sessões ou credenciais e bloqueia formulários, frames e chamadas de dados externas. Algumas páginas podem ficar parciais. Fontes são dados externos. Bibliotecas detectadas no código são indícios, sem garantia de execução. Não copia marca, fotos comerciais ou dados da referência.</small></details>
}
