import { useRef,useState } from 'react'
import { Link,useNavigate } from 'react-router-dom'
import { useMutation } from '@tanstack/react-query'
import { Maximize2,Sparkles } from 'lucide-react'
import { httpClient } from '@/services/httpClient'
import { useAccess } from './accessContext'
import { Badge,Erro,Field,FileInput } from './shared'
import { visualStudioApi as api,type VisualStudio,type VisualVariant,type VisualJob } from './visualStudioApi'

function Zoom({variant}:{variant:VisualVariant}){
 const dialog=useRef<HTMLDialogElement>(null)
 return <><button className={'ed-visual-image'+(variant.largura>variant.altura?' landscape':'')} onClick={()=>dialog.current?.showModal()} aria-label={'Ampliar '+variant.titulo}><img src={variant.arquivo_url} alt={variant.titulo} width={variant.largura} height={variant.altura} loading="lazy" decoding="async"/><span><Maximize2 size={14}/>Ampliar</span></button><dialog ref={dialog} className="ed-visual-zoom" aria-label={variant.titulo}><div className="ed-visual-zoom-head"><h3>{variant.titulo}</h3><button className="ed-button" onClick={()=>dialog.current?.close()}>Fechar</button></div><p>Proposta visual candidata · {variant.largura} × {variant.altura}. A imagem não representa uma instalação real da empresa.</p><img src={variant.arquivo_url} alt={variant.titulo} width={variant.largura} height={variant.altura} decoding="async"/></dialog></>
}

export function VisualProposals({state,disabled,busy,onChanged,onSaved,onMontage}:{state:VisualStudio;disabled:boolean;busy:boolean;onChanged:(s:VisualStudio)=>void;onSaved:()=>void;onMontage:()=>void}){
 const navigate=useNavigate()
 const openSite=useMutation({mutationFn:(v:VisualVariant)=>httpClient.post<{id:string}>(`/api/ed/empresas/${state.empresa_id}/refinamento-site`,{projeto_id:state.projeto_id,variante_id:v.id}),onSuccess:s=>{onSaved();navigate(`/empresas/${state.empresa_id}/refinar/${s.id}`)}})
 const [section,setSection]=useState('pagina'),[provider,setProvider]=useState('codex_nativo'),[instructions,setInstructions]=useState(''),[parent,setParent]=useState(''),[file,setFile]=useState<File|null>(null),[permission,setPermission]=useState(false)
 const generationKey=useRef({key:crypto.randomUUID(),signature:''})
 const generate=useMutation({mutationFn:(options?:{one?:boolean;instructions?:string;parent?:string})=>{const origin=options?.parent??parent,text=options?.instructions??instructions,quantity=options?.one?1:state.quantidade;const signature=JSON.stringify([state.revisao,quantity,section,provider,text,origin]);if(generationKey.current.signature!==signature)generationKey.current={key:crypto.randomUUID(),signature};return api.generate(state.empresa_id,state,section,provider,text,origin,generationKey.current.key,quantity)},onSuccess:()=>{generationKey.current={key:crypto.randomUUID(),signature:''};onSaved()}})
 const choose=useMutation({mutationFn:(v:VisualVariant)=>api.choose(state.empresa_id,state,v.id),onSuccess:onSaved})
 const upload=useMutation({mutationFn:()=>api.upload(state.empresa_id,state,file!,file!.name,section,'Candidata importada pelo operador; autorização para uso como fotografia comercial não comprovada.'),onSuccess:()=>{setFile(null);setPermission(false);onSaved()}})
 const variants=state.variantes.filter(v=>v.secao_id===section)
 return <section className="ed-panel ed-form"><div className="ed-visual-toolbar"><Field label="Comparar propostas de"><select value={section} onChange={e=>{setSection(e.target.value);setParent('')}}><option value="pagina">Página inteira · referências e visão geral</option>{state.secoes.map(s=><option key={s.id} value={s.id}>{s.titulo}</option>)}</select></Field><button className="ed-button" onClick={onMontage}>Revisar montagem →</button></div>
 <p>As imagens enviadas são referências candidatas. Escolher uma proposta prepara a montagem; clique em Refinar site para autorizar uma prévia de trabalho. A aprovação final continua separada.</p>
 {variants.length?<div className="ed-visual-options">{variants.map(v=>{const stale=v.direcao_versao!==state.direcao.versao,selected=state.escolhas[section]===v.id;return <article key={v.id} className={'ed-visual-option'+(selected?' chosen':'')}><Zoom variant={v}/><div className="ed-visual-option-body"><h3>{v.titulo}</h3><Badge>{stale?'Direção anterior':selected?'Escolhida para montagem':'Candidata · a revisar'}</Badge><p>{v.fornecedor==='upload'?'Importada · origem externa':v.origem_id?'Refinamento real':'Gerada pelo fornecedor'} · {v.fornecedor}<br/>{v.largura} × {v.altura} · direção v{v.direcao_versao}</p><div className="ed-actions">{selected&&<button className="ed-button primary" disabled={disabled||stale||openSite.isPending} onClick={()=>openSite.mutate(v)}>{openSite.isPending?'Abrindo estúdio…':'Refinar site'}</button>}<button className="ed-button" disabled={disabled||stale||choose.isPending} onClick={()=>choose.mutate(v)}>{selected?'Escolhida':'Escolher composição'}</button><button className="ed-button" disabled={disabled||stale||busy} onClick={()=>{setParent(v.id);setInstructions('');document.getElementById('ed-visual-refinar')?.focus()}}>Editar imagem</button><button className="ed-button" disabled={disabled||stale||busy||generate.isPending} onClick={()=>generate.mutate({one:true,parent:'',instructions:'Uma nova alternativa desta seção, mantendo a direção compartilhada e variando composição, escala e recortes. Proposta anterior '+v.id+' é candidata, não aprovada.'})}>Gerar outra · 1 proposta</button></div><details><summary>Origem, consumo e instruções</summary><p>{v.observacoes||'Imagem conceitual; fatos e fotos oficiais permanecem sujeitos à revisão.'}</p><p>Modelo: {v.modelo||'Não informado'} · uso: {v.situacao_uso}</p>{v.origem_id&&<p>Original preservado: {v.origem_id}</p>}<pre>{JSON.stringify(v.consumo??'Consumo não informado',null,2)}</pre><pre>{v.prompt||'Instruções externas não informadas.'}</pre></details></div></article>})}</div>:<div className="ed-visual-empty">Ainda sem propostas nesta seção. Gere alternativas com a conexão disponível ou importe imagens candidatas.</div>}
 <div className="ed-visual-generate"><h3><Sparkles size={18}/>{parent?'Refinar uma imagem preservando o original':'Gerar alternativas de composição'}</h3>{parent&&<p>Imagem de origem {parent.slice(0,8)}. Uma nova versão será criada.<button className="ed-button" onClick={()=>setParent('')}>Voltar às alternativas</button></p>}<div className="ed-form-grid"><Field label="Fornecedor de imagem"><select value={provider} disabled={disabled||busy} onChange={e=>setProvider(e.target.value)}><option value="codex_nativo">Codex nativo · conta integrada</option><option value="openrouter">OpenRouter · chave e modelo próprios</option><option value="openai_imagens">OpenAI Images · API e orçamento próprios</option><option value="gateway">Gateway local · capacidade de imagem configurada</option></select></Field><Field label="Quantidade de propostas"><select disabled={disabled||busy||!!parent} value={parent?1:state.quantidade} onChange={e=>onChanged({...state,quantidade:Number(e.target.value)})}>{[1,2,3,4,5,6].map(n=><option key={n}>{n}</option>)}</select></Field></div><Field label="Instruções desta geração ou refinamento"><textarea id="ed-visual-refinar" rows={3} maxLength={6000} value={instructions} disabled={disabled||busy} onChange={e=>setInstructions(e.target.value)} placeholder="Ex.: preservar a tipografia, ampliar o pão da abertura e retirar a seção sem dados confirmados."/></Field><button className="ed-button primary" disabled={disabled||busy||generate.isPending} onClick={()=>generate.mutate(undefined)}>{busy?'Geração em andamento…':parent?'Gerar refinamento':'Gerar '+state.quantidade+' propostas'}</button><p>Sem substituição paga automática. <Link to="/configuracoes/conexoes">Configurar e verificar fornecedores</Link>.</p></div>
 <details><summary>Importar proposta externa</summary><Field label="Imagem candidata PNG, JPEG ou WebP · até 8 MB"><FileInput accept="image/png,image/jpeg,image/webp" disabled={disabled} onChange={e=>setFile(e.target.files?.[0]||null)}/></Field><label className="ed-check"><input type="checkbox" checked={permission} disabled={disabled} onChange={e=>setPermission(e.target.checked)}/>Tenho permissão para usar este arquivo como referência visual interna. Isso não autoriza fotos comerciais.</label><button className="ed-button" disabled={disabled||!file||!permission||upload.isPending} onClick={()=>upload.mutate()}>Importar candidata</button></details>
 {[generate,choose,upload,openSite].filter(m=>m.isError).map((m,i)=><Erro key={i} error={m.error}/>)}
 </section>
}

export function VisualMontage({state}:{state:VisualStudio}){
 const [mobile,setMobile]=useState(false)
 const sections=state.escolhas.pagina?[{id:'pagina',titulo:'Página inteira'}]:state.secoes
 return <><div className="ed-actions"><button className="ed-button" aria-pressed={!mobile} onClick={()=>setMobile(false)}>Montagem ampla</button><button className="ed-button" aria-pressed={mobile} onClick={()=>setMobile(true)}>Montagem estreita</button></div><p>A largura da montagem só ajuda a comparar imagens. A responsividade do site será verificada após construir o HTML.</p><div className={'ed-visual-montage'+(mobile?' mobile':'')}>{sections.map(s=>{const v=state.variantes.find(x=>x.id===state.escolhas[s.id]);return <figure key={s.id}>{v?<Zoom variant={v}/>:<div className="ed-visual-empty">{s.titulo}: escolha pendente</div>}<figcaption>{s.titulo} · {v?v.titulo:'Sem imagem escolhida'}</figcaption></figure>})}</div></>
}

export function VisualOperations({company,jobs,onChange}:{company:string;jobs:VisualJob[];onChange:()=>void}){
 const readonly=useAccess()?.ator?.papel==='leitura'
 const action=useMutation({mutationFn:({id,resume}:{id:string;resume:boolean})=>resume?api.resume(company,id):httpClient.post('/api/ed/operacoes/'+id+'/cancelar',{}),onSuccess:onChange})
 return <details className="ed-panel ed-form" aria-label="Operações do estúdio" open={jobs.some(j=>['na_fila','pesquisando'].includes(j.estado))||undefined}><summary>Andamento e resultados · {jobs.length} execuções</summary>{!jobs.length&&<p>Nenhuma geração iniciada neste projeto. Propostas importadas permanecem disponíveis acima.</p>}{jobs.map(j=><div className="ed-visual-job" key={j.id}><Badge>{j.estado}</Badge><strong> {j.parametros.secao_id} · {j.parametros.concluidas?.length||0}/{j.parametros.quantidade} imagens salvas</strong><p role="status">{j.mensagem}</p><progress value={j.progresso} max={100} aria-label="Progresso da geração"/>{['na_fila','pesquisando'].includes(j.estado)?<button className="ed-button" disabled={readonly||action.isPending} onClick={()=>action.mutate({id:j.id,resume:false})}>Cancelar · manter resultados prontos</button>:['erro','interrompida','cancelada'].includes(j.estado)&&<button className="ed-button" disabled={readonly||action.isPending} onClick={()=>action.mutate({id:j.id,resume:true})}>Retomar propostas pendentes</button>}<details><summary>Registro da execução</summary><p>Execução {j.id} · {j.thread_id||'Thread não informada'} · {j.turn_id||'Turno não informado'}</p>{j.chamada_em_curso&&<p>Resposta da última chamada ainda não confirmada. A retomada verifica o checkpoint antes de repetir uma operação.</p>}{j.diagnostico!=null&&<pre className="ed-notes">{JSON.stringify(j.diagnostico,null,2)}</pre>}</details></div>)}{action.isError&&<Erro error={action.error}/>}</details>
}
