import {useState} from 'react'
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query'
import {httpClient} from '@/services/httpClient'
import {Badge,Erro,Field} from './shared'
import {useAccess} from './accessContext'
import './visualStudio.css'
interface Config {politica:string;limite_imagens:number;limite_usd:number;permitir_pago:boolean;gateway_url:string;gateway_respostas:boolean;gateway_imagens:boolean;modelos:Record<string,string>;modelo_imagens_openai:string;modelo_imagens_openrouter:string}
interface Connection {estado:string;mensagem?:string;data?:string;consumo?:unknown;credencial_presente?:boolean;ultima_operacao_real?:{operacao:string;data:string;modelo?:string}}
interface Status {config:Config;conexoes:Record<string,Connection>}
const connectionLabels:Record<string,string>={operacao_real_validada:'Operação real validada',configurado_nao_validado:'Configurado · operação pendente',acesso_nao_validado:'Acesso ainda não validado',aguardando_configuracao:'Configuração pendente',sem_credencial:'Sem credencial',limitado:'Capacidade limitada',erro:'Erro'}
export function VisualProvidersPanel(){
 const client=useQueryClient(),[edit,setEdit]=useState<Config|null>(null),[key,setKey]=useState(''),[panelPassword,setPanelPassword]=useState(''),[panelConfirm,setPanelConfirm]=useState(''),[result,setResult]=useState(''),admin=useAccess()?.ator?.papel==='administrador'
 const q=useQuery({queryKey:['ed','visual-providers'],queryFn:()=>httpClient.get<Status>('/api/ed/provedores/visual')})
 const invalidate=()=>client.invalidateQueries({queryKey:['ed']})
 const save=useMutation({mutationFn:()=>httpClient.put('/api/ed/provedores/visual/config',edit),onSuccess:()=>{setEdit(null);invalidate()}})
 const secret=useMutation({mutationFn:()=>httpClient.put('/api/ed/provedores/config/gateway-credencial',{valor:key}),onSuccess:()=>{setKey('');invalidate()}})
 const test=useMutation({mutationFn:(p:string)=>httpClient.post<Connection>('/api/ed/provedores/visual/'+p+'/testar',{}),onSuccess:r=>{setResult(r.mensagem||r.estado);invalidate()}})
 const panel=useMutation({mutationFn:()=>httpClient.put<{mensagem:string}>('/api/ed/provedores/visual/config/gateway-painel',{valor:panelPassword}),onSuccess:r=>{setPanelPassword('');setPanelConfirm('');setResult(r.mensagem)}})
 const models=useMutation({mutationFn:(p:string)=>httpClient.get<{modelos:{id:string}[]}>('/api/ed/provedores/visual/'+p+'/modelos?tipo=imagem'),onSuccess:r=>setResult('Catálogo de imagens (acesso ainda não validado): '+r.modelos.map(m=>m.id).join(', '))})
 return <section className="ed-panel ed-form ed-visual-root"><div className="ed-panel-head"><div><h2>Estúdio visual · capacidades por tarefa</h2><p>Imagem nativa, API direta e gateway local têm acesso e consumo próprios.</p></div><Badge>Catálogo ≠ operação</Badge></div><div className="ed-form-grid">{[['codex_nativo','Codex nativo · conta ChatGPT'],['openai_imagens','OpenAI Images · API'],['openrouter','OpenRouter · API direta'],['gateway','9Router · gateway local']].map(([id,label])=>{const c=q.data?.conexoes[id];return <div key={id}><h3>{label}</h3><Badge>{c?connectionLabels[c.estado]||c.estado:'Consultando'}</Badge><p>{c?.mensagem||'Configure a rota e execute uma proposta para comprovar a capacidade.'}</p>{id!=='codex_nativo'&&<p>Credencial: {c?.credencial_presente?'presente no backend':'pendente'}</p>}{c?.ultima_operacao_real&&<p>Última operação real: {c.ultima_operacao_real.operacao} · {c.ultima_operacao_real.modelo} · {c.ultima_operacao_real.data}</p>}<button className="ed-button" disabled={test.isPending} onClick={()=>test.mutate(id)}>Testar conexão e capacidade</button>{id!=='codex_nativo'&&<button className="ed-button" disabled={models.isPending} onClick={()=>models.mutate(id)}>Consultar modelos de imagem</button>}</div>})}</div><p>A operação real de imagem é feita em Criar site → Visual. O teste de conexão consulta protocolo ou catálogo; não gera imagens nem comprova inferência.</p>{result&&<p role="status" className="ed-notes">{result}</p>}
 <details><summary>Gateway local e ações de acesso</summary><p>9Router 0.5.95 em loopback; upstreams não recebem a sessão Codex automaticamente. Configure uma conta autorizada no painel e crie uma chave do gateway. Não habilite combos pagos.</p><Field label="Definir sua senha para o painel local"><input type="password" autoComplete="new-password" disabled={!admin} value={panelPassword} onChange={e=>setPanelPassword(e.target.value)}/></Field><Field label="Confirmar senha do painel"><input type="password" autoComplete="new-password" disabled={!admin} value={panelConfirm} onChange={e=>setPanelConfirm(e.target.value)}/></Field><button className="ed-button" disabled={!admin||panelPassword.length<12||panelPassword!==panelConfirm||panel.isPending} onClick={()=>panel.mutate()}>Definir senha própria · mínimo 12 caracteres</button><p>A senha inicial gerenciada pelo projeto permanece protegida. Defina sua senha acima para entrar no painel sem revelar credenciais do cofre.</p><a href="http://127.0.0.1:20128/dashboard" target="_blank" rel="noreferrer">Abrir painel local do gateway ↗</a><Field label="Chave própria do gateway"><input type="password" autoComplete="off" value={key} disabled={!admin} onChange={e=>setKey(e.target.value)}/></Field><button className="ed-button" disabled={!admin||!key||secret.isPending} onClick={()=>secret.mutate()}>Salvar chave protegida</button><p>OpenRouter usa a chave configurada em Criação e transcrição. OpenAI Images usa sua configuração existente em Integrações. As APIs têm cobrança separada do plano ChatGPT.</p></details>
 <button className="ed-button" disabled={!admin||!q.data} onClick={()=>setEdit(q.data!.config)}>Configurar modelos por tarefa e limites</button>
 {edit&&<div className="ed-form"><div className="ed-form-grid"><Field label="Política de imagem"><select value={edit.politica} onChange={e=>setEdit({...edit,politica:e.target.value})}><option value="so_gratuitos">Somente gratuitos · sem transição paga</option><option value="menor_custo">Menor custo dentro do limite autorizado</option><option value="qualidade">Qualidade · modelo explicitamente escolhido</option></select></Field><Field label="Limite de imagens por operação"><input type="number" min={1} max={30} value={edit.limite_imagens} onChange={e=>setEdit({...edit,limite_imagens:Number(e.target.value)})}/></Field><Field label="Orçamento máximo desta operação · USD"><input type="number" min={0} max={10} step={0.1} value={edit.limite_usd} onChange={e=>setEdit({...edit,limite_usd:Number(e.target.value)})}/></Field><Field label="URL do gateway · somente loopback /v1"><input value={edit.gateway_url} onChange={e=>setEdit({...edit,gateway_url:e.target.value})}/></Field><Field label="Modelo OpenAI Images"><input value={edit.modelo_imagens_openai} onChange={e=>setEdit({...edit,modelo_imagens_openai:e.target.value})}/></Field><Field label="Modelo de imagem OpenRouter"><input value={edit.modelo_imagens_openrouter} onChange={e=>setEdit({...edit,modelo_imagens_openrouter:e.target.value})}/></Field>{Object.entries(edit.modelos).map(([role,value])=><Field key={role} label={'Modelo gateway · '+({brief:'brief',analise_visual:'análise visual',imagem:'imagem',edicao:'edição',codigo:'código',refinamento:'refinamento'}[role]||role)}><input value={value} onChange={e=>setEdit({...edit,modelos:{...edit.modelos,[role]:e.target.value}})}/></Field>)}</div><label className="ed-check"><input type="checkbox" checked={edit.permitir_pago} onChange={e=>setEdit({...edit,permitir_pago:e.target.checked})}/>Autorizar o modelo pago escolhido dentro da reserva verificável. Não habilita fallback pago.</label><label className="ed-check"><input type="checkbox" checked={edit.gateway_imagens} onChange={e=>setEdit({...edit,gateway_imagens:e.target.checked})}/>Upstream do gateway oferece Images API. Esta declaração ainda precisa de geração real.</label><label className="ed-check"><input type="checkbox" checked={edit.gateway_respostas} onChange={e=>setEdit({...edit,gateway_respostas:e.target.checked})}/>Upstream do gateway oferece Responses API. Catálogo de texto não comprova esta capacidade.</label><p>Tarifa desconhecida ou sem teto verificável bloqueia a chamada paga. As preferências não fazem troca silenciosa de modelo.</p><div className="ed-actions"><button className="ed-button primary" disabled={save.isPending} onClick={()=>save.mutate()}>Salvar configuração</button><button className="ed-button" onClick={()=>setEdit(null)}>Fechar</button></div></div>}
 {[q,save,secret,test,models,panel].filter(m=>m.isError).map((m,i)=><Erro key={i} error={m.error}/>)}
 </section>
}
