import {useState,useRef,useEffect} from 'react'
import {useQuery,useQueryClient} from '@tanstack/react-query'
import {Mic,Square,Upload} from 'lucide-react'
import {csrfHeaders} from './accessState'
import {api} from './api'
import {httpClient} from '@/services/httpClient'
import {Erro} from './shared'
export interface Transcript {id:string;original:string}
interface VoiceJob {id:string;estado:string;mensagem:string;resultado?:{texto:string;tempo_transcricao:number;origem:string}}
export function VoiceComposer({onText,disabled=false,onAutoSend,submitted}:{onText:(text:string,source:Transcript)=>void;disabled?:boolean;onAutoSend?:()=>void;submitted?:string}){
 const client=useQueryClient(),[state,setState]=useState('pronto'),[blob,setBlob]=useState<Blob|null>(null),[url,setUrl]=useState(''),[error,setError]=useState<Error|null>(null),[seconds,setSeconds]=useState(0),[provider,setProvider]=useState('local'),[keep,setKeep]=useState(false),[auto,setAuto]=useState(()=>localStorage.getItem('edy-voz-auto')==='true'),[countdown,setCountdown]=useState(0),[job,setJob]=useState(''),[install,setInstall]=useState('')
 const captureOrigin=useRef('nao_informada')
 useEffect(()=>{if(submitted&&submitted===job){setState('enviado');setCountdown(0)}},[submitted,job])
 const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),timer=useRef<ReturnType<typeof setInterval>|null>(null),discard=useRef(false),mounted=useRef(true),key=useRef(''),accepted=useRef(''),epoch=useRef(0),autoCallback=useRef(onAutoSend)
 autoCallback.current=onAutoSend
 const local=useQuery({queryKey:['ed','voz-local'],queryFn:()=>httpClient.get<{instalado:boolean;mensagem:string;modelo:string}>('/api/ed/voz/local/status')}),operation=useQuery({queryKey:['ed','voz-job',job],enabled:!!job,queryFn:()=>httpClient.get<VoiceJob>('/api/ed/operacoes/'+job),refetchInterval:q=>['na_fila','pesquisando'].includes(q.state.data?.estado||'na_fila')?700:false}),installation=useQuery({queryKey:['ed','voz-install',install],enabled:!!install,queryFn:()=>api.operacao(install),refetchInterval:q=>['na_fila','pesquisando'].includes(q.state.data?.estado||'na_fila')?1500:false})
 function close(){if(timer.current)clearInterval(timer.current);timer.current=null;stream.current?.getTracks().forEach(x=>x.stop());stream.current=null}
 function cleanupVoice(){mounted.current=false;epoch.current++;discard.current=true;if(recorder.current?.state==='recording')recorder.current.stop();close()}
 useEffect(()=>{mounted.current=true;return cleanupVoice},[])
 useEffect(()=>{if(!blob){setUrl('');return}const v=URL.createObjectURL(blob);setUrl(v);return()=>URL.revokeObjectURL(v)},[blob])
 useEffect(()=>{if(installation.data?.estado==='concluida')client.invalidateQueries({queryKey:['ed','voz-local']})},[installation.data?.estado,client])
 useEffect(()=>{const d=operation.data;if(!d||accepted.current===d.id||!['concluida','erro','cancelada','interrompida'].includes(d.estado))return;accepted.current=d.id;if(d.estado==='concluida'&&d.resultado?.texto){onText(d.resultado.texto,{id:d.id,original:d.resultado.texto});setState('transcrito');if(auto&&onAutoSend)setCountdown(5)}else{setState('capturado');setError(new Error(d.mensagem));key.current=crypto.randomUUID()}},[operation.data,onText,auto,onAutoSend])
 useEffect(()=>{if(!countdown)return;const t=setTimeout(()=>{if(countdown===1){setCountdown(0);autoCallback.current?.()}else setCountdown(countdown-1)},1000);return()=>clearTimeout(t)},[countdown])
 async function transcribe(audio:Blob){const ticket=++epoch.current;setState('processando');setError(null);setCountdown(0);try{const f=new FormData();f.append('arquivo',audio,'comando');f.append('chave',key.current);f.append('provedor',provider);f.append('manter_audio',String(keep));f.append('captura_origem',captureOrigin.current);const r=await fetch('/api/ed/voz/transcricoes',{method:'POST',headers:csrfHeaders(),body:f});const d=await r.json();if(!r.ok)throw new Error(d.erro);if(!mounted.current||ticket!==epoch.current){await api.cancelarOperacao(d.id);return}setJob(d.id)}catch(e){if(mounted.current&&ticket===epoch.current){setState('capturado');setError(e instanceof Error?e:new Error('Transcrição indisponível; texto e áudio preservados.'))}}}
 async function record(){const ticket=++epoch.current;setError(null);setBlob(null);setJob('');setCountdown(0)
  if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined'){setError(new Error('Captura indisponível. Envie um áudio ou escreva no chat.'));return}
  setState('permissao');discard.current=false;captureOrigin.current='microfone_navegador'
  try{const s=await navigator.mediaDevices.getUserMedia({audio:true});if(!mounted.current||discard.current||ticket!==epoch.current){s.getTracks().forEach(t=>t.stop());return}stream.current=s
   const mime=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus'].find(x=>MediaRecorder.isTypeSupported(x)),r=new MediaRecorder(s,mime?{mimeType:mime}:undefined),parts:BlobPart[]=[];recorder.current=r;key.current=crypto.randomUUID()
   r.ondataavailable=e=>{if(e.data.size)parts.push(e.data)}
   r.onstop=()=>{close();if(!mounted.current)return;if(!discard.current){const b=new Blob(parts,{type:r.mimeType});setBlob(b);void transcribe(b)}else setState('pronto')}
   r.onerror=()=>{discard.current=true;close();if(mounted.current){setState('erro');setError(new Error('A gravação falhou. Confira o dispositivo ou envie um áudio.'))}}
   r.start();setSeconds(0);setState('gravando');let elapsed=0;timer.current=setInterval(()=>{setSeconds(++elapsed);if(elapsed>=180&&r.state==='recording')r.stop()},1000)
  }catch(e){if(mounted.current&&ticket===epoch.current){close();setState('erro');const name=e instanceof Error?e.name:'';setError(new Error(name==='NotAllowedError'?'Microfone bloqueado pelo navegador. Permita o acesso nas configurações deste site ou envie um áudio.':name==='NotFoundError'?'Nenhum microfone encontrado. Conecte um dispositivo ou envie um áudio.':name==='NotReadableError'?'Microfone ocupado ou indisponível. Confira o dispositivo e tente novamente.':e instanceof Error?e.message:'Permissão do microfone não concedida.'))}}
 }
 async function cancel(){epoch.current++;discard.current=true;if(recorder.current?.state==='recording')recorder.current.stop();close();setCountdown(0);try{if(job&&['na_fila','pesquisando'].includes(operation.data?.estado||'na_fila'))await api.cancelarOperacao(job)}catch(e){setError(e as Error)}setJob('');setBlob(null);setState('pronto')}
 const busy=['gravando','processando','permissao'].includes(state),installing=!!install&&['na_fila','pesquisando'].includes(installation.data?.estado||'na_fila')
 return <div className="ed-voice" aria-label="Ditado no compositor"><div className="ed-actions"><button type="button" className="ed-button" disabled={disabled||busy} onClick={record}><Mic size={16}/> Gravar áudio</button><label className="ed-button"><Upload size={16}/> Enviar áudio<input aria-label="Arquivo de áudio" className="ed-sr-only" type="file" accept="audio/*,.m4a" disabled={disabled||busy} onChange={e=>{const f=e.target.files?.[0];if(f){captureOrigin.current='upload';setBlob(f);setJob('');key.current=crypto.randomUUID();void transcribe(f)}e.target.value=''}}/></label>{state==='gravando'&&<button type="button" className="ed-button" onClick={()=>recorder.current?.stop()}><Square size={16}/> Parar · {seconds}s</button>}{busy&&<button type="button" className="ed-button" onClick={()=>void cancel()}>Cancelar voz</button>}</div>
 <p role="status">{state==='permissao'?'Aguardando permissão do microfone.':state==='processando'?operation.data?.mensagem||'Transcrevendo…':state==='gravando'?'Gravando localmente; até três minutos.':state==='enviado'?'Áudio enviado à conversa. Acompanhe o refinamento acima.':state==='transcrito'?'Pronto para enviar: revise o texto no compositor.':'Transcrição: '+(provider==='local'?'Local · sem cobrança externa':provider==='openai'?'OpenAI API · cobrança separada':'OpenRouter · cobrança separada')+'. Gravar não inicia construção.'}</p>
 {!!countdown&&<p role="alert">Enviar ao terminar: {countdown}s <button type="button" className="ed-button" onClick={()=>setCountdown(0)}>Cancelar envio automático</button></p>}
 {blob&&<details><summary>Ouvir gravação ou descartar áudio</summary><audio aria-label="Ouvir gravação" controls src={url}/><div className="ed-actions"><button type="button" className="ed-button" disabled={busy||disabled} onClick={()=>{key.current=crypto.randomUUID();void transcribe(blob)}}>Tentar transcrição novamente</button><a className="ed-button" href={url} download="comando-edy">Salvar captura</a><button className="ed-button" type="button" onClick={()=>void cancel()}>Descartar captura</button>{job&&!busy&&<button className="ed-button" type="button" onClick={async()=>{try{await httpClient.delete('/api/ed/voz/transcricoes/'+job+'/audio');setKeep(false)}catch(e){setError(e as Error)}}}>Apagar áudio do servidor</button>}</div></details>}
 <details><summary>Teste guiado do microfone</summary><ol><li>Clique em Gravar áudio e permita o microfone neste navegador.</li><li>Fale uma alteração curta, depois clique em Parar.</li><li>Ouça a gravação e confira a transcrição no campo de comando.</li><li>Corrija o texto e clique em Enviar. Confira a nova versão na mesma conversa.</li></ol><p>Captura pelo microfone físico requer sua fala. Testes sintéticos ou upload não comprovam essa etapa. Em caso de falha, continue por texto ou envie uma gravação.</p></details>
 {error&&<Erro error={error}/>}
 <details><summary>Preferências de voz</summary><label>Transcrição<select aria-label="Transcrição" value={provider} disabled={busy} onChange={e=>{setProvider(e.target.value);key.current=crypto.randomUUID()}}><option value="local">Local · faster-whisper small PT-BR</option><option value="openai">OpenAI · requer chave e saldo próprios</option><option value="openrouter">OpenRouter · requer chave e modelo STT</option></select></label><label className="ed-check"><input type="checkbox" checked={keep} disabled={busy} onChange={e=>setKeep(e.target.checked)}/> Reter áudio no workspace (padrão: apagar após transcrever)</label>{onAutoSend&&<label className="ed-check"><input type="checkbox" checked={auto} disabled={busy} onChange={e=>{setAuto(e.target.checked);if(!e.target.checked)setCountdown(0);localStorage.setItem('edy-voz-auto',String(e.target.checked))}}/> Enviar ao terminar, após cinco segundos para cancelar</label>}<p>{local.data?.mensagem} Máximo 8 MB / 180s; um worker de transcrição. Áudios não são instruções até o envio do texto.</p>{local.data&&!local.data.instalado&&<button type="button" disabled={installing||disabled} className="ed-button" onClick={async()=>{try{const d=await httpClient.post<{id?:string}>('/api/ed/voz/local/instalar',{});if(d.id)setInstall(d.id);else client.invalidateQueries({queryKey:['ed','voz-local']})}catch(e){setError(e as Error)}}}>{installing?'Instalando…':'Instalar modelo local (~500 MB)'}</button>}{installation.data&&<p role="status">{installation.data.mensagem}</p>}</details></div>
}
