import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query'
import {Link} from 'react-router-dom'
import {httpClient} from '@/services/httpClient'
import {Badge,Erro} from './shared'

export interface Workflow{id:string;estado:string;mensagem:string;plano:{acao:string;empresa_id?:string};etapas:{nome:string;estado:string;tentativas:number;resultado:Record<string,unknown>|null;operacao_id?:string}[]}
const labels:Record<string,string>={na_fila:'Na fila',executando:'Executando',aguardando_dependencia:'Aguardando dependência',pausada:'Pausada',cancelada:'Cancelada',falhou:'Falhou',parcial:'Parcialmente concluída',concluida:'Concluída'}
function ChildProgress({id}:{id:string}){
 const q=useQuery({queryKey:['ed','operacao',id],queryFn:()=>httpClient.get<{estado:string;mensagem:string;progresso:number;brief_aplicado?:{versao:number}}>( '/api/ed/operacoes/'+id),refetchInterval:1500})
 if(q.isError)return <Erro error={q.error}/>
 return q.data&&<div role="status"><p>{q.data.mensagem}{q.data.brief_aplicado&&' · brief v'+q.data.brief_aplicado.versao}</p><progress max={100} value={q.data.progresso} aria-label="Etapa da operação Codex"/><small>Progresso por etapa; não é uma estimativa de tempo restante.</small></div>
}
export function WorkflowCard({id}:{id:string}){
 const client=useQueryClient(),q=useQuery({queryKey:['ed','fluxo',id],queryFn:()=>httpClient.get<Workflow>('/api/ed/fluxos/'+id),refetchInterval:q=>['na_fila','executando'].includes(q.state.data?.estado||'na_fila')?1500:false})
 const action=useMutation({mutationFn:(a:string)=>httpClient.post('/api/ed/fluxos/'+id+'/'+a),onSuccess:()=>client.invalidateQueries({queryKey:['ed']})})
 if(q.isError)return <Erro error={q.error}/>
 if(!q.data)return <p>Carregando execução…</p>
 const j=q.data,complete=j.etapas.filter(s=>s.estado==='concluida').length,active=['na_fila','executando'].includes(j.estado)
 return <article className="ed-flow-card"><div className="ed-panel-head"><h3>{({consultar:'Consultar leads',pesquisar:'Pesquisar e preparar',preparar:'Preparar prévia',gerar:'Criar prévia do brief',refinar:'Refinar projeto'} as Record<string,string>)[j.plano.acao]||'Execução'} · {complete}/{j.etapas.length} etapas</h3><Badge tone={j.estado==='concluida'?'green':'amber'}>{labels[j.estado]||j.estado}</Badge></div><p role="status">{j.mensagem}</p><progress max={j.etapas.length} value={complete} aria-label="Etapas concluídas"/>{active&&j.etapas.filter(s=>s.estado==='executando'&&s.operacao_id&&['gerar','refinar'].includes(s.nome)).map(s=><ChildProgress key={s.operacao_id} id={s.operacao_id!}/>)}{j.estado==='parcial'&&<p className="ed-alert">As etapas executadas não significam que todas as informações foram confirmadas. Revise as pendências da ficha e continue pelas fontes disponíveis.</p>}{j.etapas.filter(s=>s.resultado).slice(-1).map((s,i)=><Result key={i} value={s.resultado!}/>)}<details><summary>Etapas, resultados parciais e diagnóstico</summary><ol className="ed-flow-steps">{j.etapas.map((s,i)=><li key={i}><strong>{s.nome}</strong><span>{s.estado} · {s.tentativas} tentativa(s)</span>{s.operacao_id&&<small>Operação: {s.operacao_id}</small>}{s.resultado&&<Result value={s.resultado}/>}</li>)}</ol></details><div className="ed-actions">{active&&<button className="ed-button" disabled={action.isPending} onClick={()=>action.mutate('pausar')}>Pausar</button>}{!['concluida','cancelada'].includes(j.estado)&&<button className="ed-button" disabled={action.isPending} onClick={()=>action.mutate('cancelar')}>Cancelar</button>}{!active&&!['concluida'].includes(j.estado)&&complete<j.etapas.length&&<button className="ed-button" disabled={action.isPending} onClick={()=>action.mutate('retomar')}>Retomar checkpoints</button>}</div>{action.isError&&<Erro error={action.error}/>}</article>
}
function Result({value:v}:{value:Record<string,unknown>}){
 const company=String(v.empresa_id||''),url=String(v.url_ativa||''),inactive=typeof v.url==='string'&&!url,stable=typeof v.abrir_url==='string'&&v.abrir_url.startsWith('/previas/')?v.abrir_url:''
 return <div className="ed-flow-result">{typeof v.miniatura_url==='string'&&v.miniatura_url.startsWith('/api/ed/')&&<img className="ed-batch-thumbnail" src={v.miniatura_url} alt="Captura real do projeto" loading="lazy"/>}{stable&&<Link className="ed-button primary" to={stable}>Abrir prévia</Link>}{company&&<Link to={'/empresas/'+company}>Abrir ficha ↗</Link>}{url.startsWith('http://127.0.0.1:')&&<a href={url} target="_blank" rel="noreferrer">Abrir prévia local ↗</a>}{inactive&&<small>Servidor parado. Abrir prévia recupera a versão salva sem nova geração.</small>}{typeof v.zip_url==='string'&&v.zip_url.startsWith('/api/ed/')&&<a href={v.zip_url}>Baixar pacote ZIP</a>}{Array.isArray(v.empresas)&&v.empresas.map((r)=><Link key={r.id} to={'/empresas/'+r.id}>{r.nome} ↗</Link>)}{typeof v.whatsapp==='string'&&<p className="ed-notes">Rascunho · sem envio: {v.whatsapp}</p>}{Array.isArray(v.pendencias)&&v.pendencias.length>0&&<details><summary>{v.pendencias.length} pendências</summary><ul>{v.pendencias.map((p,i)=><li key={i}>{String(p)}</li>)}</ul></details>}<details><summary>Resultado e origem</summary><pre>{JSON.stringify(v,null,2)}</pre></details></div>
}
